Seagate/cortx-hare

- hax/hax/exception.py
- hax/hax/filestats.py
Solution: don't use time.sleep(). Instead, use [threading.Event](https://docs.python.org/3/library/threading.html#event-objects) that can be canceled from another thread (and the waiting thread will react immediately).
Note: this is a resurrected version of #1338 made for main branch.
Relates to [EOS-13393](https://jts.seagate.com/browse/EOS-13393).
> Problem: sleeps in filestats.py can make hax hang

- hax/hax/exception.py
- hax/hax/filestats.py
Solution: don't use time.sleep(). Instead, use [threading.Event](https://docs.python.org/3/library/threading.html#event-objects) that can be canceled from another thread (and the waiting thread will react immediately).
Note: this is a resurrected version of #1338 made for cortx-1.0 branch.
Relates to [EOS-13393](https://jts.seagate.com/browse/EOS-13393).
> Problem: sleeps in filestats.py can make hax hang (cortx-1.0)

- provisioning/hare-logrotate
Solution: replace 'size' with 'maxsize', which doesn't comflict with
'weekly' time interval option of lograte.
Additionally, increase max size of a log file to 50MB. Rotated logs are
compressed, with an avg ratio around 10:1 to 50:1, so total size of the
logs should not exceed 100MB, given that 10 last rotations are stored.
'copytruncate' option ensures that Hare applications can continue
logging information w/o needing to re-open the log file after each
rotation.
> Problem: logrotate config uses mutually exclusive options

- utils/build-ees-ha
This makes s3server to fail and produce a lot of traces which consume
disk space on shared partition affecting another node.
ClusterIP resource shall also migrate after motr-stack since "failed"
node can't serve requests anymore.
Solution:
* Add hax-running attribute which is set to 1 when hax is
started on current node and set to 0 when hax is stopped (Exec Post-hooks
in systemd file).
* Add location constrains for ClusterIP-clone and s3auth-clone resources
to make them migrate/stop when hax (i.e. motr-stack) is not running on
current node. Since s3server-cN resources are colocated with s3auth
and can't work on opposite nodes - they will be stopped on "failed"
node.
Signed-off-by: Andrei Zheregelia <andrei.zheregelia@seagate.com>
> Problem: S3 resources do not stop when motr stack migrated to another node

- hax/hax/filestats.py
- hax/hax/handler.py
- hax/hax/hax.py
- hax/hax/motr/__init__.py
- hax/hax/motr/delivery.py
- hax/hax/motr/ffi.py
- hax/hax/queue/__init__.py
- hax/hax/queue/offset.py
- hax/hax/server.py
- hax/hax/servicemon.py
- hax/hax/types.py
- hax/hax/util.py
- stubs/consul/__init__.pyi
- systemd/consul-client-conf.json.in
- systemd/consul-server-conf.json.in
The issue is caused by this Consul bug reported by @andriytk this winter: https://github.com/hashicorp/consul/issues/7069
The main problem with these delayed service watch handler invocations is that sometimes hax can broadcast (erroneously) a Motr service state as M0_NC_FAILED while the service is actually up and running. Such a broadcast will force all Motr processes and services to disconnect that service that will cause to bigger problems (as listed in https://jts.seagate.com/browse/EOS-13678)
Workaround: don't rely on watch mechanism. Instead, poll the service health status directly from Consul via Health API.
Note: This PR repeats https://github.com/Seagate/cortx-hare/pull/1348 for cortx-1.0 branch
> EOS-13678: Consul doesn't always invoke service watcher (cortx-1.0)

- hax/hax/queue/__init__.py
**Note: for main branch only**
The fix with service health polling brought a regression (due to the
lack of typing in Python code).
HAState.status field changed its type: str -> ServiceHealth but the code
in drive failure event processing didn't reflect that change.
Solution:
1. Improve type hints in drive failure event processing logic (so that
the problem becomes obvious)
2. Fix the code.
Notes: cortx-1.0 branch doesn't have this problem (I saw it and resolved while resolving the merge conflicts in https://github.com/Seagate/cortx-hare/pull/1350). So this change is needed for main branch only.
> Problem: Rule for drive failure event is broken

- utils/hare-reportbug
Syslog in JSON format is required as input for analysis scripts.
Solution: add command to generate reqired log file
Signed-off-by: Andrei Zheregelia <andrei.zheregelia@seagate.com>
> Problem: reportbug tool doesn't generate syslog in JSON format

- hax/hax/util.py
At HW logs I saw the following error stacktrace (when Consul became
unavailable):
```
Oct 08 07:27:49 inteln13-m07.colo.seagate.com hare-hax[140861]: 2020-10-08 07:27:49,152 [ERROR] {service-monitor} Aborting due to an error
Oct 08 07:27:49 inteln13-m07.colo.seagate.com hare-hax[140861]: Traceback (most recent call last):
Oct 08 07:27:49 inteln13-m07.colo.seagate.com hare-hax[140861]: File "/opt/seagate/cortx/hare/lib64/python3.6/site-packages/hax/servicemon.py", line 94, in _execute
Oct 08 07:27:49 inteln13-m07.colo.seagate.com hare-hax[140861]: name)
Oct 08 07:27:49 inteln13-m07.colo.seagate.com hare-hax[140861]: File "/opt/seagate/cortx/hare/lib64/python3.6/site-packages/hax/util.py", line 454, in get_local_service_health
Oct 08 07:27:49 inteln13-m07.colo.seagate.com hare-hax[140861]: …
```
> Problem: service-monitor thread can exit early if Consul fails

- utils/bootstrap-node
- utils/check-service
- utils/get-service-health
- utils/hare-bootstrap
During cluster bootstrap with --mkfs option, it is possible
that ha-online notification from Consul about the Motr service
when its m0mkfs process is started will not manage to change
to ha-offline after m0mkfs process has finished. Instead, it
may come after the correspondent m0d process is started already.
This will cause hax to close the ha_link to the newly started
m0d process, so the process would panic:
```
Jan 03 13:02:01.356617 hare64648-build-ssu1 mero-server[5124]: Mero panic: !rep->hae_disconnected_previously at ha_entrypoint_state_cb() ha/ha.c:308 (errno: 0) (last failed: none) [git: 8d44b0a8a] pid: 5124  /var/mero/m0d-0x7200000000000001:0xc/m0trace.5124
Jan 03 13:02:01.356949 hare64648-build-ssu1 mero-server[5124]: Mero panic reason: HA has already decided that this process …
```
> EOS-14115: fix ha-notifications race during bootstrap

- utils/bootstrap-node
- utils/check-service
- utils/get-service-health
- utils/hare-bootstrap
During cluster bootstrap with --mkfs option, it is possible
that ha-online notification from Consul about the Motr service
when its m0mkfs process is started will not manage to change
to ha-offline after m0mkfs process has finished. Instead, it
may come after the correspondent m0d process is started already.
This will cause hax to close the ha_link to the newly started
m0d process, so the process would panic:
```
Jan 03 13:02:01.356617 hare64648-build-ssu1 mero-server[5124]: Mero panic: !rep->hae_disconnected_previously at ha_entrypoint_state_cb() ha/ha.c:308 (errno: 0) (last failed: none) [git: 8d44b0a8a] pid: 5124  /var/mero/m0d-0x7200000000000001:0xc/m0trace.5124
Jan 03 13:02:01.356949 hare64648-build-ssu1 mero-server[5124]: Mero panic reason: HA has already decided that this process …
```
> EOS-14115: fix ha-notifications race during bootstrap #1363

- Makefile
- provisioning/logrotate/virtual
- provisioning/setup.py
- provisioning/setup.yaml
- provisioning/setup_info.json
- utils/m0trace-prune
- CSM requires Hare to report any unavailable features based on the
installation type.
- Logrotate settings for hare logs must be configured based on the given installation
type. Such a utility is missing in hare.
- Cron job for pruning hax m0trace files is also missing based on the installation
type.
Solution:
- Add a utility to accept options for configuring logrotate and to report
masked features based on the installation type fetched from the provisioner.
Sample provisioner installation information,
```
{
"ret": {
"nodes": 1,
"server_type": "physical",
"servers_per_node": 2,
"storage_type": "5u84"
}
}
```
- Add a cron job script to prune /var/motr/hax/m0trace.* files based on the
installation type (virtual or physical).
> EOS-13263: Hare utility to mask features and logrotate configuration is missing

- hare.spec
Hare logrotate file is copied as /etc/logrotate.d/hare by setup.py but
hare.spec is referring to /etc/logrotate.d/hare_logrotate.
Solution:
Fix hare logrotate file name in hare.spec from /etc/logrotate.d/hare_logrotate
to /etc/logrotate.d/hare
> Problem: rpm build fails due to wrong logrotate file in hare.spec

- Makefile
- provisioning/logrotate/hare
Hare logrotate configuration is supposed to be installed at
/etc/logrotate.d/hare as part of rpm build but the installation
code is missing from the Makefile. This was added as part of
the commit `0cd9cb4` but was removed by `3483beb` as the logrotate
configuration is required to be installed as per the installation type
(i.e. virtual or physical) using hare setup.py utility as part of
the provisioning. But this is breaking the rpm build presently.
Solution:
Restore /etc/logrotate.d/hare installation logic in Makefile and
install a default logrotate configuration ($HARE_SRC/provisioning/
logrotate/hare) for hare before setup.py utility is invoked to
update it as per the installation type.
> Problem: rpm build for hare main branch fails

- utils/hare-reportbug
Solution: include `hctl status` output into `hctl reportbug` bundle.
Limit max execution time of `hctl status` command to 30 seconds in case
it hangs.
> Problem: `hctl status` output isn't part of `hctl reportbug` bundle

- README.md
It's not enough to set M0_SRC_DIR, we need to export it also.
> README: add export when setting M0_SRC_DIR

- Makefile
- hare.spec
- provisioning/logrotate/hare
- provisioning/logrotate/virtual
- provisioning/setup.py
- provisioning/setup.yaml
- provisioning/setup_info.json
- utils/m0trace-prune
- CSM requires Hare to report any unavailable features based on the
installation type.
- Logrotate settings for hare logs must be configured based on the given installation
type. Such a utility is missing in hare.
- Cron job for pruning hax m0trace files is also missing based on the installation
type.
Solution:
- Add a utility to accept options for configuring logrotate and to report
masked features based on the installation type fetched from the provisioner.
Sample provisioner installation information,
```
{
"ret": {
"nodes": 1,
"server_type": "physical",
"servers_per_node": 2,
"storage_type": "5u84"
}
}
```
- Add a cron job script to prune /var/motr/hax/m0trace.* files based on the
installation type (virtual or physical).
- Use asyncio to invoke csm api store_unsupported_features() …
> Problem: Hare utility to mask features and logrotate configuration is missing

- provisioning/logrotate/physical
- provisioning/setup.py
- provisioning/setup_info.json
eos.utils python utils package is renamed to cortx-py-utils. Also
logrotate configuration file for `physical` setup is missing.
Solution:
- Use cortx-utils package instead of eos.utils package.
- Add logrotate configuration file for `physical` setups.
- Update setup_info.json file to use `server_type` instead of name.
> Problem: setup.py uses wrong utils package

- cfgen/cfgen
- cfgen/dhall/types.dhall
- cfgen/dhall/types/DiskRef.dhall
- cfgen/dhall/types/PoolsRef.dhall
- cfgen/examples/multipools.yaml
- cfgen/examples/singlenode.yaml
- cfgen/tests/singlenode.dhall
- rfc/11/README.md
- rfc/4/README.md
- utils/hare-status
- utils/m0crate-io-conf
- utils/update-consul-conf
This patch should not break LDR1 setups (they use single SNS pool).  Please run the usual set of LDR1 tests (preferably on HW setup) and if they pass — merge the patch.  It's OK to postpone testing of multipool configurations.  **The longer this branch remains unmerged, the more it rots.**
---
Context:
- _Pools_ refer to non-overlapping sets of disks.
- _Profile_ is a reference to one or more pools.
- When Motr client is started, it receives profile fid from the command line.  Motr client will only be able to use those pools, which are referred to by its profile.
So far `cfgen` was only able to generate Motr configuration with a single SNS pool and a single profile.  This patch adds multipools support.
Solution:
* Extend CDF format so that multiple SNS pools and profiles can be specified: …
> Problem: multiple SNS pools are not supported

- utils/hare-reportbug
* Break down systemd logs to dedicated files: each contains one boot
* Save entire /var/logs/cluster directory to fetch rotated logs as well
Details are available in commit description.
> Improve hctl reportbug

- Makefile
- hare.spec
Solution: Fix installation of m0trace-prune cron file by using DESTDIR prefix for `install` target and referring the file with `%{_sysconfdir}/cron.hourly/*` in hare.spec.
Closes #1388.
> Problem: make rpm fails as non-root

- hare.spec
Solution: instruct rpm's internal linter to target python3 syntax instead of python2.
> Problem: rpmbuild reports python syntax warnings

- .github/stale.yml
Solution: revert to the [default settings](https://github.com/probot/stale#usage) of the bot, which are quite reasonable and not spammy.
Signed-off-by: Valery V. Vorotyntsev <valery.vv@gmail.com>
> Problem: 'Stale' bot spams with notifications

- hax/hax/motr/__init__.py
When motr service (confd or ioservice) fails Consul detects the same via hare
consul service watcher. The state is updated in the Consul services catalog which
is then replicated to all the Consul nodes. Consul agents notify the the local hare
hax service which then broadcasts the event to all the local motr processes.
The failure broadcast was happening which helps motr clients to disconnect
from the failed peer motr service but service online broadcast did not
happen due to wrong status check. Due to this the motr cliens were not able
to re-establish the connection with the restarted motr service.
The consul service watch mechanism is based on systemd and watches systemd unit state.
The watch is triggered every 1s and every change in systemd unit is detected and
notified to hax service …
> EOS-14192: IO fails after ioservice restart

- hax/hax/handler.py
Problem: Hax consumer thread logs long debug messages
Hax consymer thread writes long debug log messages. It creates
IEM processing in SSPL slow. This needs to be fixed by writing
proper optimised messages.
Solution:
Skip long hax debgug messages.
> Problem: Hax consumer thread logs long debug messages

- hax/hax/motr/__init__.py
- hax/hax/motr/delivery.py
- hax/hax/motr/hax.c
- hax/hax/server.py
- hax/hax/types.py
- hax/hax/util.py
Motr process now notifies systemd a bit later than earlier. During node crash and failover,
Consul and watcher is up and it finds that motr confd process has not started yet.
Presently Hax just checks if the status of the process is passing where if the process is in
activating state its corresponding consul status is warning, this is interpreted as failed by hax.
Meanwhile, the entrypoint request from motr process is been serviced by hax, once motr gets the
entrypoint reply the halink is established. In parallel hax decides that the process has failed
because the status reported by Consul is warning and not passing. Hax notifies the same to
everyone including itself and disconnects the halink with the just started motr process.
On receiving the failure notification motr process tries to …
> Problem: delayed motr service failure notification from hax leads to motr crash

- utils/bootstrap-node
Currently, hax starts on the nodes which run confd or ios
which is wrong. Client-only nodes should have hax running also.
Solution: fix bootstrap-node to start hax always on the node,
regardless of its configuration.
> bootstrap-node: fix hax startup of client-only nodes

- cfgen/cfgen
- cfgen/dhall/types/ClusterDesc.dhall
- rfc/18/README.md
Currently, any cluster node requires confd or ios to be
configured, which is wrong for the client-only nodes.
Solution: fix cfgen to support client-only nodes which don't
requite confd or ios to be configured.
Closes #1401.
> cfgen: fix client-only nodes configuration

- hax/hax/filestats.py
- hax/hax/hax.py
- hax/hax/motr/__init__.py
- hax/hax/server.py
Various sub-modules of hax create multiple ConsulUtil instances which in turn create multiple Consul objects. These objects are usually destroyed by Python's GC, but sometimes there might be lagging and the number of such connections would grow beyond 200 - the default limit in Consul. After this, nobody could connect
to Consul.
Solution: re-use the ConsulUtil object instantiated by hax.py in various other hax submodules.
> Problem: hax creates multiple ConsulUtil instances

- hax/hax/filestats.py
- hax/hax/hax.py
- hax/hax/motr/__init__.py
- hax/hax/server.py
Various sub modules of hax create multiple ConsulUtil instances which
inturn create multiple Consul objects. In running cluster and with rising consul
users there's a possiblity that the default number of allowed Consul client http connections
(200) may exceed which leeds to Consul randomly dropping the subsequent http requests.
This is presently leading to hax exception (as below) and prevents from updating filesystem
stats in Concul kv leading to EOS-15143 issue.
Exception stack is as follows (trace truncated),
```
Nov 22 11:14:20 ssc-vm-c-0552.colo.seagate.com hare-hax[11757]: Traceback (most recent call last):
Nov 22 11:14:20 ssc-vm-c-0552.colo.seagate.com hare-hax[11757]: File "/opt/seagate/cortx/hare/lib/python3.6/site-packages/urllib3/connectionpool.py", line 706, in urlopen
Nov 22 …
```
> EOS-15143: Consul http_max_conns_per_client exceeds and leads to connection reset

- hax/hax/filestats.py
- hax/hax/util.py
The changes in this PR are for two issues :
1. The original one as reported in JIRA ticket :
In this, hax service had got stopped upon getting HAConsistencyException while trying to access Consul KV in function get_conf_obj_status. This had happened when the consul had lost the leader and new leader election again had happened. So, in this PR the decorator has been put for get_conf_obj_status to make retries forever.
2. The issue which I had seen during attempts to repro, and mentioned in the JIRA ticket comments (failure which had occurred during access to consul catalog) :
Similar to above, the decorator has been put around function "_ensure_motr_all_started".
The testing for this issue has been done by killing the consul process and checking that the retries are being made and recovery …
> EOS-14739:fs_free_seg, fs_free_disk is not reducing after a huge s3 IOs

- systemd/hare-consul
- utils/mk-consul-env
Rename `consul-<IP>` to `consul-data-<IP>` so that it would be
easier to filter out the consul-data directory from the rest
of the configuration files at /var/lib/hare.
> hare-consul: improve consul-data dir name

- cfgen/Makefile
- cfgen/cfgen
- hax/hax/hax.py
- hax/hax/server.py
- hax/mypy.ini
Solution:
1. make mypy behavior stricter. Use `--check-untyped-defs` flags
everywhere in the build pipeline. More details on this solution: https://mypy.readthedocs.io/en/stable/common_issues.html#no-errors-reported-for-obviously-wrong-code)
2. fix the type errors uncovered by enabling this mode.
The issue was revealed in #1410
>  Problem: mypy doesn't detect missing args of function

- hax/hax/handler.py
- hax/hax/hax.py
- hax/hax/message.py
- hax/hax/motr/__init__.py
- hax/hax/motr/delivery.py
- hax/hax/motr/hax.c
- hax/hax/server.py
- hax/hax/types.py
- hax/hax/util.py
- hax/test/test_delivery_herald.py
Motr process states are persisted in Consul by hax as and when the motr
process updates the same to hax. But the process failure is not updated
in the Consul when a motr process crashes abrubtly, in which case no
process event is sent.
fsStatsUpdater thread in the hax checks the motr processes (confd, ios)
state in Consul and if all are STARTED then it starts rconfc and tries to
fetch statistics from motr. So if the failure state is not updated in Consul
fsStatsUpdater always see the motr process states as STARTED and keeps trying
in which case rconfc fails too.
Solution:
Update process failuer in Consul by updating the motr process state to
M0_CONF_HA_PROCESS_STOPPED.
> Problem: Consul state is not updated in case of process failure

- utils/hare-shutdown
Currently, when shutting down the cluster user see this:
```
$ hctl shutdown
...
Killing RC Leader at cmu.local... **ERROR**
```
Which is scarry and misleading.
Solution: fix the msg so it looks like this:
```
Shutting down RC Leader at cmu.local... OK
```
> hctl: fix shutdown msg about RC Leader

- utils/hare-shutdown
flake8 validation fails,
```
13:16:52  make[4]: Entering directory `/root/rpmbuild/BUILD/cortx-hare/cfgen'
13:16:52  utils/hare-shutdown:217:80: E501 line too long (82 > 79 characters)
13:16:52  utils/hare-shutdown:218:38: W504 line break after binary operator
13:16:52  utils/hare-shutdown:219:17: E127 continuation line over-indented for visual indent
13:16:52  make[3]: *** [flake8] Error 1
13:16:52  make[3]: *** Waiting for unfinished jobs....
```
Solution:
Fix the above style errors reported by flake8
> Problem: hare main branch fails to build

- hax/hax/hax.py
- hax/hax/log.py
- hax/hax/motr/delivery.py
- hax/hax/util.py
- hax/test/test_delivery_herald.py
Solution:
1. Remove obviously redundant logging in `@repeat_if_fails` decorator
2. Add custom TRACE verbosity level and use it in DeliveryHerald (since the logs make sense but probably in tests only)
Closes #1420
> Problem: hax generates redundant DEBUG logs

- .github/stale.yml
Stale bot configuration is removed as  'Stale' bot spams with notifications. However this causes auto closing of issues. Please refer - https://github.com/Seagate/cortx-hare/issues/1325
To fix this added stale bot configuration again with 6 days before sending notification.
> Problem: No configuration present for stale bot. Hence bot is auto-closing issues as default behavior

- Makefile
EOS-15919 Make distclean doesn't delete all files.
Solution: Added code in Makefile to delete leftover files, which
are created at the time of make and which should be deleted at
make distclean.
Test steps:
1. executed - make
2. executed - make distclean
Relevant output :
--> Cleaning hax
removing hax/build
removing hax/dist
removing hax/hax.egg-info
removing hax/libhax.cpython-36m-x86_64-linux-gnu.so
removing hax/hax/__pycache__
removing hax/hax/motr/__pycache__ dir
removing hax/hax/queue/__pycache__ dir
removing hax/test/__pycache__ dir
3. executed - git clean -n -fdx
It returned nothing.
Signed-off-by: Shipra Gupta <shipra.gupta@seagate.com>
> EOS-15919 Make distclean does not delete all the untracked files.

- hax/requirements.txt
requests module from aiohttp has a dependency on a specific range of idna
package version which leads to the following make devinstall error,
```
Installed /root/cortx-hare/hax
Processing dependencies for hax==1.0.0
error: idna 3.1 is installed but idna<3,>=2.5 is required by {'requests'}
make: *** [/opt/seagate/cortx/hare/lib/python3.6/site-packages/hax.egg-link] Error 1
```
Solution:
Add idna version range to be installed to hax/requirements.txt
> Problem: make devinstall fails

- Jenkinsfile
Problem: Jenkinsfile uses user specific SSC VM and credentials.
Solution: Use DevOps Service account for Hare CI VM
> Use SSC VM from Generic Account instead of User specific VM.

- Makefile
- README.md
Problem:
m0crate command throwing error for the steps given in README.md
Error : m0crate: command not found
Solution:
m0crate can be located in motr directory, so the m0crate utility
needs correct path while executing this command.
This only needs a documentation fix, which is done here.
> EOS-16201:Hare Run I/O test m0crate: command not found

- cfgen/tests/singlenode.dhall
Jira link: https://jts.seagate.com/browse/EOS-16393
Problem cause: test Dhall files were not aligned to changes in grammar
introduced by #1401 fix.
Here is the change in the grammar that was not addressed in
singlenode.dhall:
```diff
diff --git a/cfgen/dhall/types/ClusterDesc.dhall b/cfgen/dhall/types/ClusterDesc.dhall
index 9996de4..e5d1bbf 100644
--- a/cfgen/dhall/types/ClusterDesc.dhall
+++ b/cfgen/dhall/types/ClusterDesc.dhall
@@ -28,7 +28,7 @@ let Node =
{ hostname : Text
, data_iface : Text
, data_iface_type: Optional ./Protocol.dhall
-  , m0_servers : List M0Server
+  , m0_servers : Optional (List M0Server)
, m0_clients : { s3 : Natural, other : Natural }
}
```
Solution: wrap the list into Some in the test file.
> EOS-16393: make test fails due to a Dhall error

- utils/hare-status
Modified code to get list of devices and status.
Code will read entries from KV present in the below format "m0conf/nodes/<node_id>/processes/<process_fidk>/services/<svc_fid>/sdevs/<sdev_fid>"
> EOS-15799 Management: display cluster configuration

- utils/hare-shutdown
Modified code to take log level as argument through CLI
hctl shutdown needs to be called as 'hctl shutdown -v' to enable debug mode
Replaced messages printed by print() with logger functions.
Output of 'hctl status -v' after changes is as follows,
[root@ssc-vm-c-1822 hare]# hctl shutdown -v
Starting new HTTP connection (1): 127.0.0.1:8500
http://127.0.0.1:8500 "GET /v1/catalog/nodes HTTP/1.1" 200 220
http://127.0.0.1:8500 "GET /v1/health/node/ssc-vm-c-1822.colo.seagate.com HTTP/1.1" 200 313
http://127.0.0.1:8500 "GET /v1/kv/leader HTTP/1.1" 200 158
Started thread
Stopping m0d@0x7200000000000001:0xc (ios) at ssc-vm-c-1822.colo.seagate.com...
Stopped m0d@0x7200000000000001:0xc (ios) at ssc-vm-c-1822.colo.seagate.com
Exiting thread
Started thread
Stopping m0d@0x7200000000000001:0x9 (confd) …
> EOS 15932 No verbose mode present in hctl-shutdown

- hax/hax/filestats.py
- hax/hax/hax.py
- hax/hax/motr/__init__.py
- hax/hax/motr/rconfc.py
- hax/hax/util.py
Presently only one spiel command is being invoked as part of fileStatsUpdater thread
but spiel use cases increase, e.g. sns repair/rebalance, rconfc must be started
only once.
Solution:
Create a motr runnable that is started as part of motr start operation.
Start rconfc as part of motr thread but wait for motr services to start.
> Problem: hax starts rconfc in context of fileStatsUpdater

- utils/hare-status
Process type is a typing.NamedTuple which is converted to JSON with json
library incorrectly. This makes the part of "hctl status --json" payload already unparseable.
Here is how this subtree looks now:
```
"nodes": [
[
"localhost",
[
[
"hax",
"0x7200000000000001:0x6",
"192.168.6.214@tcp:12345:1:1",
"started"
],
[
"confd",
"0x7200000000000001:0x9",
"192.168.6.214@tcp:12345:2:1",
"started"
],
[
"ioservice",
"0x7200000000000001:0xc",
"192.168.6.214@tcp:12345:2:2",
"started"
],
[
"m0_client",
"0x7200000000000001:0x28",
"192.168.6.214@tcp:12345:4:1",
"unknown"
],
[
"m0_client",
"0x7200000000000001:0x2b",
"192.168.6.214@tcp:12345:4:2",
"unknown"
]
]
]
]
```
So under "nodes" there is a list which messes up node name (string) with Process details (erroneously shown as sub-lists).
Solution: use …
> Problem: "nodes" subtree in "hctl status --json" is broken

- cfgen/cfgen
- provisioning/hare_setup.py
- provisioning/miniprov/hare_mp/cdf.py
- provisioning/miniprov/hare_mp/dhall/gencdf.dhall
- provisioning/miniprov/hare_mp/types.py
- provisioning/miniprov/requirements.txt
- provisioning/setup.yaml
Mini provisioner CDF generator adds few default values for some of the
configuration keys. But hare cfgen utility that parses the generated
CDF does not allow some of the defined keys to have no values.
cfgen does not allow,
- meta-data devices to be None
- diskrefs must node be empty
- pool type cannot be null
- List of profiles must not be empty
- data_iface_type cannot be null
Solution:
- Fetch meta data devices from cortx-py-utils:conf-store and
pass the values to Hare mini provisioner.
- Allowed diskrefs to be empty, but this needs to be fixed properly.
- Set default pool type to be sns.
- Set default non-empty list of profiles.
- Passed tcp as a default network interface type to mini provisioner.
- Add --filename option along with with config in setup.yaml
Signed-off-by: Mandar …
> Problem: cfgen fails to parse CDF generated by mini provisioner

- README.md
Solution:
Update hare README.md to include instructions to build hare rpm from source.
> Problem: Instructions to build hare rpm from source are missing

- Makefile
- provisioning/miniprov/Makefile
- provisioning/miniprov/requirements.txt
- provisioning/miniprov/setup.py
Mini Provisioner depends on ConfStore which is imported from
cortx.utils.
The problem is that Hare build pipeline runs in a separate virtual
environment (a.k.a. virtualenv). By default virtualenv doesn't inherit
system-wide packages from `/usr/lib/python3.6/site-packages`. It means
that even though cortx-py-utils RPM is installed, its Python packages
are not visible from Hare virtualenv.
1. Create virtualenv with `--system-site-packages` flag.
2. After that local requirements.txt must be processed with
`--ignore-installed` flag to force pip to overwrite the packages in the
local site-packages.
> Problem: No module named 'cortx' when running tests

- provisioning/miniprov/hare_mp/cdf.py
- provisioning/miniprov/test/test_cdf.py
Solution: use the partition name instead while generating CDF. At the
moment the value is not provided through ConfStore so the value is
hardocded with TODO comment.
> Problem: CDF file uses metadata device instead of volume

- provisioning/setup.yaml
Solution: use the format suggested by Mini Provisioner Specification;
`script:` must be replaced by `cmd:`.
cc @SwapnilGaonkar7
> Problem: setup.yaml uses 'script' instead of 'cmd'

- provisioning/miniprov/hare_mp/main.py
- provisioning/setup.yaml
hare_setup utility by default tries to install logrotate configuration which
requires provisioner cli to be installed. It is possible that on some dev setups
provisioner is not installed, in which case hare_setup throws an error that may
mislead user to assume that hare_setup command itself failed.
Also it is not required logrotate to be configured in context of every command
execution.
Solution:
Provide an explicit option to hare_setup utility to configure hare logrotate
values.
> Problem: logrotate configuration is not optional

- provisioning/miniprov/hare_mp/cdf.py
- provisioning/miniprov/hare_mp/dhall/gencdf.dhall
- provisioning/miniprov/hare_mp/types.py
- provisioning/miniprov/test/test_cdf.py
JIRA: https://jts.seagate.com/browse/EOS-17250
Solution:
1. take the number of s3 servers from `cluster>{node-name}>s3_instances` value.
2. update failing unit tests.
Resolves one of the items specified in #1477
> Problem: Number of s3 servers is not taken from ConfStore

- hax/hax/handler.py
- hax/hax/hax.py
- hax/hax/motr/__init__.py
- hax/hax/server.py
- hax/hax/types.py
- hax/hax/util.py
If a node is rebooted Consul does report a warning for the corresponding
service to hax but hax checks for node status which is 'passing' atleast
for few iterations, this delay in node status update leads to missing of
the Consul warning, Consul status for the process is not update in KV.
Consul KV for the process status still remains M0_CONF_HA_PROCESS_STARTED
which also causes node-join to fail.
While notifying service failure to peer motr processes it is also important
to handle delay in notification mainly in case of transient failure.
The process for which Consul reported failure might just be starting and
reporting a process failure when hax has already replied to the entrypoint
request leads to other inconsistencies with halink protocol.
Hax also does not send failure notifications …
> Problem: Hare doesn't handle node failure properly

- jenkins/prepare-yum-repos
Problem: The yum repos set in hare CI are old
Solution: Update the yum repos for motr and lustre in hare CI
Signed-off-by: Parikshit Dharmale <parikshit.dharmale@seagate.com>
> EOS-17643 Hare CI: Update the yum repos

- Jenkinsfile
hctl bootstrap and hctl shutdown are taking longer time
to execute causing jenkins timeout to trigger and aborting
the I/O test with m0crate.
Solution: Increase the jenkins timeout for I/O test with m0crate.
Signed-off-by: Parikshit Dharmale <parikshit.dharmale@seagate.com>
> Problem: Hare CI I/O test with m0crate is aborted

- hax/hax/util.py
- utils/hare-shutdown
- utils/utils.py
Problems:
1. SIGKILL doesn't stop hare-shutdown script properly. There is a chance that local consul will be killed and thus hare-shutdown will not work next time.
2. There is a chance that local consul will be stopped not the last. If an error occurs after that, hare-shutdown will not work next time.
> EOS-17407: hare-shutdown can leave the cluster in non-stoppable state

- provisioning/miniprov/Makefile
- provisioning/miniprov/hare_mp/main.py
Solution: Modified code to address errors generated by flake8 and mypy
Note: flake8 still reporting some error but they looks false positive
```
[root@ssc-vm-c-1823 hare]# flake8 provisioning/miniprov/hare_mp --show-source
provisioning/miniprov/hare_mp/cdf.py:17:33: E901 SyntaxError: invalid syntax
def __init__(self, provider: ValueProvider):
^
provisioning/miniprov/hare_mp/cdf.py:28:20: E701 multiple statements on one line (colon)
raw_content: bytes = pkg_resources.resource_string(
^
provisioning/miniprov/hare_mp/cdf.py:33:14: E701 multiple statements on one line (colon)
nodes: List[NodeDesc] = []
^
provisioning/miniprov/hare_mp/cdf.py:35:20: E701 multiple statements on one line (colon)
server_dict: Dict[str, str] = conf.get('cluster>server_nodes')
^ …
```
> Problem: hare_mp package doesn't pass flake8 and mypy checks

- hare.spec
Currently, the requirement allows only 1.7.8 version of Consul which is very strict. Hare is known to work fine with a much wider range of Consul versions.
Solution: fix the requirement to allow versions of Consul from 1.7.x to 1.9.x.
> hare.spec: fix consul version requirement

- hax/hax/hax.py
- hax/hax/motr/__init__.py
Hax fetches and saves RM fid when hax process starts. Hare elects an RC
leader from the given Consul server nodes which also run a motr
Confd process. Every confd runs a RM service, hax returns the fid of
motr RM service cooresponding to the confd running on the Hare RC leader
node. However, it is possible that the RC leader may change due existing RC
leader failure, in this case hax still returns the saved RM fid in response
to the new entrypoint requests from the motr processes. This may lead to
inconsistencies and failure of RM requests.
Solution:
Do not save the RM fid but fetch it while responding to the entrypoint
requests.
> Problem: hax returns invalid RM fid post RC leader re-election

- cfgen/cfgen
It seems like python is unable to build the proper message when assert
is triggered: an NPE happens while building the explanatory string.
Solution:
1. Add more asserts to catch the problem with missing (None) fields in
node_desc
2. Print more context so that the caller can understand the root cause.
Closes #1487
cc @andriytk
> Problem: cfgen doesn't show which node has the problem with IP config

- README.md
Signed-off-by: Patrick Hession <patrick.hession@seagate.com>
Problem: Motr build dependencies are not present in this Motr installation
Solution: Added command to build install dependencies
-----
[View rendered README.md](https://github.com/hessio/cortx-hare/blob/patch-3/README.md)
> Added build dependencies to Motr installation

- cfgen/cfgen
Currently, the assert msg looks like this:
File "/opt/seagate/cortx/hare/bin/../bin/cfgen", line 1094, in pool_drives
assert len(targets) == 1  # guaranteed by validate_pools_desc()
AssertionError
which gives no clue about what's wrong with the pool configuration.
Solution: print config line which fails the assertion.
> cfgen: improve assert msg at pool drives check

- provisioning/miniprov/hare_mp/cdf.py
Solution: dhall-t-yaml will be called after previous process execution completes
UT:
-bash-4.2$ sudo /opt/seagate/cortx/hare/bin/hare_setup --config 'json:///home/754021/EOS-17172/hare/provisioner_cluster1.json' --filename '/var/lib/hare/cluster3rr.yaml'
-bash-4.2$ sudo /opt/seagate/cortx/hare/bin/hare_setup --init
Cluster is not running
2021-02-23 21:40:24: Generating cluster configuration... OK
2021-02-23 21:40:25: Starting Consul server on this node........ OK
2021-02-23 21:40:30: Importing configuration into the KV store... OK
2021-02-23 21:40:30: Starting Consul on other nodes... OK
2021-02-23 21:40:31: Updating Consul configuraton from the KV store... OK
2021-02-23 21:40:31: Waiting for the RC Leader to get elected....... OK
2021-02-23 21:40:36: Starting Motr (phase1, mkfs)... OK …
> Problem: config command of mini-provisioning failing infrequently which is causing deployment failure

- hctl
- rfc/11/README.md
- utils/bootstrap-node
- utils/hare-shutdown
- utils/hare-start
- utils/hare-start-node
- utils/hare-utils
To provide hctl start --node interface which starts the services on a local node that is previously configured.
hare-start-node : This script starts all the services based on the already present configurations ( which were generated during bootstrap process).
> $ hctl start --node
2021-02-19 03:06:55: Starting Consul agent on this node.... OK
2021-02-19 03:07:02: Starting Motr (phase1, m0d)... OK
2021-02-19 03:07:16: Starting Motr (phase2, m0d)... OK
2021-02-19 03:07:19: Checking health of services... OK
OK
2. On 3 node cluster, node 1896 shutdown
> [root@ssc-vm-c-1899 ~]# hctl status
Data pool:
0x6f00000000000001:0x87 'the pool'
Profile:
0x7000000000000001:0xcf 'default': 'the pool' None None
Services:
ssc-vm-c-1896.colo.seagate.com
[unknown]  hax        0x7200000000000001:0x32 …
> EOS-17098: Provide hctl start --node interface

- provisioning/miniprov/hare_mp/main.py
- provisioning/setup.yaml
It turned out that setup.yaml file, --config option is mandatory for all commands otherwise provisioner code will fail.
Solution: Add --config option for all commands in hare setup.yaml
> Problem: mini provisioner doesn't work at stable

- hax/hax/hax.py
Problem:
All the pcs resources are not online within time limit.
Hence Unboxing process not successful. Confd's entrypoint request
was not replied in time and it timed out.
Solution:
Current queue length in hax is 8, because of which if the requests
overflow the queue, they may get dropped or not serviced due to
which motr process may end up timing out. So increasing the queue
length from 8 to 8192.
> EOS-18485:All services not online while unboxing after max attempts

- Makefile
JIRA: [EOS-18433](https://jts.seagate.com/browse/EOS-18433)
Problem causes:
1. In devinstall mode, the packages must not be installed to
/opt/seagate/cortx/hare (via `pip ... --prefix <folder>`). We must use
local virtualenv folder instead and create symlinks to executables only.
2. hare_setup is not installed during devinstall because of a mistype in
Makefile.
Solution: fix Makefile
> Problem: hare doesn't bootstrap in devinstall mode

- hax/hax/handler.py
- hax/hax/hax.py
- hax/hax/message.py
- hax/hax/motr/__init__.py
- hax/hax/motr/delivery.py
- hax/hax/motr/hax.c
- hax/hax/types.py
- hax/test/test_delivery_herald.py
As part of fix (a354d38) to EOS-14988, Hare implemented a protocol fix with respect to motr communication. The fix introduced a problem of blocking motr thread in hax, that lead to delay in processing of motr events posted internally by Hare.
The pulled in commits from main mainly fix 2 problems,
1. Unblock in coming motr thread in hax corresponding to the entrypoint request.
2. Fix the wrong tag used in the halink message delivered call back in hax motr land.
The patch with these commits reduces the overall starting time of motr processes thus resolving the issues that are seen during cluster start/stop, standby/unstandby and boxing/unboxing.
Hare team has tested this patch by running at least 7 iterations of boxing/unboxing.
> EOS-18485: Not all the services are online during unboxing after max attempts

- Makefile
Description: Package imports issue after running make install command. hare_setup was not able to locate hare_mp package and its relative modules
Solution: Makefile alterations. (Installing setup.py file from provisioning/miniprov in python virtual environment)
Signed-off-by: Suprit Shinde <suprit.shinde@seagate.com>
> EOS-18353: Hare Miniprovisioner package imports issue

- provisioning/miniprov/hare_mp/cdf.py
- provisioning/miniprov/hare_mp/dhall/gencdf.dhall
- provisioning/miniprov/hare_mp/types.py
- provisioning/miniprov/test/test_cdf.py
Solution: Reading values for pools and profiles from ConfStore
UT: Tested config, init, test sections for singlenode, execution is completes successful.
Sample CDF:
pools:
- allowed_failures: null
name: StorageSet-1
data_units: 1
parity_units: 0
disk_refs:
- path: /dev/sdc
node: ssc-vm-c-1822.colo.seagate.com
type: sns
profiles:
- pools:
- StorageSet-1
name: Profile_the_pool
nodes:
- m0_servers:
- io_disks:
data: []
meta_data: /dev/vg_metadata_srvnode-1/lv_raw_metadata
runs_confd: true
- io_disks:
data:
- /dev/sdc
meta_data: /dev/vg_metadata_srvnode-1/lv_raw_metadata
runs_confd: null
data_iface: eth1
hostname: ssc-vm-c-1822.colo.seagate.com
m0_clients:
other: 3
s3: 0
data_iface_type: tcp
Snippet from sample confstore file:
"cluster": {
"cluster_id": "92f444df-87cc-4137-b680-aab3b35d1695", …
> Problem: Hare mini provisioner sets default values for some keys in CDF

- provisioning/miniprov/hare_mp/cdf.py
- provisioning/miniprov/hare_mp/main.py
- provisioning/miniprov/hare_mp/store.py
- provisioning/miniprov/hare_mp/validator.py
- provisioning/miniprov/test/test_validator.py
- utils/utils.py
Component mini-provisioning section, e.g. post-install, config, init, etc,
are expected to be executed on every node in the cluster. Thus it is
component's responsibility to evaluate if the command must do anything or
nothing on that node.
Hare needs to evaluate if the mini-provisioner init and test section
executions must be a no-op on a given node or not.
Solution:
- Check if the node is the first node of the first storage set in the
cluster using information from the comf-store.
- Add a validator class to encapsulate common routines with respect to
validations.
- Add routines to ConfStoreProvider for frequently fetched conf-store keys.
> EOS-18645: evaluate execution of mini provisioner setup command

- utils/utils.py
Solution: reuse the approach from hare-bootstrap script - compare the
hostname with /var/lib/hare/node-name. If the file doesn't exist, then
fallback to older logic.
> EOS-18846: shutdown uses redundant ssh to local host

- utils/hare-shutdown
- utils/utils.py
Description: The **ERROR** message was logged onto the console due to a wrong exit code check. Re-initiating the killing of consul returned wrong exit code as consul is already being killed. And to ensure that in the end, all the processes containing "consul" as a pattern must be killed, we still have the "sudo pkill --exact -KILL consul &> /dev/null" command present.
Signed-off-by: SUPRIT SHINDE <suprit.shinde@seagate.com>
> EOS-18751: hctl shutdown reports ERROR on VM

- utils/utils.py
JIRA ticket: [EOS-18846](https://jts.seagate.com/browse/EOS-18846)
This PR cleans up the fix made in #1553 
The problem is that hare-shutdown script checks whether the cluster is running by using this code:
```python
def check_cluster():
if not utils.consul_is_active_at('localhost'):
if utils.pcs_consul_is_active_at('localhost'):
exit("Cluster is run by Pacemaker, try `pcs cluster stop --all'")
else:
exit('Cluster is not running')
```
The intention is that Consul should be running at the current node. The
problem is that 'localhost' node will not be used in multinode
configurations (and even singlenode configuration may refer the current
node by some other name).
Check BOTH criteria:
1. whether the given name matches /var/lib/hare/node-name
2. whether the given name looks like localhost …
> Problem: hare shutdown still requires password while shuting down

- utils/hare-shutdown
Solution: reuse the approach from hare-bootstrap script - compare the
hostname with /var/lib/hare/node-name. If the file doesn't exist, then
fallback to older logic.
This is a backport PR to cortx-1.0 branch.
Source PR: #1553
> EOS-18846: shutdown uses redundant ssh to local host (cortx-1.0)

- Makefile
- provisioning/miniprov/Makefile
- provisioning/miniprov/hare_mp/cdf.py
- provisioning/miniprov/hare_mp/main.py
- provisioning/setup.yaml
JIRA ticket: [EOS-18909](https://jts.seagate.com/browse/EOS-18909)
According to the updated mini provisioner requirements, `hare_setup prepare --config $URL` command must be supported by our component.
Solution:
1. Add prepare command to setup_hare (so that it is available through CLI, but effectively a no-op)
2. Update setup.yaml to reflect the new command
3. Fix flake8 issue in mini provisioner code.
> Problem: no 'prepare' command is available

- provisioning/miniprov/hare_mp/types.py
hare_mp/types.py:123:5: E301 expected 1 blank line, found 0
make[2]: *** [flake8] Error 1
make[1]: *** [check-miniprov] Error 2
make: *** [build] Error 2
Solution:
Add a blank line to make flake8 happy.
> Problem: Hare mini provisioner build fails

- provisioning/miniprov/hare_mp/templates/hare.config.conf.tmpl.3-node.sample
- provisioning/miniprov/hare_mp/templates/hare.init.conf.tmpl.1-node
- provisioning/miniprov/hare_mp/templates/hare.init.conf.tmpl.3-node
- provisioning/miniprov/hare_mp/templates/hare.init.conf.tmpl.3-node.sample
- provisioning/miniprov/hare_mp/templates/hare.test.conf.tmpl.1-node
- provisioning/miniprov/hare_mp/templates/hare.test.conf.tmpl.3-node
- provisioning/miniprov/hare_mp/templates/hare.test.conf.tmpl.3-node.sample
Because of newly added validation checks in init and test sections of Hare mini
provisioner, some conf-store keys are required in init and test sections too.
Present templates for init and test sections do not contain any keys with respect
to this.
Solution:
- Update init and test section conf-store templates.
- Add more nodes information in 3 node config section template.
- Add populated sample conf-store files for config, init and test sections.
> Problem: init and test mini provisioning phases fail

- hax/hax/handler.py
- hax/hax/motr/__init__.py
- hax/hax/types.py
- hax/hax/util.py
The given crash occurs during dix setup of a motr io service when Hare
marks the data devices corresponding to an ioservice as failed. The crash
is mainly seen during mkfs. Hare starts a Consul watcher per io service,
which also monitors the motr-mkfs service (because both of them use the
same FIDs). Consul watcher keeps sending warning notifications for the
motr service until it is activating or when it is in inactive state.
In the former case (while ioservice is activating) Hare needs to handle
a race condition when Consul notifies a warning but Hare has already replied
to the entrpoint request, in such a scenario hare cannot notify the process
failure while it is actually starting as it leads to inconsistencies in halink
protocol. Along with this a case where motr-mkfs has stopped but …
> EOS-18434: mkfs panic: (!pver->pv_is_dirty) at m0_cs_dix_setup()

- Makefile
Solution : The list of python scripts in utils/ is a kind of hard-coded in Makefile. So once somebody adds a script, the script will most probably be forgotten and not added to PYTHON_SCRIPTS in the makefile. This is error-prone.
So we try to make Makefile to fetch the filenames automatically or make that list of scripts be a kind of dynamic.
Signed-off-by: Supriya Chavan <supriya.s.chavan@seagate.com>
> EOS-19092 Problem : Makefile doesn't run linters against some of utils/hare-* scripts

- provisioning/miniprov/hare_mp/main.py
- provisioning/miniprov/hare_mp/store.py
jira ticket- https://jts.seagate.com/browse/EOS-18936
In order to hctl fetch-fids be working on all the nodes of the cluster, consul-kv.json must be present on every node in the cluster. Presently cfgen is invoked in the init phase of the hare mini provisioner which generates consul-kv.json.
**Note:** File : `utils/hare-fetch-fids ` had some linter warnings regarding formatting. **No code changes done.**
1. Invoking cfgen in config phase of hare mini provisioner.
2. hctl fetch-fids works on every node of the cluster post config phase execution of hare mini provisioner.
```
$ hctl fetch-fids -n ssc-vm-c-1813.colo.seagate.com
[
{
"name": "confd",
"fid": "0x7200000000000001:0x9"
},
{
"name": "ioservice",
"fid": "0x7200000000000001:0xc"
}
]
```
(Issue observed while running `hctl fetch-fids`, …
> EOS-18936: Provisioning: invoke cfgen in config phase of hare mini provisioner

- provisioning/miniprov/hare_mp/main.py
Solution: Modified code to use --mkfs only during init stage.
> EOS-19410 Problem: 'Test' stage of mini-provisioner should run without '--mkfs' option

- hax/hax/handler.py
This was fixed by https://github.com/Seagate/cortx-hare/pull/1400, but a recent patch for https://jts.seagate.com/browse/EOS-18434 seems to have re-introduced the issue. Presently when a Motr process notifies M0_CONF_HA_PROCESS_STARTING or M0_CONF_HA_PROCESS_STARTED, hax broadcasts M0_NC_ONLINE and when Motr process notifiy M0_CONF_HA_PROCESS_STOPPING and M0_CONF_HA_PROCESS_STOPPED, hax broadcasts M0_NC_FAILED for that process as part of halink protocol. The correponding status is also updated in the Consul.
But when say motr process is stopping and hax broadcasts M0_NC_FAILED to motr processes and to itself, the halink is disconnected and rconfc from motr process may request entrypoint again. This may lead to such a panic which means that hax as already decided that the motr process has …
> EOS-19409: motr-mkfs fails with Motr panic: !rep->hae_disconnected_previously

- README.md
Signed-off-by: Patrick Hession <patrick.hession@seagate.com>
- HARE team need to maintain Motr installation steps
- `make devinstall` causes issues with HARE as mentioned in [issue 1544](https://github.com/Seagate/cortx-hare/issues/1544)
- It is not clear that rpm generation and build from source are not both required.
- Linked Motr installation to Motr Quick Start Guide instead of these steps being maintained twice.
- Changed HARE from `make devinstall` to `make install` 
- Made clear that you only need either build from source or rpm generation, not both
- @hessio using VMWare Workstation Pro 16.
-----
[View rendered README.md](https://github.com/hessio/cortx-hare/blob/patch-4/README.md)
> Clearing up that you build source OR rpm

- Makefile
This is main -> stable backporting PR.
Contains the fix for broken devinstall (https://jts.seagate.com/browse/EOS-18433) and a regression fix (https://jts.seagate.com/browse/EOS-18559)
For more details please see the source PRs:
* #1524
* #1534
> Problem: hare doesn't bootstrap in devinstall mode (stable branch)

- hax/hax/util.py
consul_util.get_conf_obj_status() requires `@repeat_if_fail` decorator.
Otherwise, in case of some intermittent Consul issue, no reply will be
sent.
```
hax/hax/motr/__init__.py
279-    @log_exception
280-    def ha_nvec_get_reply(self, event: HaNvecGetEvent) -> None:
281-        LOG.debug('Preparing the reply for HaNvecGetEvent (nvec size = %s)',
282-                  len(event.nvec))
283-        notes: List[HaNoteStruct] = []
284-        for n in event.nvec:
285-            n.note.no_state = HaNoteStruct.M0_NC_ONLINE
286-            if (n.obj_t in (ObjT.PROCESS.name, ObjT.SERVICE.name)
287:                    and self.consul_util.get_conf_obj_status(
288-                        ObjT[n.obj_t], n.note.no_id.f_key) != 'passing'):
289-                n.note.no_state = …
```
> Problem: NvecGet may get no reply in case of Consul issue

- jenkins/prepare-yum-repos
Solution: Add motr_upload repo for dependency package installation
Hare CI is failing to install cortx-motr package as now this requires installation of dependency package named isa-l.
This package is available in motr_upload of third-party-deps repo. 
Adding motr_upload repo path in yum for motr package dependency installation.
Signed-off-by: Parikshit Dharmale <parikshit.dharmale@seagate.com>
> Problem: Hare CI: cortx-motr installation fails

- provisioning/miniprov/hare_mp/templates/hare.config.conf.tmpl.3-node
- provisioning/miniprov/hare_mp/templates/hare.init.conf.tmpl.3-node
- provisioning/miniprov/hare_mp/templates/hare.test.conf.tmpl.3-node
Private data interface names for node 1 in the 3-node conf store template files
are not the same as for other nodes.
Solution:
Match the private data interface variable name for node 1 with other nodes.
> Problem: private data interface template variable names mismatch

- rfc/README.md
Need to create design document RFC, for generation of layout parameters
for auxiliary (AUX) pools, during multipools cluster bootstrap.
This PR is used to update the RFC indexes only.
Detailed document is published at confluence at link :
https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/184746420/23+MPAUX+Multipool+Auxiliary+Layout+Parameters+Generation
It addresses the comments from PR:
https://github.com/Seagate/cortx-hare/pull/1585/
-----
[View rendered rfc/README.md](https://github.com/suvratjoshi/cortx-hare/blob/new_e19399/rfc/README.md)
> EOS-19399: Create design RFC for AUX multipools layout generation

- provisioning/miniprov/hare_mp/main.py
- provisioning/setup.yaml
hare_setup support bundle invokes `hctl reportbug`, as per the `setup.yaml`
example mentioned at https://seagate-systems.atlassian.net/wiki/spaces/PRIVATECOR/pages/94470861/Config+upgrade+section+in+setup.yaml,
support bundle command need not expect a configuration URL as a parameter.
Solution:
Don't add an argument to hare_setup support bundle command.
> Problem: Support bundle hare_setup command expects conf-store URL

- provisioning/miniprov/hare_mp/main.py
- rfc/20/README.md
Positional arguments to accept bundle-id and destination directory path are
available for `hctl reportbug` command but are missing from `hare_setup`
command.
Solution:
Add positional arguments to accept `bundle-id` and destination dir to hare-setup
interface and pass them to `hctl reportbug` command.
> EOS-19522: bundle-id and dest-dir arguments are missing from hare_setup

- utils/hare-start
JIRA issue: [EOS-19637](https://jts.seagate.com/browse/EOS-19637)
Due to a mistake in bash script the script always thinks that it is
invoked with `--node` flag.
The problem is that in bash there is no boolean types so node=true and
node=false are understood in the same way (as a string with non-zero
length) - that turns out to be semantics of [[ ]] in bash.
Solution:
1. Don't evaulate true/false within double brackets.
> EOS-19637: node-start never works cluster-wise

- README.md
README file instructs to download the RPMs using private Seagate URLs which are obviously unavailable to external users.
Solution: remove misleading instructions from README file
Closes  #1589
> Problem: README.md references RPM private Seagate repos

- utils/hare-bootstrap
Solution: Added two new functions named ssh_safe and conf_dir_check. one for generic ssh purpose that would also show on which node in cluster is problematic and confdir for checking write access to the peer nodes. 
Signed-off-by: SUPRIT SHINDE <suprit.shinde@seagate.com>
> EOS-18914: hctl bootstrap permissions error

- hctl
Solution: Sourcing py3venv and activating it.
1. 'Make devinstall' uses python ./setup.py develop. 
2. The "develop" mode doesn't create valid folders with pyc files in the venv. Instead, it creates .egg-link files. 
3. Those .egg-link files don't get considered even if PYTHONPATH is updated. But they are respected when virtual environment is activated.
Closes #1425 
Closes #1603
> EOS-18795 'hctl status doesn't work after make devinstall'

- utils/elect-rc-leader
- utils/get-service-health
- utils/hare-fetch-fids
- utils/hare-shutdown
- utils/utils.py
All the scripts under libexec/ can be invoked by short name only in
the context of hctl script. In non-hctl context, the scripts should use
absolute path instead:
- elect-rc-leader invokes node-name and it doesn't work in context of
hctl.
- get-service-health also invokes node-name; it can be invoked directly
by Consul so node-name should be addressed by absolute path.
- utils/utils.py contains redundant invocation of node-name (by short
name). That function is removed.
> EOS-20754: scripts under libexec/ are not runnable when invoked by short name

- hax/hax/types.py
- hax/hax/util.py
- provisioning/miniprov/Makefile
- provisioning/miniprov/hare_mp/main.py
- provisioning/miniprov/mypy.ini
'Reset' will delete entries from consul KV which are added by Hare
'Cleanup' will delete config(/var/lib/hare) and logs(/var/log/hare)
> EOS-18907: Implement "reset" and "cleanup" phase for Hare mini-provisioner

- provisioning/miniprov/hare_mp/main.py
- provisioning/mypy.ini
After hare bootstrap, it is observed that some services although
reported started by systemd take some time to initialize and thus
start. If the cluster is shutdown before the services are started
during hare_setup init, it may leave the cluster in some
inconsistent state. Which may cause some issues during shutdown or
startup at later point of time by HA.
Presently hare_setup init and test functions only check `hctl status`
and thus systemd output and not the processes state in Consul KV.
Solution:
Check Consul KV status and wait until all the processes are transitioned
to `M0_CONF_HA_PROCESS_STARTED`.
> EOS-21028: hare_setup init and test stop cluster too soon

- cfgen/cfgen
Issue :
The bug was reported by Jenkins deployment failure and also was
seen locally a couple of times. The run_command() function from
cfgen file gets timed out (15 sec) rarely. This mostly happens
because of sluggish VMs or network issues.
Resolution :
To fix this issue a decorator is created which keeps on retrying
the wrapped function after each timeout. This way, user will keep
getting indication upon each timeout and also retries will be made
till the wrapped function call is successful.
> EOS-20779: 1N VM-Deployment Failed in hare for the build Main#1178

- hax/requirements.txt
Problem reason:
1. Hare doesn't specify explicit mypy version in its requirements
2. So once newer mypy version is released, it is applied automatically
if .py3venv/ folder doesn't exist (yet)
3. It turns out that mypy 0.901 stops bringing type stubs for libraries
by default. Corresponding type stubs should be installed explicitly.
Solution: add missing type-* libraries to the build requirements.
Note: these depedendencies are build-time only. Runtime dependencies are
not affected.
> Problem: newer mypy fails on Hare sources

- utils/get-process-state
JIRA issue: [EOS-21102](https://jts.seagate.com/browse/EOS-21102)
Problem: when hare-bootstrap script awaits for m0d processes to start,
it looks into Consul KV. The corresponding key looks as follows: `$HOSTNAME/processes/$fid`
In singlenode deployments $HOSTNAME is resolved to FQDN while in Consul
KV the corresponding node is known as 'localhost'.
As long as utils/get-process-state queries non-existent key, the output
is empty string (instead of desired 'M0_CONF_HA_PROCESS_STARTED').
Solution: use node-name script instead of $HOSTNAME variable.
> EOS-21102: Singlenode deployment will never succeed

- provisioning/miniprov/hare_mp/main.py
In 'reset' phase of hare we are cleaning up the data generated. We are deleting consul KV entries generated by Hare.
But before that we need to stop Hare services as they might keep generating more data.
We are calling 'hctl shutdown' to stop services if cluster is running
> EOS-21119 Hare mini-provisioner reset phase does not shutdown the cluster

- hax/hax/handler.py
- hax/hax/motr/__init__.py
- hax/hax/util.py
Jira - [EOS-19656](https://jts.seagate.com/browse/EOS-19656)
On server node failure notification, Hare needs to report M0_NC_FAILED for the corresponding motr configuration objects, viz: node, enclosure (post EOS-17599), controller, and drives to all the Motr processes including s3servers.
In `broadcast_ha_states()`, added a check for process failures.
- fetch node from the failed process fid
- fetch fids of all configuration objects
fetch node fid
fetch enclosure fid
fetch controller fid
- append all states (fid: status) to HaNoteStruct notes
which is further notified to motr processes.
**Note**:  **how to be sure that process failure is due to node failure?**
We don't need to. Logically node failure and process failure will have the same effect. 
If the node fails devices are not …
> EOS-19656: Notify M0_NC_FAILED for motr configuration objects on server node failure

- hax/hax/motr/delivery.py
- hax/test/test_delivery_herald.py
JIRA issue: [EOS-20970](https://jts.seagate.com/browse/EOS-20970)
Solution:
1. Introduce unsorted_deliveries where all unawaited (yet) notifications are put.
1. Whenever wait_for_{all,any} method is invoked, corresponding messages go from unsorted_deliveries to recently_delivered. At the seame time unsorted ones that have been put more than 10 seconds ago get removed.
So effectively unsorted_deliveries size gets reduced whenever wait_for_{all,any} happens.
> DeliveryHerald memory leak: unawaited notifications never deleted

- hax/hax/handler.py
- hax/hax/hax.py
- hax/hax/message.py
- hax/hax/motr/__init__.py
- hax/hax/motr/planner.py
- hax/hax/motr/util.py
- hax/hax/queue/__init__.py
- hax/hax/server.py
- hax/hax/types.py
- hax/test/test_work_planner.py
Jira ticket: [EOS-19373](https://jts.seagate.com/browse/EOS-19373) 
Currently we have only one Motr-aware thread (ConsumerThread) that reads out `queue.Queue`, gets BaseMessage from it and interacts with Motr layer accordingly. In bigger installations one thread simply doesn't manage to process the flow of the messages fast (so that entrypoint requests can start delaying which is critical for Motr API).
As a solution. we want to add more consumer threads. There is one problem though: we can't blindly process the ordered messages in parallel to each other, sometimes the order matters. This patch proposes splitting the whole stream of such messages into continous partitions (or groups). Messages within the same partition can be handled in parallel without an issue. If a message belongs to …
> EOS-19373 Parallel message processing in Hax

- hare.spec
JIRA issue: [EOS-15353](https://jts.seagate.com/browse/EOS-15353)
Currently the hare.spec file doesn't specify explicit version for facter
tool. It turns out that older facter versions didn't handle labeled
network interfaces well.
Solution: set explicit requirement >= 3.14.8 in the specfile.
> EOS-15353: Specfile allows invalid facter version

- provisioning/miniprov/hare_mp/main.py
- provisioning/setup.yaml
Implement hare_setup upgrade command.
Currently it is set as no-operation as nothing is expected to be done.
Basic API provision is done.
> EOS-17954 : Implement "hare_setup upgrade" CLI

- provisioning/miniprov/hare_mp/cdf.py
If Consul cluster is deployed separately, Hare needs to know the locations
of consul server nodes in order to decide if motr confd must be started on that
node or not.
Solution:
- Add `consul_server` as one of the roles to `server_node>{machine-id}>roles`
in conf-store corresponding to the node that runs a consul agent in server mode.
e.g.
```
"server_node": {
"1114a50a6bf6f9c93ebd3c49d07d3fd4": {
"cluster_id": "my-cluster",
"hostname": "ssc-vm-1623.colo.seagate.com",
"roles": [
"primary",
"openldap_server",
"consul_server"
],
"name": "srvnode-1",
"network": {
"data": {
"interface_type": "tcp",
"private_interfaces": [
"eth0"
]
}
},
"s3_instances": "2",
```
- Fetch roles from `server_node>{machine-id}>roles` and check for `consul_server`
as one of the roles before configuring that node to …
> EOS-19727: Map confd locations to consul servers

- hax/hax/util.py
When Consul reports a warning for a motr process to Hax, Hax checks the current
status of the given motr process and reports the status accordingly.
If the current status of the given Motr process evaluates to FAILED, Hax reports
FAILED for its corresponding devices (including CAS device) as well.
If this happens during bootstrap (specifically during mkfs as processes start and
stop), then CAS transaction fails due to lack of availability of a clean pool version
as Hax has reported FAILED for some of the devices in the pool version.
Solution:
- No need to report FAILED if Consul warning is received when process is
STOPPING, instead report STOPPED for remote process and OFFLINE for local
Motr process, because local hax establishes connections with only local
Motr processes, so we don't …
> EOS-21337: Motr panic: (!pver->pv_is_dirty) at m0_cs_dix_setup() motr /setup_dix.c:347

- hax/requirements.txt
- hax/setup.py
JIRA ticket: [EOS-21355](https://jts.seagate.com/browse/EOS-21355)
In Hare sources there is no specific requirement on mypy version. It
seems like the newer version 0.901 stops bringing type information (so
called type stubs) for standard libraries; those type stubs should be
installed separately.
Solution: stick mypy to version 0.812 in cortx-1.0 to avoid more
surprises in a release branch.
> EOS-21355: newer mypy version fails at Hare sources (cortx-1.0)

- README.md
- hare.spec
There are two issues:
1. The Hare README file doesn't specify that cortx-py-utils is required
to build Hare nowadays.
2. hare.spec doesn't declare dependency on cortx-py-utils RPM.
1. Improve README
2. Add cortx-py-utils to both Requires and BuildRequires sections.
-----
[View rendered README.md](https://github.com/knekrasov/cortx-hare/blob/declare-py-utils-deps/README.md)
> Problem: cortx-py-utils dependency is not declared

- provisioning/miniprov/hare_mp/store.py
JIRA ticket: EOS-21976
It seems like ConfStore class should be used internally in
cortx-py-utils only; external code should use Conf 'wrapper' class
instead. Reason behind this change is that ConfStore signatures will
change soon and that change will be reflected automatically in Conf.
Solution: use 'wrapper' Conf class instead.
> EOS-21976: ConfStore must not be used

- README.md
Other than cortx-motr-test rpms installing other rpms without removing motr-test rpm
Signed-off-by: Vaibhav Paratwar <vaibhav.paratwar@seagate.com>
-----
[View rendered README.md](https://github.com/Seagate/cortx-hare/blob/vaibhavparatwar-patch-3/README.md)
> EOS-21437: HARE README GitHub Issue: #1664 - cortx-motr-tests rpm installation gives error

- hax/hax/handler.py
- hax/hax/motr/__init__.py
- hax/hax/util.py
jira link- https://jts.seagate.com/browse/EOS-18481
1. Initialization during bootstrap, after ios service, is online.
2. Device failure/online events
1. After bootstrap
```
$ hctl status -d
Data pool:
0x6f00000000000001:0x2f 'the pool'
Profile:
0x7000000000000001:0x4f 'default': 'the pool' None None
Services:
ssc-vm-c-1813.colo.seagate.com  (RC)
[started]  hax        0x7200000000000001:0x6   10.230.248.67@tcp:12345:1:1
[started]  confd      0x7200000000000001:0x9   10.230.248.67@tcp:12345:2:1
[started]  ioservice  0x7200000000000001:0xc   10.230.248.67@tcp:12345:2:2
[unknown]  m0_client  0x7200000000000001:0x29  10.230.248.67@tcp:12345:4:1
[unknown]  m0_client  0x7200000000000001:0x2c  10.230.248.67@tcp:12345:4:2
Devices:
ssc-vm-c-1813.colo.seagate.com
[online]  /dev/null
[online] …
```
> EOS-18481: Update device status in consul KV

- provisioning/miniprov/hare_mp/main.py
Solution : Redirect Hare deployment logs to '/var/log/seagate/hare/setup.log'
> EOS-21274 : setup.log file got created in /root instead of /var/log/seagate/hare

- provisioning/miniprov/hare_mp/cdf.py
- provisioning/miniprov/hare_mp/dhall/gencdf.dhall
- provisioning/miniprov/hare_mp/store.py
- provisioning/miniprov/hare_mp/templates/hare.config.conf.tmpl.3-node.sample
- provisioning/miniprov/hare_mp/types.py
- provisioning/miniprov/hare_mp/validator.py
- provisioning/miniprov/test/test_cdf.py
In CORTX, data is distributed over targets (devices) using layout. Layout is computed from input erasure coding configuration of N, K and S.
In CORTX, any component can fail and it can be mapped to following failure domains
- Node, Cylindrical Volume Group (CVG) and Disk (few more like Site and Rack).
As data is distributed  according to erasure coding configuration we can allow some number of failure for above domains(e.g. CVG)
Now we need to calculate this allowed failure vector based on erasure coding configuration, number of nodes and number of CVG per node and  populate this info in CDF so that it can be used by motr.
For exact formula used to calculate allowed failure vector refer to https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/127893680/CORTX+Durability+Configuration# …
> EOS-20675 Populate allowed_failures vector in CDF

- cfgen/cfgen
- cfgen/dhall/render/Root.dhall
- hax/hax/handler.py
- hax/hax/util.py
In case of multiple controllers per node, confd.xc, generated by cfgen does include
all the controllers per node as the children of the corresponding enclosure.
This leads to failure domain inconsistencies.
Solution:
- Assign all the controllers for a given node as the conrresopnding enclosure's
children.
> EOS-21289: Enclosure does not include all the controllers from the given node

- utils/hare-bootstrap
- utils/mk-consul-env
JIRA issue: [EOS-21354](https://jts.seagate.com/browse/EOS-21354)
In case when there are N nodes in Consul cluser, each Consul server
should have (N-1) IP addresses in retry-join list. Current
implementation adds not more than 1 retry-join address.
When a node reboots Consul agent needs to join back to the cluster.
Servers in retry-join list are the ones that will be used to connect
back to the cluster (or form it in case when Raft quorum used to be
lost). If retry-join contains one address only, that address becomes
single point of failure: once that node is down, other Consul agents
will not be able to reconnect to the cluster.
Modify bash scripts to allow multiple retry-join arguments.
> EOS-21354: Consul always has <=1 retry-join address

- provisioning/miniprov/hare_mp/cdf.py
- provisioning/miniprov/hare_mp/templates/hare.config.conf.tmpl.3-node.sample
- provisioning/miniprov/test/test_cdf.py
Problem :
The miniprovisioner CDF generator utility doesn't take devices
from both (all) the cvgs but just one (cvg[0]).
Solution :
All the devices present in all cvg are read now, using this PR.
> EOS-22129:Miniprovisioner cdf generator doesn't take devices from cvg[1]

- hax/hax/handler.py
With the addition of multiple Hax consumer threads, motr::stop()
was invoked from multiple threads which lead to multiple invocations
of rconfc_stop() during Hax shutdown. Motr rconfc might get finalised
in one of these calls. Thus a subsequent call to rconfc_stop would
fail due to already destroyed or invalid structure.
Solution:
- Allow only consumer thread 0 to invoke motr::stop() and finalise
rconfc.
> EOS-21420: motr rconfc_stop fails during hax shutdown

- provisioning/miniprov/hare_mp/main.py
- provisioning/miniprov/hare_mp/systemd.py
- provisioning/miniprov/hare_mp/validator.py
- provisioning/miniprov/test/test_cdf.py
- provisioning/miniprov/test/test_systemd.py
- provisioning/miniprov/test/test_validator.py
JIRA ticket: [EOS-21424](https://jts.seagate.com/browse/EOS-21424)
Solution: when deploying via mini provisioner, Hare must update hax'
systemd unit so that the following statements get commented out:
1. Requires=
2. After=
3. Restart=
> EOS-21424: Cortx-HA conflicts with hax systemd unit

- hax/hax/motr/__init__.py
rconfc_stop was invoked before completion of rconfc_start.
This is indicated by spiel_ready.
Invoke rconfc_stop if rconfc_start is complete.
Looped through 100+ iterations of hare_setup init stage. Panic didn't appear.
> ======================================================================================
start_count=130,
Thu Jul  8 03:56:46 MDT 2021
======================================================================================
panic_cnt_n1_after = 0
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
> EOS-21389: motr rconfc_stop fails due to spiel not ready

- hax/hax/handler.py
- hax/hax/types.py
- hax/hax/util.py
- rfc/4/README.md
Motr panic: (!pver->pv_is_dirty) is seen in motr-mkfs completion window,
where the Consul KV for motr process status is updated to STARTED for motr-mkfs
process and Consul reports warning for the same, this happens when motr-mkfs
start shuting down but has not reported STOPPING yet or due to delayed Consul
warning notification. Hare thinks that process crashed because Consul reported
a warning and process status remained started but not stopping or stopped.
Solution:
This needs to be handled by storing additional information and checking for
the process type (M0MKFS or M0D) along with process status.
Thus if the process status evaluates to FAILED based on Consul service status
and present process status in Consul KV but the process type is M0MKFS then
report STOPPED instead of FAILED so …
> EOS-22227: Hare reports device failures for motr m0mkfs process

- utils/hare-bootstrap
Problem: In our current code, we have timeout of 5 sec for consul start. But we have seen that sometimes consul takes more than 5 secs to start causing timeout and deployment failure. 
Solution: Changed logic for consul start check, removed timeout and added code for service failure check so we will keep checking until either consul is started or enters in failed state.
Tested bootstrap on 1 node and 3 node.
Tested on setup on which issue was seen.
> EOS-21919 Custom-build-1901: 3-node deployment fails at hare

- provisioning/miniprov/hare_mp/cdf.py
- provisioning/miniprov/hare_mp/types.py
- provisioning/miniprov/test/test_cdf.py
For 4+2+0,
`- allowed_failures:
disk: 2
ctrl: 2
encl: 1
rack: 0
site: 0`
For 4+2+2,
`- allowed_failures:
disk: 2
ctrl: 2
encl: 0
rack: 0
site: 0`
> EOS-22328 Modify formula for calculating allowed failure vector

- Makefile
- hax/hax/hax.py
- hax/hax/queue/offset.py
- hax/hax/queue/publish.py
- hax/hax/server.py
- hax/hax/types.py
- hax/hax/util.py
- hax/requirements.txt
- hax/setup.py
- hax/test/integration/__init__.py
- hax/test/integration/conftest.py
- hax/test/integration/pytest.ini
- hax/test/integration/test_motr.py
- hax/test/integration/test_server.py
- hax/test/integration/testutils.py
- hax/test/test_offset_storage.py
- provisioning/miniprov/hare_mp/main.py
Problem: critical parts of hax functionality are not covered by the automatic tests. Things like integration with Consul and communication to Motr land are very hard to test.
Solution:
1. Refactor hax code so that it is possible to implement integration tests that would mock or emulate Consul and Motr
2. Introduce pytest test framework
3. Implement several sample integration tests showing how Consul and Motr-related functionality can be tested.
4. Implement basic infrastructure for running such tests (e.g. integrate them into Makefile).
> EOS-21245 Improve hax testability

- hax/hax/motr/__init__.py
Devices are marked failed, when the corresponding ios service
fails. However, when the service comes back online, device states
remains failed as only explicit device events can mark device online.
Marking the device states to offline on process failure,
ensures that, on process coming back online, all the devices can be
updated from offline to online except failed ones.
> EOS-22106: Devices are marked offline on process failure

- cfgen/cfgen
The default allowed enclosure failures for dix/md pools is not populated which
may cause inconsistencies while wrting meta data further causing IO failures
in case of enclosure or node failures.
Solution:
Calculate and populate allowed enclosure failures for dix and md pools using
number of enclosures in the cluster.
> Problem: allowed enclosure faillures is not populated for dix/md pools

- Makefile
- provisioning/hare-logrotate
- provisioning/logrotate/hare
- provisioning/logrotate/physical
- provisioning/logrotate/virtual
- provisioning/miniprov/hare_mp/main.py
- utils/consul-watch-handler
- utils/elect-rc-leader
- utils/hare-reportbug
- utils/proto-rc
Solution :
Redirect logs to Hare support bundle '/var/log/seagate/hare'.
> EOS-15803 : Support: support bundle enhancements - Move /var/log/hare to /var/log/seagate/

- provisioning/miniprov/hare_mp/main.py
Cortx-ha does not manage hare-consul-agent.service being a 3rd party software.
Presently, by default, hare-consul-agent.service is disabled as part of cortx
deployment. In-order to support automatic restart in case of node restart and
because hare-consul-agent.service is not managed by cortx-ha, the systemd unit
needs to be enabled post hare deployment.
But a non cortx-ha deployments does not require hare-consul-agent.service to be
enabled and this will change post Hare starts using the default consul service
instead of hare-consul-agent.service as part of Hare-Consul separation.
Solution:
Enable hare-consul-agent.service post init phase of Hare deployment.
> EOS-20861: Hare consul services are disabled on freshly deployed VM

- hax/hax/handler.py
- hax/hax/motr/__init__.py
- hax/hax/types.py
- hax/hax/util.py
It is important to send actual device status to any motr process
(server/client) joining the cluster in reply to a nvec request.
Hax is replying drive and sdev status as M0_NC_ONLINE by default
instead of fetching the status from Consul KV.
This may lead to notifying the wrong device status to motr process
and cause further failures during IO.
Solution:
Fetch drive and sdev statuses from Consul KV to reply to the nvec
request.
> Problem: hax does not report the actual drive status in nvec reply

- provisioning/miniprov/hare_mp/main.py
- provisioning/setup.yaml
Solution:
The upgrade is used to support component specific upgrade (excluding 3rd software party upgrade which is handled by Provisioner).
So we can provide this feature for disruptive SW upgrade of components.
> EOS-20332: [Hare] SW Upgrade mini-provisioner: pre/post upgrade

- provisioning/miniprov/hare_mp/main.py
Help strings for pre/post upgrade modified. Currently it shows "upgrade" for both pre and post upgrades.
Signed-off-by: Vaibhav Paratwar <vaibhav.paratwar@seagate.com>
> EOS-23093 help strings for pre/post upgrade change

- cfgen/cfgen
JIRA issue: [EOS-15352](https://jts.seagate.com/browse/EOS-15352)
Solution: check the facter version programmatically at every node specified in the CDF file.
> EOS-15352: cfgen doesn't check facter version

- hax/hax/hax.py
- hax/hax/util.py
- stubs/consul/__init__.pyi
Jira issue: [EOS-22484](https://jts.seagate.com/browse/EOS-22484)
As long as Consul is not stopped anymore during hctl shutdown, Consul
Session may be kept alive even if Hare cluster is down. The Consul
Session mechanism is used for RC leader election. In the described
situation in newly started Hare cluster there is no Hax process which
can consider itself as running at RC leader. In particular, this means
that there is no Hax process that would keep updating FS statistics in Consul KV.
When Consul sessions are destructed?
1. When Consul cluster is restarted. It was the case before --skip-consul-stop flag was added.
2. When any the checks registered as a part of contract of this Session start failing.
In case of RC leader session the contract is the health state of confd and hax …
> EOS-22484: RC can't be re-elected after hctl shutdown

- provisioning/miniprov/hare_mp/templates/hare.config.conf.tmpl.1-node
Problem:
Miniprovisioner Jenkins job failing for missing keys cvg_count & storage_set_id parameter.
Failing job link:
http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Mini-Provisioning/job/CentOS-7.9.2009/job/Hare/5/console
Solution:
Added cvg_count and storage_set_id keys with TMPL values in the template file.
> EOS-23291: changes for Miniprovisioner failing for new key

- cfgen/cfgen
- cfgen/requirements.txt
- provisioning/miniprov/hare_mp/cdf.py
- provisioning/miniprov/hare_mp/main.py
- provisioning/miniprov/hare_mp/store.py
- provisioning/miniprov/hare_mp/templates/hare.config.conf.tmpl.1-node
- provisioning/miniprov/hare_mp/templates/hare.config.conf.tmpl.3-node.sample
- provisioning/miniprov/hare_mp/templates/hare.init.conf.tmpl.3-node
- provisioning/miniprov/test/test_cdf.py
- utils/hare-bootstrap
HA uses private FQDN to report node events, whereas hare is using
hostnames presently to generate configurations (CDF), which is subject
to change.
Update the configurations generated by Hare to use private FQDNs from
confstore.
Update functionality in scripts to use private FQDN.
Update unit tests and templates.
CDF file
```
$ cat /var/lib/hare/cluster2.yaml
pools:
- allowed_failures:
disk: 0
ctrl: 0
encl: 0
rack: 0
site: 0
spare_units: 0
name: storage-set-1__sns
data_units: 1
parity_units: 0
disk_refs:
- path: /dev/sdc
node: srvnode-1.data.private
type: sns
profiles:
- pools:
- storage-set-1__sns
name: Profile_the_pool
nodes:
- m0_servers:
- io_disks:
data:
- /dev/sdc
meta_data: /dev/vg_srvnode-1_md1/lv_raw_md1
runs_confd: false
- io_disks:
data: []
meta_data: null
runs_confd: true …
```
> EOS-22349: Replace hostname with Private FQDN in CDF

- provisioning/miniprov/hare_mp/cdf.py
- provisioning/miniprov/hare_mp/main.py
- provisioning/miniprov/hare_mp/store.py
- provisioning/miniprov/hare_mp/types.py
- provisioning/miniprov/test/test_cdf.py
<html>
<body>
prepare | Motr | server>name>cvg[0]>m0d[0]>md_seg1 | /dev/vg_srvnode-1_md1/lv_raw_md1 | string |  
prepare | Motr | server>name>cvg[0]>m0d[0]>md_journal | /dev/vg_srvnode-1_md1/lv_be_log | string |  
prepare | Motr | server>name>cvg[1]>m0d[0]>md_seg0 | /dev/vg_srvnode-1_md2/lv_md2_seg0 | string |  
<br class="Apple-interchange-newline">
</body>
</html>
The above keys are generated by Motr. Since, we cannot update the global confstore and the keys are specific to Motr-hare.
A shared confstore between hare-motr is required.
This confstore will be available after motr's prepare stage.
Note: Currently, the value for BE segment1 (path to metadata devices) is hard-coded.
Read BE segment1 using Motr-Hare confStore in config stage.
Update the cluster definition file.
Sample …
> EOS-19065: Use shared Motr-Hare confstore to populate BE segment1 in CDF

- provisioning/miniprov/hare_mp/cdf.py
- provisioning/miniprov/hare_mp/templates/hare.config.conf.tmpl.1-node
- provisioning/miniprov/hare_mp/templates/hare.config.conf.tmpl.3-node
- provisioning/miniprov/hare_mp/templates/hare.config.conf.tmpl.3-node.sample
- provisioning/miniprov/hare_mp/templates/hare.init.conf.tmpl.1-node
- provisioning/miniprov/hare_mp/templates/hare.init.conf.tmpl.3-node
- provisioning/miniprov/hare_mp/templates/hare.init.conf.tmpl.3-node.sample
- provisioning/miniprov/hare_mp/templates/hare.test.conf.tmpl.1-node
- provisioning/miniprov/hare_mp/templates/hare.test.conf.tmpl.3-node
- provisioning/miniprov/hare_mp/templates/hare.test.conf.tmpl.3-node.sample
- provisioning/miniprov/test/test_cdf.py
EOS-21210: Modify s3 key path according to changes in confstore
Solution :
Refer to Conf store KV `cortx>software>s3>service>instances` to populate number of
s3 client instances while generating CDF in hare mini-provisioner's `config` phase.
> EOS-21210: Modify s3 key path according to changes in confstore

- provisioning/miniprov/hare_mp/main.py
- provisioning/setup.yaml
Solution:
By default, cleanup will take you to post-factory(i.e. after post-install) and Pre-factory will take you to before-factory (i.e. undo everything that was done in post-install).
So we need to support this option in cleanup state.
In hare code post-install is no-op. So `--pre-factory` option is also no-op for us. 
We can use this command to cleanup with --pre-factory `/opt/seagate/cortx/hare/bin/hare_setup cleanup --config 'json:///root/hare.cleanup.conf.tmpl.1-node' --pre-factory`
> EOS-21138: Support '--pre-factory' option in Hare factory reset

- hax/hax/motr/__init__.py
- hax/hax/util.py
If a node is shutdown or rebooted in that case the corresponding node
processes are shutdown. In this case no drive failure events are sent
if the status of processes corresponding to the stopped node is
M0_CONF_HA_PROCESS_STOPPED in consul kv.
As the node's devices remain online, s3servers don't get any failure
notification which leads to dgread failures.
Solution:
Send OFFLINE notifications for the devices corresponding to the stopped
or restarted node.
Addresses: https://jts.seagate.com/browse/EOS-23165
> Problem: node drive failure events are sent on node restart

- cfgen/cfgen
If allowed_failures vector is not populated in CDF, cfgen calculates invalid
default allowed_failures vector with incorrect values for enclosure and
controllers.
Solution:
Check for empty allowed_failures vector from CDF and calculate the allowed_failures
vector based on the cluster configuration.
> Problem: Invalid allowed_failures vector values

- .prospector.yml
Codacy uses Python code analysis tool prospector which in turn uses Static analysis
tool, pep257 that checks the docstring style in Python code
is configured for Cortx repositories in github. This tool by default implements
rules D212 and D213 which conflict each other.
e.g.
```
"""Summary.
Documentation.
"""
leads to "Multi-line docstring summary should start at the second line pydocstyle(D213)".
"""
Summary.
Documentation.
"""
leads to "Multi-line docstring summary should start at the first line pydocstyle(D212)".
```
Same issue is reproduced at PR https://github.com/Seagate/cortx-hare/pull/1725
Solution:
As we don't want to disable tool pep257 entirely we can configure prospector by disabling
the specific rules, D212, from the tool using .prospector.yml.
Signed-off-by: Mandar Sawant …
> EOS-23252: Codacy blocking merge because of a dead lock condition

- cfgen/cfgen
The default tolerance vector generated for dix and md pools in case of
multiple ioservice per node causes tolerance check to fail for m0d
during bootstrap.
For example,
If #encls = 3, #ctrls = 3 (2 per encl/node), #sdevs = 2 per ctrl,
data_units = 4, parity_units = 2 and spare_units = 0. Thus pool width = 6.
Default DIX or MD layout parameters are, data_units = 1, parity_units = 2
and spare_units = 0.
In such a case the allowed failure vector presently generated for the DIX and
MD pool is, [0, 0, 2, 4, 2] ([S, R, E, C, D]), where number of controller failures
allowed are 4 which is more and 2 (K) tolerated failures.
Thus in this case it is possible that more than K units can be lost due to failure
of 4 controllers in a particualr combination across multiple nodes. Which cannot
be …
> Problem: bootstrap fails with multiple ioservices per node

- hax/hax/motr/__init__.py
- hax/hax/util.py
- hax/test/integration/test_motr.py
- hax/test/integration/testutils.py
**Problem**:
Node is now mapped to a motr enclosure and not a controller.
Presently while notifying controller failure, hax maps entire node to
a controller and not the failed motr process (ioservice).
**Solution**:
In case of IO service failure we are just marking controller
as failed and not marking whole node as failed(but if all the Io services
are failed then we will mark node as failed).
If we mark node as failed(because all IO services are failed) and then
if IO service comes back then we will mark node as online.
In case of node failure we are mapping all the controllers to node instead of just 1.
> EOS-23006 Map a motr process to a controller and not a node

- ha-simulator/README.md
- ha-simulator/docker-compose.yml
- ha-simulator/docker/Dockerfile
- ha-simulator/docker/etc/ha.conf
- ha-simulator/docker/etc/message_bus.conf
- ha-simulator/docker/patches/0001-Consul-hostname-altered-via-env-variable.patch
- ha-simulator/docker/requirements.txt
- ha-simulator/docker/run.sh
- ha-simulator/emitter.py
- ha-simulator/prepare-host.sh
- ha-simulator/run-containers.sh
- hax/hax/ha/__init__.py
- hax/hax/ha/events.py
- hax/hax/ha/handler/__init__.py
- hax/hax/ha/handler/node.py
- hax/hax/ha/thread.py
- hax/hax/hax.py
- hax/hax/motr/__init__.py
- hax/hax/util.py
- hax/mypy.ini
JIRA ticket: [EOS-15788](https://jts.seagate.com/browse/EOS-15788)
This PR adds integration with HA EventManager. By the result of this integration node state events ("offline", "online") will be received by hax and translated into Motr-specific broadcast messages.
Partial problems resolved by this PR:
1. No dev environment to debug against HA component. As a solution, the HA simulator is implemented (see `ha-simulator/` folder for more details). Hare developers don't need to deploy Kafka, Zookeeper, configure MessageBus etc to trigger HA events to happen.
2. The task itself leads to coupling with cortx-ha component (Reason: in order to receive HA events, Hare side needs to import cortx-ha types like EventManager, SubscribeEvent etc). The proposed solution identifies such issues and …
> EOS-15788: Node failure events handling

- .prospector.yml
- README.md
- hare.spec
Merging fresh main branch to fault_tolerance. 
Commits to be merged:
```
commit a9d179d068e51df41c6d3fb4289905ff1dbcad43 (HEAD -> main-to-fault_tolerance-0818, mein/main-to-fault_tolerance-0818)
Author: vaibhavparatwar <vaibhav.paratwar@seagate.com>
Date:   Wed Aug 4 10:09:35 2021 -0600
EOS-21367 : Facter rpm doesn't exist
Solution:
- We replace facter with puppet agent.
- Updated README with puppet-agent installation step.
Signed-off-by: vaibhavparatwar <vaibhav.paratwar@seagate.com>
commit fc5e04f76c5f871f1c813942036e6d5103cb1e73
Author: Mandar Sawant <mandar.sawant@seagate.com>
Date:   Tue Aug 10 13:57:06 2021 -0600
EOS-23252: Codacy blocking merge because of a dead lock condition
Codacy uses Python code analysis tool prospector which in turn uses Static analysis
tool pep257 that …
```
> Merge main to fault_tolerance 0818

- ha-simulator/docker-compose.yml
- ha-simulator/emitter.py
- ha-simulator/prepare-host.sh
- ha-simulator/run-containers.sh
- hax/hax/ha/handler/node.py
- hax/hax/ha/thread.py
- hax/hax/motr/__init__.py
- hax/hax/types.py
JIRA ticket: [EOS-15788](https://jts.seagate.com/browse/EOS-15788)
During the integration meeting it turned out that cortx-ha sends not only 'offline' and 'online' statuses but 'failed' also. Hare needs to handle this status as well.
> EOS-15788: Hare needs to subscribe to 'failed' node status as well

- hax/hax/ha/handler/node.py
- hax/test/test_types.py
Solution: implement a unit test that verifies that the conversions
between ServiceHealth and ha_note constants are correct (and as a side
effect - prove that Codacy error 'self.value is unsubscriptable' is
invalid).
Signed-off-by: Konstantin Nekrasov <konstantin.nekrasov@seagate.com>
> EOS-15788: No auto test for ServiceHealth<>ha_note present

- provisioning/miniprov/hare_mp/main.py
- provisioning/miniprov/hare_mp/templates/hare.reset.conf.tmpl.1-node
- provisioning/miniprov/hare_mp/templates/hare.reset.conf.tmpl.3-node
- provisioning/miniprov/test/test_templates.py
For motr reset, to restart the cluster, hare init needs to be called.
So Hare reset needs to call the 'Init' stage.
Solution:
Updated hare.reset.conf.tmpl.1-node and hare.reset.conf.tmpl.3-node.
Call 'Init' stage into Hare reset stage.
Addressed review comments on PR #1727 and removed /var/motr/hax , /etc/sysconfig/m0d-*
and /etc/sysconfig/s3server-* files in cleanup stage with pre-factory arguement.
> EOS-23169: Factory Reset - Call Hare init stage in Hare 'reset' stage

- cfgen/cfgen
- cfgen/examples/singlenode.yaml
- cfgen/tests/singlenode.dhall
- provisioning/miniprov/hare_mp/templates/hare.config.conf.tmpl.3-node.sample
- provisioning/miniprov/hare_mp/templates/hare.init.conf.tmpl.3-node.sample
- provisioning/miniprov/hare_mp/templates/hare.test.conf.tmpl.3-node.sample
This feature is developed considering the node (enclosure) failure
case. If a node in the cluster fails, it means that all the disks
in that node become inaccessible. As this feature considers only
node failures, it keeps the spare pools ready considering the
other alive nodes from the cluster.
The feature works using the mathematical combinations formula
C(n, r) = (n! / (r!(n-r)!))
It basically creates combinations of all the nodes in case of
failures of nodes from 1 to the allowed number of nodes to be
failed, by allowance vector.
For each and every such generated combinations of (alive) nodes,
it creates the sets of the disks and assigns a pool to each of
them. Such spare pools created considering allowed node failures
are called as aux pools.
This PR also covers …
> EOS-16272: cfgen to generate aux pool layouts considering node failures

- Makefile
- provisioning/support.yaml
A new Support Framework has been rolled out. This requires every component to have support.yaml
file, which will provide interfaces for it. This support.yaml should be present at location -
`/opt/seagate/cortx/hare/conf/support.yaml`
Solution:
Added support.yaml file at `/provisioning` location.
> EOS-22569: Integrate with new support bundle framework

- cfgen/cfgen
'aux_pool_list' function tries to access 'disk_refs' without checking if
it is present or not. cfgen do work without specifying 'disk_refs' in pool.
In above case we are considering all disks as part of pool.
Solution: Modified above mentioned function to list all the devices mentioned in CDF
file and use them if 'disk_refs' is not specified
> Problem: EOS-24186 S3 Mini Provisioner job is failing on main during bootstrap cluster

- hax/hax/motr/__init__.py
- hax/hax/util.py
- hax/test/integration/test_motr.py
- hax/test/integration/testutils.py
The fix for EOS-24124 was incomplete: broadcast to Motr layer still
happened even in case of MKFS stopped state (the condition was around
Consul KV update only).
Solution:
1. Exclude drive status broadcast when MKFS is not online
2. Implement an automatic test that validates this scenario
Signed-off-by: Konstantin Nekrasov <konstantin.nekrasov@seagate.com>
> EOS-24266: Drive states are still broadcast when MKFS is down

- hax/hax/motr/__init__.py
- hax/hax/types.py
- hax/hax/util.py
- hax/test/integration/test_motr.py
Presently on node failure/online, the corresponding process status
is updated but Enclosure, Node and controller status update is missed in
consul KV.
The states of node and enclosure are updated based on the node
failure/online event.
The controllers are updated based on the corresponding ios services
states.
HANote takes updated states from consul kv.
```
[root@ssc-vm-g2-rhev4-0399 test]# hctl status -d
Data pool:
0x6f00000000000001:0x39 'the pool'
Profile:
0x7000000000000001:0x60 'default': 'the pool' None None
Services:
localhost  (RC)
[started]  hax        0x7200000000000001:0x7   10.230.246.59@tcp:12345:1:1
[started]  confd      0x7200000000000001:0xa   10.230.246.59@tcp:12345:2:1
[started]  ioservice  0x7200000000000001:0xd   10.230.246.59@tcp:12345:2:2
[started]  ioservice …
```
> EOS-23005: Updating node, enclosure and controllers status in consul KV

- Makefile
- hare.spec
- hax/helper/__init__.py
- hax/helper/configure.py
- hax/helper/exec.py
- hax/setup.py
Solution: Implement `configure` script that repeats the way how
hare-bootstrap script generates the configuration files.
Signed-off-by: Konstantin Nekrasov <konstantin.nekrasov@seagate.com>
> EOS-24053: conf generation is impossible outside of hare-bootstrap

- cfgen/dhall/render/LibfabricNetId.dhall
Hare cfgen uses dhall configuration files to generate motr configuration,
confd.xc. Motr endpoint format changed from lnet to libfabric, which is
different than that used presently by dhall for Motr endpoint rendering.
Solution:
Use a Libfabric specific rendering dhall configuration file and update
the endpoint rendering accordingly.
> Problem: cfgen does not populate correct libfabric endpoints in confd.xc

- hax/helper/configure.py
- provisioning/miniprov/hare_mp/main.py
- utils/mk-consul-env
- utils/update-consul-conf
Hare mini provisioner config stage generate Hare and Motr configuration, which
also comprises of information to register Hare and Motr services with Consul.
This information is not populated by hare configure utility.
Solution:
- Accept configuration directory path as an argument to Hare scripts.
- Fetch required services information from offline key values generated as
part of Hare configuration.
> Problem: hare configure does not populate services information

- README.md
hctl bootstrap failed with Unsupported facter version found. 
Issue caused because facter is already installed by another application/Package with unsupported version.
Before installing puppet-agent, added steps to check and remove the unsupported facter binary, if already installed.
Closes #1779
> EOS-24507: bootstrap failed with RuntimeError Unsupported facter version found 2.4.1

- README.md
- Testing_Verification_History.md
Problem: Quick-Start-Guide(QSG) page missing with page verification info.
Solution: Added a Testing_Verification_History page and linked it to QSG page.
-----
[View rendered README.md](https://github.com/pavankrishnat/cortx-hare/blob/patch-2/README.md)
> EOS-24917: Update QSG with verification info

- utils/check-service
- utils/update-consul-conf
Hare watchers scripts that monitor Hare, Motr and S3 servers processes use
systemd interface to fetch their respective statuses. Systemd interface is
typically not used in the container environments and thus the watcher scripts
fail and report motr processes as offline even though they are started.
This leads to hax reporting invalid failure statues causing further inconsistencies.
Solution:
- Configure Hare check-script to send curl requests on the Hare, Motr and S3 server
ports to detect if the process is active or not.
- Use node name in hax http server url instead of hax endpoint.
> EOS-24972: Hare watcher scripts do not work in containers

- cfgen/cfgen
If there are pure client nodes (without m0_servers) in the
cluster configuration, the automatic disk_refs generation for
the pools fails:
2021-09-15 16:23:30: Generating cluster configuration...Traceback (most recent call last):
File "/opt/seagate/cortx/hare/bin/../bin/cfgen", line 2164, in <module>
main()
File "/opt/seagate/cortx/hare/bin/../bin/cfgen", line 223, in main
cluster = build_cluster(cluster_desc)
File "/opt/seagate/cortx/hare/bin/../bin/cfgen", line 2123, in build_cluster
for m0d in node['m0_servers']:
KeyError: 'm0_servers'
Solution: add explicit check for m0_servers section present
in the node configuration before including it in disk_refs
generation.
> cfgen: fix automatic pool disk_refs generation

- cfgen/cfgen
- cfgen/dhall/render/Root.dhall
- cfgen/dhall/types/Root.dhall
- cfgen/tests/sample-confd.dhall
We must take into account the services configured at the enclosures, when we use them to calculate the `parity_units` parameter for the pools: CAS-services for the dix-pool and IOS services for md-pool. Otherwise, we can get the wrong values when the services are not present on the nodes. (Like, for example, in case of the pure client-nodes present in the cluster configuration.)
The same principle must be applied in case of calculating the `tolerance` vector for the pools, as well as the `mdredundancy` parameter.
> cfgen: fix parity_units calc for dix and md pools

- utils/hare-fetch-fids
Currently hare fetch-fid do not support returning index based service fid.
Lets say there are 2 s3server present in node and component wants to know fid for service present at 0th index then following command can be used
"hctl fetch-fids --service=ioservice --index=0"
**[root@ssc-vm-5246 ~]# hctl fetch-fids --service=ioservice**
[
{
"name": "ioservice",
"fid": "0x7200000000000001:0xa"
},
{
"name": "ioservice",
"fid": "0x7200000000000001:0x15"
}
]
**[root@ssc-vm-5246 ~]# hctl fetch-fids --service=ioservice --index=1**
{
"name": "ioservice",
"fid": "0x7200000000000001:0x15"
}
**[root@ssc-vm-5246 ~]# hctl fetch-fids --service=ioservice --index=0**
{
"name": "ioservice",
"fid": "0x7200000000000001:0xa"
}
**[root@ssc-vm-5246 ~]# hctl fetch-fids --service=s3server --index=0**
{
"name": …
> EOS-25014 Add support for getting fid of services by index

- hax/hax/common/__init__.py
- hax/hax/hax.py
- hax/hax/server.py
- hax/hax/util.py
- hax/requirements.txt
- hax/test/integration/test_consul_util.py
- hax/test/integration/test_motr.py
- hax/test/integration/test_server.py
- hax/test/test_offset_storage.py
- provisioning/miniprov/hare_mp/main.py
- utils/hare-shutdown
- utils/hare-status
JIRA ticket: [EOS-24730](https://jts.seagate.com/browse/EOS-24730)
The existing retries mechanism (`@repeat_if_fails` decorator) will force
Consul-related operations to be retried forever even in case Consul
agent is not accessible and/or raft leader is not available. That will
become a problem when hax is no more controlled by systemd because hax
stop may be delayed forever in case of Consul connectivity problems.
Solution:
1. Introduce dependency injection (DI) mechanism
2. Add a global hax state object (used to store 'stopping' flag)
3. Make @repeat_if_fails decorator be aware of the global state object
(by means of DI) so that no retries happen if the application is going
to shutdown.
> EOS-24730: If Consul is down, hax will not exit

- cfgen/cfgen
- cfgen/dhall/render/FdmiFilter.dhall
- cfgen/dhall/render/Root.dhall
- cfgen/dhall/types.dhall
- cfgen/dhall/types/ClusterDesc.dhall
- cfgen/dhall/types/FdmiFilter.dhall
- cfgen/dhall/types/FdmiFilterDesc.dhall
- cfgen/examples/singlenode.yaml
- cfgen/tests/sample-confd.dhall
- cfgen/tests/singlenode.dhall
- hax/hax/types.py
- provisioning/miniprov/hare_mp/cdf.py
- provisioning/miniprov/hare_mp/dhall/gencdf.dhall
- provisioning/miniprov/hare_mp/types.py
- provisioning/miniprov/test/test_cdf.py
Solution: add the code to configure the filters in CDF.
To use FDMI the following needs to be configured in CDF:
- FDMI plugin endpoint which will consume FDMI records sent by FDMI
sources. Currently FDMI filter is one of Motr client processes;
- FDMI filters. `fdmi_filters` section defines filters and their FDMI
plugin endpoints.
`cfgen/cfgen --help-schema` explains format of the `fdmi_filters`
section in CDF:
```
#
fdmi_filters:  # This section is optional.  If it is missing, no fdmi filters
- name: <str>  # Human-readable name of the filter
node: <str>  # Hostname of the node that hosts FDMI plugin
client_index: <int>  # 0-based index of the client that would be
substrings: [ <str> ]  # List of strings for FDMI plugin to match
```
cfgen/examples/singlenode.yaml has an example of …
> EOS-21433 cfgen: add support for FDMI filters

- provisioning/miniprov/hare_mp/cdf.py
- provisioning/miniprov/hare_mp/utils.py
Hare mini provisioner generates cluster description file for a given
provisioner provided cluster description. A Motr container can have
multiple cvgs and thus start multiple ioservices per container. In
such a scenarios CDF generation is failing due to a bug where data
devices from more than 1 cvgs are not accounted.
Solution:
Account data devices from all the cvgs for a given motr ioservice.
> EOS-25106: cdf creation fails for multiple cvgs per container

- hax/hax/motr/hax.c
- hax/hax/motr/hax.h
Fix use after free panic at link_disconnected_cb() - the
rpc connection might be already freed by the time the callback
is called, so we cannot use it to figure out the endpoint
address. Here is the panic sample:
motr[29162]:  6700   WARN  [ha/halon/interface.c:537:halon_interface_link_disconnected_cb]  hl=0x7f5dfc55d690 ep=172.18.1.25@o2ib:12345:4:1
motr[29162]:  60c0  FATAL  [lib/assert.c:50:m0_panic]  panic: fatal signal delivered at unknown() (unknown:0)  [git: 2.0.0-307-11-gcacd425] /var/motr/hax/m0trace.29162
Motr panic: fatal signal delivered at unknown() unknown:0 (errno: 0) (last failed: none) [git: 2.0.0-307-11-gcacd425] pid: 29162  /var/motr/hax/m0trace.29162
Motr panic reason: signo: 11
/lib64/libmotr.so.2(m0_arch_backtrace+0x2f)[0x7f5e1404540f] …
> hax: fix panic at link_disconnected_cb()

- provisioning/miniprov/hare_mp/consul_starter.py
- provisioning/miniprov/hare_mp/hax_starter.py
- provisioning/miniprov/hare_mp/main.py
- provisioning/miniprov/hare_mp/utils.py
Presently without systemd, there is no other interface to start Hare hax service.
In-order to start hax process the corresponding environment and logging needs to
be configured explicitly in a non-systemd environment.
Solution:
- Add a sub command, start to hare_setup utility.
- Configure required environment, logging and start hax service in background
as part of hare_setup start command.
> Problem: no interface to start hax service without systemd

- provisioning/miniprov/hare_mp/hax_starter.py
- provisioning/miniprov/hare_mp/main.py
Hare need to upload configuration to consul in mini-provisioner prepare and
config stages respectively. Oblivious to consul cluster location a consul
client agent needs to be started locally to upload the relevant configuration
to Consul.
Solution:
Start and stop a Consul client agent in prepare and config stages to upload
the respective configuration to Consul.
> EOS-25123: Start consul client agent in prepare and config stage

- hax/setup.py
With the ARM64 Motr port, we are starting to check for
CONFIG_platform macro variable in the code, which is set at
Motr's config.h file. So we should explicitly include this file
via `-include'config.h'` gcc parameter from now on.
The change is compatible with the old Motr code.
See also https://github.com/Seagate/cortx-motr/pull/1086.
> hax: fix rpm build for ARM64 Motr port

- provisioning/miniprov/hare_mp/cdf.py
- provisioning/miniprov/hare_mp/consul_starter.py
- provisioning/miniprov/hare_mp/main.py
- provisioning/miniprov/hare_mp/utils.py
- systemd/consul-server-conf.json.in
- utils/elect-rc-leader
- utils/update-consul-conf
Modified code to to fetch paths for consul and hax from confstore
Also modified code to get consul endpoints from confstore
Destroying leader session after consul start
Copying 'consul-server-conf.json' to '{hare_local_dir}/consul/config'' directory
Updating elect-rc-leader watcher entry in consul-server-conf.json to take config-dir as input
> EOS-25125 Fetch local paths from confstore

- hax/hax/util.py
- provisioning/miniprov/hare_mp/consul_starter.py
- provisioning/miniprov/hare_mp/hax_starter.py
- provisioning/miniprov/hare_mp/main.py
Following changes in provisoner code causing provisioner to terminate in case
hare prints error or warning message.
Seagate/cortx-prvsnr#6209
So changing them to debug
> Privisioner exiting incase of warning or error message

- provisioning/miniprov/hare_mp/main.py
hare_setup start command checks if systemd is enabled and accordigly
decides to start hax and consul without or with systemd. But,
hare_setup does not start consul in case systemd is enabled in the
containers.
Solution:
Instead of checking systemd internally in hare_setup start command,
take an explicit option to specifiy if hare_setp start is being executed
in environment with or without systemd.
> Problem: systemd check in hare_setup start may not work

- hax/setup.py
Fix the change at commit c8363d2: the `-include config.h`
compiler option was specified wrongly in the python list
of parameters, which resulted in compilation error:
'config.h': No such file or directory
Solution: make `-include` and `config.h` a separate list
elements.
> fixup! hax: fix rpm build for ARM64 Motr port

- containers/examples/3node/config-vol-1-pvc.yaml
- containers/examples/3node/config-vol-1.yaml
- containers/examples/3node/config-vol-2-pvc.yaml
- containers/examples/3node/config-vol-2.yaml
- containers/examples/3node/config-vol-3-pvc.yaml
- containers/examples/3node/config-vol-3.yaml
- containers/examples/3node/cortx-io-pod-1.yaml
- containers/examples/3node/cortx-io-pod-2.yaml
- containers/examples/3node/cortx-io-pod-3.yaml
- containers/examples/3node/cortx-io-pod-svc-1.yaml
- containers/examples/3node/cortx-io-svc-1.yaml
- containers/examples/3node/cortx-io-svc-2.yaml
- containers/examples/3node/cortx-io-svc-3.yaml
- containers/examples/3node/hare.config.conf.3-node
- containers/examples/3node/hare.config.conf.n.cvgs.3-node
- containers/examples/3node/io-pv-1.yaml
- containers/examples/3node/io-pv-2.yaml
- containers/examples/3node/io-pv-3.yaml
- containers/examples/3node/io-pvc-1.yaml
- containers/examples/3node/io-pvc-2.yaml
- containers/examples/3node/io-pvc-3.yaml
- containers/examples/3node/motr_hare_keys.json
Presently there's no template(s) to support provisioning Hare container. This
inhibits testing Hare in containers.
Solution:
Add template/example files for creating persistent volumes, persistent volume claims,
creating multi-container pods, creating configuration pv and pvc, creating services
corresponding to the Hare-motr pods.
> EOS-23500: no template for hare container configuration is present

- hax/helper/configure.py
- utils/update-consul-conf
Presently Hare checks if motr confds are configured on a given
node or not. If yes then by default it configures the local Consul
agent as a server. This may not be correct if Consul server cluster
is started separately from Hare + Motr cluster.
Solution:
Add an explicit option to update-consul-conf to configure a local
Consul agent as a server or a client.
> Problem: hare by default configures Consul as a server

- hctl
hctl interface fails with error,
```
[root@cortx-io-pod-1 ~]# hctl fetch-fids
Failed to create stream fd: No such file or directory
```
if hctl is executed in non-systemd environment.
Solution:
- check if systemd is enabled implicitly in hctl and accordingly
set log re-direction to journald or not.
```
[root@cortx-io-pod-1 ~]# hctl fetch-fids
[
{
"name": "ioservice",
"fid": "0x7200000000000001:0xa"
},
{
"name": "ioservice",
"fid": "0x7200000000000001:0x17"
},
{
"name": "confd",
"fid": "0x7200000000000001:0x24"
}
]
[root@cortx-io-pod-1 ~]#
```
> Problem: hctl interfaces fails in non-systemd environment

- hax/helper/configure.py
- provisioning/miniprov/hare_mp/main.py
- provisioning/miniprov/hare_mp/utils.py
- utils/update-consul-conf
In provioner environment, currently UUID is being generated by
hare code before writing it into sysconfig files.
But according to motr requirement we should use 'machine_id' as UUID
As a solution :
Use machine_id as uuid, if specified as option
if not specified then generate it.
Also added code for copying confd.xc at $local/motr/sysconfig/<machine-id>/
For e.g. /etc/cortx/motr/sysconfig/<machine-id>/confd.xc
**Test**
Tested config method and sysconfig files are getting generated by using machine-id as UUID
Also tested bootstrap and in that case UUID is randomly generated
[root@ssc-vm-6327 hare]# /opt/seagate/cortx/hare/bin/hare_setup config --config yaml:///tmp/e24393/single_node_confstore.yaml
[root@ssc-vm-6327 hare]# cat …
> EOS-24408: Integration of Hare Mini provisioner - support to F-87A 

- Makefile
- hax/hax/motr/ffi.py
Add ARM64/AArch64 support:
1) `make rpm` works now on Arm64.
2) Fixed `libhax.cpython*.so` name for Arm64 at `HaxFFI::__init__`.
Testing: 1) rpm was built with `make rpm` and then installed successfully on the node; 2) singlenode cluster bootstrapped successfully:
```
$ hctl bootstrap --mkfs singlenode.yaml 
2021-10-30 13:14:43: Generating cluster configuration... OK
2021-10-30 13:15:25: Starting Consul server on this node..................................................................................... OK
2021-10-30 13:18:21: Importing configuration into the KV store... OK
2021-10-30 13:18:24: Starting Consul on other nodes...Consul ready on all nodes
2021-10-30 13:18:26: Updating Consul configuraton from the KV store... OK
2021-10-30 13:18:43: Waiting for the RC Leader to get …
```
> Add ARM64/AArch64 support

- hax/hax/util.py
- utils/hare-status
hctl status takes too much time in containers and also report inacurate statuses
for Motr and s3servers. hctl status looks at the health of consul service corresponding
to the Motr and s3server processes. Consul service status uses consul watcher which
probes the process endpoint. Thus a motr process can be running but not yet functional.
Solution:
Read Motr and s3server statuses saved in Consul KV that is updated when Motr process
reports the same. Thus is accurate from functionally readiness perspective of Motr
or s3server processes.
> EOS-25703: hctl status takes too much time to complete in containers

- README.md
- cfgen/cfgen
- hare.spec
On CentOS 8 the standard facter rpm version is 3.14,
which fits our needs. So the puppet-agent rpm (which
provided the needed version of facter-3.14 to us on
CentOS 7) is no longer required on CentOS 8.
-----
[View rendered README.md](https://github.com/andriytk/cortx-hare/blob/fix-facter-check-centos8/README.md)
> Fix facter version check on CentOS 8

- README.md
- cfgen/cfgen
- hare.spec
* Fix facter version check on CentOS 8
On CentOS 8 the standard facter version is 3.14,
which fits our needs. So the puppet-agent (which
provided the needed version of facter-3.14 to us
on CentOS 7) is not required anymore on CentOS 8.
(cherry picked from commit e10e5b396ed56abfe380d323047ba61b07ecb40d)
-----
[View rendered README.md](https://github.com/andriytk/cortx-hare/blob/sage-2.1/README.md)
> Fix facter version check on CentOS 8 (#1862)

- hare.spec
`make rpm` is failing on CentOS 8, solution:
1) `python36-*` packages are called `python3-*` in CentOS 8 - update in requirements.
2) Fix `h_motr_version` for motr requirement: it is taking the VERSION and RELEASE values from Hare instead of Motr. Fix by adding one more escape `%` symbol before VERSION and RELEASE.
> spec: fix make rpm on CentOS 8

- hare.spec
There is no need to check for CentOS 7 in defining `h_motr_version`: escaping `%` with one more `%` works fine in CentOS 7 as well.
> fixup! spec: fix make rpm on CentOS 8

- hare.spec
make rpm is failing on CentOS 8
Solution:
1) python36-* packages are called python3-* in CentOS 8:
update in requirements.
2) Fix h_motr_version for motr requirement: it is taking the
VERSION and RELEASE values from Hare instead of Motr.
Fix by adding one more escape % symbol before VERSION and
RELEASE.
(cherry picked from commit b5b6bec4f174b1cc86697c1187c8e977c504f0ee)
> spec: fix make rpm on CentOS 8 (#1861)

- Makefile
- hax/helper/ping.py
- hax/requirements.txt
- hax/setup.py
- stubs/tcpping/__init__.pyi
- utils/check-service
- utils/m0ping
In non-container environment with systemd enabled, hare uses systemd
interface to check if motr process is online or not. As systemd is not
enabled in container environment, hare uses a http probe to check if
motr process is online or not. This works but the respective curl command
may take more than 30s to complete in certain circumstances. This may
result in the consul watcher timeout which by default 30s.
```
[root@cortx-data-headless-svc-sm13-r2 /]# time curl cortx-data-headless-svc-sm13-r2:3001
curl: (56) Recv failure: Connection reset by peer
real    0m45.988s
user    0m0.007s
sys     0m0.006s
```
This may lead to timeout when consul watcher tries to check the status of
a motr service which may lead to a false failure notification,
```
{'Node': 'cortx-data-headless-svc-sm13-r2', …
```
> EOS-25727: motr process probe in hare check-service script may timeout

- hax/hax/motr/__init__.py
It is noted during testing that hax sometimes can report wrong quorum
value by calculating the active confds. This causes further
inconsistencies in motr processes startups.
This check in hax was added to avoid a hang situation during shutdown,
where hax's motr rconfc sends incessant entrypoint requests. Ideally,
reporting of confd failure must avoid this.
Solution:
Don't check for actve confds while sending entrypoint responses.
> Problem: hax reports wrong confd quorum value

- hax/hax/motr/__init__.py
- hax/hax/util.py
Solution:
1. Make sure that execution path of broadcast_ha_states reuses the same
kv_cache instance (to minimize repeated KV GET requests).
2. Refactor the KV-modifying functions so that actual kv_put()
operations can be postponed when possible (reason: kv_put() invalidates
the current kv_cache instance which may be an overkill if kv_put is
invoked too early).
> EOS-25863: BroadcastHAStates is slow at large clusters

- hax/hax/message.py
- hax/hax/motr/planner.py
- hax/test/test_work_planner.py
In fact, the delay is caused by the fact that when a large cluster is bootstrapping, there is a solid flow of BroadcastHAStates events.  According to the current design every broadcast will create a new partition in WorkPlanner which means that when the number of such commands is large, the execution of the commands becomes purely sequential.
1. introduce the notion of 'asap commands queue'. Such commands are executed regardless of the current group number in WorkPlanner.  ProcessEvent command becomes an 'ASAP' command (together with AnyEntrypointRequest and NvecGet).
2. Add ordering between ProcessEvent messages. ProcessEvent messages conflict if they contain the same fid. If a ProcessEvent message is being executed already, another conflicting ProcessEvent will not start processing …
> EOS-25863: ProcessEvents processed with a delay

- hax/hax/motr/__init__.py
- hax/hax/motr/hax.c
Hax crashed with the following panic,
```
2021-11-11 13:18:35,327 [DEBUG] {rconfc-starter} KVGET key=cortx-data-headless-svc-ssc-vm-g2-rhev4-1634/processes/0x7200000000000001:0x105, kwargs={}
motr[00637]:  9090   WARN  [ha/halon/interface.c:1119:m0_halon_interface_send]  hl=0x7f10540041a0 ep=inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-1963@2001 epoch=0 tag=7 type=2
motr[00637]:  8ed0  FATAL  [lib/assert.c:50:m0_panic]  panic: (m0_ha_lq_invariant(lq)) at m0_ha_lq_enqueue() (ha/lq.c:199)  [git: 2.0.0-527-34-g2fefe244] /etc/cortx/hare/config/c09a91306c824883a5586bc52e3b73c8/m0trace.637
Motr panic: (m0_ha_lq_invariant(lq)) at m0_ha_lq_enqueue() ha/lq.c:199 (errno: 11) (last failed: none) [git: 2.0.0-527-34-g2fefe244] pid: 637  /etc/cortx/hare/config/c09a91306c824883a5586bc52e3b73c8/m0trac …
```
> EOS-25916: hax uses halink while its disconnecting

- cfgen/Makefile
- cfgen/cfgen
- hax/hax/log.py
- hax/helper/configure.py
- hax/helper/exec.py
- provisioning/miniprov/hare_mp/main.py
Cfgen is an important part of cluster bootstrapping. Currently, if an error happens during bootstrap (especially when ran as a part of Mini Provisioner) debugging of such an issue is rather complicated.
1. Add verbose and non-verbose logging modes in cfgen
2. Add support of logging to a file (configured via CLI arguments)
3. Improve logging within cfgen
4. Replace `assert` statements with custom functions that can give more
information for debugging
> EOS-25247: Cfgen emits no logs

- .whitesource
Problem:
Whitesource scans are not enabled for cortx-hare repo.
Solution:
Adding .whitesource file to enable scans on cortx-hare repository
Whitesource scans looks for 3rd party libraries in the repositories.
It further identifies if any of the repositories are
vulnerable to known vulnerabilities.
If it finds out such known vulnerabilities in 3rd party libraries,
it reports the vulnerabilities on whitesource dashboard.
It doesn't interfere in any of the existing code.
This file is already tested on other repositories such as
cortx-s3server, cortx-motr etc.
So there is no impact of this change to existing functionality.
> EOS-26134 : Enable Whitesource scans

- hax/hax/message.py
- hax/test/integration/test_motr.py
- hax/test/integration/test_server.py
JIRA ticket: [EOS-25377](https://jts.seagate.com/browse/EOS-25377)
Dataclass StobIoqError turns out to be not serialized by `simplejson` library. The serializing is done as a normal workflow of STOB_IOQ_ERROR message propagation (so this dataclass gets serialized into JSON and that JSON is sent as a payload to EQ and then retransmitted to BQ from the RC leader node).
1. Implement custom serializer function for StobIoqError (for_json())
2. Implement integration tests that verify that the bug is not
reproduced anymore:
- StobIoqError is serializable by simplejson library
- Resulting payload is understood by the BQ processor
Closes #1830
> EOS-25377: StobIoqError type not JSON-serializable

- hare.spec
- hax/hax/filestats.py
- hax/hax/handler.py
- hax/hax/motr/__init__.py
- hax/hax/motr/ffi.py
- hax/hax/motr/hax.c
- hax/hax/motr/hax.h
- hax/hax/motr/rconfc.py
- hax/test/integration/testutils.py
The following panic is observed on CentOS 8 on startup:
hare-hax[270375]: 2021-11-08 16:04:42,950 [DEBUG] {MainThread} Loading library from path: /opt/seagate/cortx/hare/lib64/python3.6/site-packages/hax/motr/../../libhax.cpython-36m-x86_64-linux-gnu.so
hare-hax[270375]: 2021-11-08 16:04:43,061 [INFO] {qconsumer-0} Handler thread has started
hare-hax[270375]: 2021-11-08 16:04:43,061 [DEBUG] {qconsumer-0} Adopting Motr thread
hare-hax[270375]: motr[270375]:  c700  FATAL  [lib/assert.c:50:m0_panic]  panic: fatal signal delivered at unknown() (unknown:0)  [git: 2.0.0-307-21-g05f1efe0] /var/motr/hax/m0trace.270375
hare-hax[270375]: Motr panic: fatal signal delivered at unknown() unknown:0 (errno: 0) (last failed: none) [git: 2.0.0-307-21-g05f1efe0] pid: 270375  /var/motr/hax/m0trace.270375 …
> hax: fix SIGSEGV panic on CentOS 8

- hax/hax/handler.py
- hax/hax/motr/__init__.py
- hax/hax/motr/ffi.py
- hax/hax/motr/hax.c
- hax/hax/motr/hax.h
- hax/test/integration/test_motr.py
- hax/test/integration/testutils.py
Hax relays self's and motr-mkfs process events to all the peer connected motr-mkfs
and to hax's motr land. Eventhough motr-mkfs processes event broadcasts are
restricted to the process states only and not to the entire motr process's
configuratio tree hierarchy (i.e. process's corresponding node, controller,
enclosure and drives), hax process events broadcasts happen to its corresponding
configuration tree hierarchy. Thus, when hax's motr land starts, the event is a
broadcast to all the connected motr-mkfs processes as well. As process, entrypoint
and nvec motr process events are given higher proirities, it may happen that
hax's process event broadcast may take time. It is observed that in a certain
situation, hax tries to send an event notification to itself and other connected
motr-mkfs …
> EOS-25916: mkfs halink is not disconnected

- provisioning/miniprov/hare_mp/store.py
Problem: Currently we check all the nodes in 'storage_set' key.
But some of the nodes can be of type 'control_node' and we dont need to
include then while calculating allowed failure vector
Solution: Added check for 'storage_node' while getting list of nodes
**Testing:**
Config generated for 15 node setup is as follows
`pools:
- allowed_failures:
disk: 7
ctrl: 6
encl: 3
rack: 0
site: 0
spare_units: 0
name: storage-set-1__sns
data_units: 8
parity_units: 7`
> EOS-26350: Wrong allowed failure vector is generated

- hax/hax/util.py
Problem: It is possible that consul may not be ready and RC leader may
not have been elected yet, in such a case hax is hitting an exception
during startup which is causing hax to stop.
Solution: Wait until principle RM is not ready
> EOS-25926 [2.0.0-421-RC4.2] [v0.0.14] Deployment stuck for 9 N (12+6+0)

- hax/hax/motr/__init__.py
- hax/test/integration/test_motr.py
Motr ha module restricts the number of configuration objects in Motr
ha vector (nvec response) to 1024 objects.
```
struct m0_ha_msg_nvec_array {
struct m0_ha_note hmna_arr[M0_HA_STATE_UPDATE_LIMIT];
} M0_XCA_ARRAY M0_XCA_DOMAIN(rpc);
...
enum m0_ha_state_update_defaults {
M0_HA_STATE_UPDATE_LIMIT = 1024,
};
```
If Hare sends ha status
for more than 1024 motr configuration objects in a single nvec response
this limitation is hit and hax panics in Motr land.
Solution:
Limit number of configuration objects in a single nvec response to
1024. Create multiple nvec responses for a ha broadcast of more than
1024 objects.
> EOS-25889: hax panics for broadcast of more than 1024 motr objects

- provisioning/miniprov/hare_mp/main.py
- provisioning/miniprov/hare_mp/utils.py
Problem:
On a given node for all the motr processes (confds and ioservices),
presently, mkfs is executed serially via Hare mini-provisioner. It is
executed in parallel across the nodes but not on a node. So ioservices
mkfs does not complete before confd's mkfs completes. Now we don't
require confds to be running for ioservices mkfs (this is done by
passing confd.xc to motr-mkfs). Thus, all can be executed in parallel
on a given node.
For sequential execution of mkfs, it takes significant amount of time
if the number of mkfs requests are more (typically when we have
multinode clusters). With this parallel execution of mkfs we need
to reduce this time.
Solution:
The idea here is to make the mkfs commands to run in parallel.
This PR addresses this using concurrent process execution …
> EOS-25688: Reduce mkfs time for multiple io services

- utils/hare-status
In the containers environment, consul kv calls take a longer time for execution in comparison to the LR environment.
An experiment was done which should a significant difference of 17 mins between the two environments. 
Reduced number of consul kv calls.
Initially, for every process, multiple separate kv calls were made. Now, we are fetching kv for all the processes under a node at once and parsing it further.
- Time taken with the final change ( fetching endpoint for every process function) is yet to be tested on 15 node.
- on 5node could see 33% reduction.
- with code changes in 2 functions -  _process_status()_ and _proc_fid2name()_ fetching at node level is:
```
real 1m5.397s
user 0m9.109s
sys 0m0.164s
```
- original hct status script took
```
real 4m5.153s
user 0m22.156s
sys 0m0.235s …
```
> EOS-25703: hctl status takes too much time in containers

- provisioning/miniprov/hare_mp/main.py
Solution: Added new command 'upgrade' which will be no-op currently
**Test:**
Tested 3 node LR bootstrap and 3 node LC deployment using custom branch.
```
[root@cortx-data-headless-svc-ssc-vm-g3-rhev4-2653 /]# /opt/seagate/cortx/hare/bin/hare_setup upgrade --config yaml:///etc/cortx/cluster.conf --services all
[root@cortx-data-headless-svc-ssc-vm-g3-rhev4-2653 /]# echo $?
0
```
[root@cortx-data-headless-svc-ssc-vm-g3-rhev4-2653 /]# hctl status
Data pool:
0x6f00000000000001:0x81 'storage-set-1__sns'
Profile:
0x7000000000000001:0xcc 'Profile_the_pool': 'storage-set-1__sns' 'storage-set-1__dix' None
Services:
cortx-data-headless-svc-ssc-vm-g3-rhev4-2653
[started]  hax        0x7200000000000001:0x31  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2653@2001
[started]  ioservice …
> EOS-26619: Support 'upgrade' command for Hare mini-provisioning

- provisioning/miniprov/hare_mp/main.py
We can create a support bundle for the 'generate' command using the following filters:
1] Time-bound log collection, like logs for last n days / weeks / months
2] Within component, logs collection limiting to a single or multiple service specific logs
3] Logs collection for the given type of logs (text, binary, etc), as applicable per component
4] Limited sized logs
5] Include or exclude core dumps, exclude by default
6] Include or exclude stack traces, include by default
> EOS-25678: Hare: Add filters to support bundle

- provisioning/miniprov/hare_mp/main.py
Problem :
Hare miniprovisioner init mkfs stage has some "logging.info" logs in
happy path. These logs were added to monitor mkfs process fids and
execution time. These logs do not just go in the log file but also
get printed on the console. Any additional logs on console are
treated as failures/errors by provisioner. Even if those are treated
as errors, but still those are ignored and deployment gets completed
successfully. So currently technically these logs are not harming.
Because of these logs, the error message that is thrown by provisioner
on the console is misleading, which says "init phase of hare, failed".
It is creating confusion when deployment fails in Hare init stage
because of any kind of genuine failure.
Solution :
Remove the log prints in the happy path. Use logging debug …
> EOS-26740 : Remove logging from miniprovisioners init mkfs stage

- provisioning/miniprov/hare_mp/main.py
Solution: Added 'hax' as supported value for 'services' option
**Test:**
Tested 3 node LC deployment
> [root@cortx-data-headless-svc-ssc-vm-g3-rhev4-2653 /]# /opt/seagate/cortx/hare/bin/hare_setup upgrade --config yaml:///etc/cortx/cluster.conf --services hax
> [root@cortx-data-headless-svc-ssc-vm-g3-rhev4-2653 /]# echo $?
> 0
> [root@cortx-data-headless-svc-ssc-vm-g3-rhev4-2653 /]# /opt/seagate/cortx/hare/bin/hare_setup upgrade --config yaml:///etc/cortx/cluster.conf --services all
> [root@cortx-data-headless-svc-ssc-vm-g3-rhev4-2653 /]# echo $?
> 0
> [root@cortx-data-headless-svc-ssc-vm-g3-rhev4-2653 /]# /opt/seagate/cortx/hare/bin/hare_setup post_install --config yaml:///etc/cortx/cluster.conf --services all
> [root@cortx-data-headless-svc-ssc-vm-g3-rhev4-2653 /]# echo $?
> 0
> …
> EOS-26660: "services" option in hare_setup command should support 'hax' as argument

- hax/hax/util.py
- provisioning/miniprov/hare_mp/main.py
It is possible that not all the remote and local process statuses
are updated on every node. For more reliability it is better to
check all the processes status per node explicity.
Solution:
Iterate over each node's processes and check the corresponding status
in Consul KV.
(cherry picked from commit 3e4c24effaad0b81f7ff732b80793f8f0e5266c7)
Conflicts:
provisioning/miniprov/hare_mp/main.py
> EOS-26836: wait function in init is not reliable (cherry pick from main)

- hax/hax/server.py
- rfc/11/README.md
Signed-off-by: Yash Bhamare <yash.bhamare@seagate.com>
- Currently, cluster status cannot be fetched outside of hare installation. In order to provide this functionality, an endpoint is added in hax to give the cluster status in json format.
-  [x] Coding conventions are followed and code is consistent
> EOS-26482 : Changes to support hctl status over http command

- provisioning/miniprov/hare_mp/main.py
- provisioning/miniprov/hare_mp/store.py
- provisioning/miniprov/hare_mp/utils.py
In containers environment init containers in data pods perform mkfs afer which
the data containers start. Ordering with a given pod happens implicitly but not
across the pods. It is possible that while init container on a pod is in-progress
while another data pod has already started. Motr services from the started data
pod may try to connect to the motr mkfs processes running in the init container as
both motr mkfs and motr ioservices use the same motr identifiers. Furthermore,
once the init container completes, motr ioservices connection would break, resulting
in failures. It is possible that motr may experience failures in this case.
It is epected that not even intermittent failures must be observed.
Solution:
To handle this situation, Hare sets a Consul KV per node on completion of …
> EOS-26888: init and data containers are not ordered across the pods

- provisioning/miniprov/hare_mp/main.py
- As per new design in hare for motr-s3 pod separation [here](https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/811696538/WIP+POC+for+more-s3+pod+separation). There are no devices attached and not even a motr services running in s3server pod so we don't need to run init as mkfs. It is not required.
-  Added only condition for server_node on init function to skip init stage for s3server pods.
-  [x] Coding conventions are followed and code is consistent
- We are going to commit this change (and all the other changes related to pod separation) in 'K8s_pod_separation' branch.
> EOS-26607: Skip hare init stage(No-op) in s3server pod

- hax/hax/queue/cli.py
After inject library is introdued, @repeat_if_fails() decorator can't be
used until inject DI engine is configured. It seems like we forgot to
update h0q CLI utility.
Up to this PR neither EQ nor BQ would work from command line.
Solution: configure DI in the main function of queue/cli.py
-  [x] Coding conventions are followed and code is consistent
> Problem: h0q is broken because of inject library

- hax/helper/configure.py
- provisioning/miniprov/hare_mp/cdf.py
- provisioning/miniprov/hare_mp/store.py
- provisioning/miniprov/test/test_cdf.py
EOS-26874: Used constants to filter node type info from conf-store
- Earlier hare uses node type value from conf-store to identify if its a data node (running ioservices) or not. Utils Team had provided a new set of constants ans search API which can be used to extract the information of node type from the conf-store by making use of appropriate key. Thus, creating a strict binding contract between the provisioner and the components.
-  Removed hardcoded node_type value with appropriate constants key and search API.
-  Renamed function name from _get_server_nodes to _get_data_nodes and get_storage_set_nodes to get_data_nodes.
-  [x] Coding conventions are followed and code is consistent …
> EOS-26874: Use constants to filter node type info from conf-store

- hax/hax/motr/__init__.py
- mkfs is getting stuck in case Hax is not ready for entrypoint request
-  In case of exception while replying to entrypoint request Hare will drop
the entrypoint requests silently at hax and hax will not send any entrypoint reply.
In such a case we will let motr timeout and Hare will then expect a subsequent
entrypoint request from Motr
> EOS-25926: mkfs is getting stuck in case Hax is not ready for entrypoint request

- utils/hare-status
During the deployment through jenkins job, we might get an exception in hctl status as consul data might not be updated.
This happens when deploy script has just completed and we immediately call hctl status. Since consul data might not be updated, we get a NoneType object which cannot be iterated.
> 16:37:01 Traceback (most recent call last):
16:37:01 File "/opt/seagate/cortx/hare/bin/../libexec/hare-status", line 362, in
16:37:01 sys.exit(main())
16:37:01 File "/opt/seagate/cortx/hare/bin/../libexec/hare-status", line 356, in main
16:37:01 show_text_status(cns, cns_util, opts.devices)
16:37:01 File "/opt/seagate/cortx/hare/lib64/python3.6/site-packages/hax/util.py", line 143, in wrapper
16:37:01 return f(*args, **kwds)
16:37:01 File "/opt/seagate/cortx/hare/bin/../libexec/hare-status", …
> Bug EOS-26873: hctl status shows NoneType exception when called immediately after ./deploy-cortx-cloud.sh script

- hax/hax/hax.py
- hax/hax/util.py
- systemd/consul-client-conf.json.in
- systemd/consul-server-conf.json.in
- utils/update-consul-conf
- We don't need to run elect rc leader on s3server pods as they don't have confd running
-  We will check if node has confd then only we will add leader watch key
Also we fixed issue where RC election was not happenning due to stale session.
If there is session present for leader without 'value' then we will destroy it
which will trigger RC re-election
> EOS-26610: Don't run elect-rc-leader on s3server pods

- cfgen/cfgen
- provisioning/miniprov/hare_mp/cdf.py
- provisioning/miniprov/hare_mp/main.py
- provisioning/miniprov/hare_mp/utils.py
Currently Hare 'config' stage is assuming that each node / pod will
contain motr services and devices mentioned in CDF file.
In any scenarios, config stage of hare should check, if motr services
are there and then only generate motr related fids.
In case motr services are not there, do not start/intiate motr
dependent services. Also currently 'config' is failing in s3server pod,
if 'motr-hare_keys.json' is not present, this needs to be fixed for
s3server pod.
- Problem statement
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design
Checklist for …
> EOS-26608: config, cfgen support nodes without motr srvces and devices

- cfgen/cfgen
- cfgen/dhall/render.dhall
- cfgen/dhall/render/Endpoint.dhall
- cfgen/dhall/render/LnetEndpoint.dhall
- cfgen/dhall/render/Process.dhall
- cfgen/dhall/types.dhall
- cfgen/dhall/types/Endpoint.dhall
- cfgen/dhall/types/LibfabricEndpoint.dhall
- cfgen/dhall/types/LnetEndpoint.dhall
- cfgen/dhall/types/NodeDesc.dhall
- cfgen/dhall/types/Process.dhall
- cfgen/dhall/types/Service.dhall
- cfgen/dhall/utils.dhall
- cfgen/dhall/utils/lnetendpoint.dhall
- hax/helper/configure.py
- provisioning/miniprov/hare_mp/cdf.py
- provisioning/miniprov/hare_mp/dhall/gencdf.dhall
- provisioning/miniprov/hare_mp/main.py
- provisioning/miniprov/hare_mp/types.py
- provisioning/miniprov/hare_mp/utils.py
- utils/bootstrap-node
- utils/hare-bootstrap
- utils/hare-node-join
- utils/hare-start
- utils/start-node
- utils/update-consul-conf
- utils/util
Presently Hare supports just libfabric in Containers. This restricts testing
Hare and Motr using different transports, e.g. lnet.
Solution:
- Update Hare configuration to support multiple transports.
> EOS-27069: hare does not support multiple network transports

- hax/hax/handler.py
- hax/hax/motr/__init__.py
- hax/hax/types.py
- hax/hax/util.py
- provisioning/miniprov/hare_mp/main.py
- utils/bootstrap-node
- Transition motr process to ONLINE on receiving M0_CONF_HA_PROCESS_RECOVERED.
- Transition motr process to RECOVERING state on receiving
M0_CONF_HA_PROCESS_STARTED event from motr process.
> EOS-24483: hare does not support dtm recovery transitions for processes

- cfgen/examples/ci-boot1-2ios.yaml
- cfgen/examples/ci-boot2-1confd.yaml
- cfgen/examples/ci-boot2.yaml
- cfgen/examples/ci-boot3.yaml
- cfgen/examples/ldr1-cluster.yaml
- cfgen/examples/multipools.yaml
- cfgen/examples/singlenode.yaml
- rfc/11/README.md
- utils/bootstrap-node
- utils/hare-bootstrap
- utils/hare-node-join
- utils/hare-start
- utils/update-consul-conf
While the multiple transport type support was added, a related change was
missed in `utils/bootstrap-node` script. Although the nw `xprt` argument was
added to `getopt` it was not parsed and that lead to failure of `hctl bootstrap`
command.
Solution:
- Fix bootstrap-node script to parse xprt argument.
> hctl: bootstrap-node script is broken

- provisioning/miniprov/hare_mp/cdf.py
- provisioning/miniprov/hare_mp/main.py
- provisioning/miniprov/hare_mp/store.py
- provisioning/miniprov/hare_mp/utils.py
Problem: Refactoring and optimization of similar function which having
same business logic.
1. get_io_nodes(self) in utils.py
2. get_data_nodes(self) in store.py
3. _get_data_nodes(self, pool: PoolHandle) in cdf.py
All above functions are returning either a list of machine_id or a list
of hostname w.r.t service_type(SERVICE_MOTR_IO).
Solution: Defined 2 new function, "get_machine_ids_for_service(service_type)"
and "get_hostnames_for_service(service_type)" which will accept 1st (service_type)
as mandatory arguments and will return a list of nodes with it's machine_id and
a list of nodes with it's hostname respectively.
> EOS-27107: Refactoring and optimization of similar function

- provisioning/miniprov/hare_mp/main.py
- utils/hare-reportbug
Support bundle is not supported for '-s' parameter.
Solution:
Added -s parameter to support bundle generation process.
> EOS-27231: Support Bundle generate is failing for hare

- README.md
`yum erase -y $(rpm -q --whatprovides $(readlink -f /usr/bin/facter))`
would erase existing facter rpm along with the motr rpm, which
depends on it.
Solution: don't erase existing facter rpm, the facter binary
will be overwritten by the `ln -sf` command mentioned later.
-----
[View rendered README.md](https://github.com/andriytk/cortx-hare/blob/update-readme-facter/README.md)
> README: update about facter installation on el7

- cfgen/cfgen
- hax/hax/util.py
- utils/update-consul-conf
Hare configures Motr processes endpoints for both Lnet and Libfabric
transports but the portal values are same for both the transports.
Lnet tranport has an internal limitation and does not support portal
value > 64. Thus bootstrap using lnet transport fails.
Solution:
- Use different portal values for different transports, lnet and libfabric
respectively.
> Problem: Lnet endpoint ports cannot be > 64

- hax/hax/ha/events.py
- hax/hax/hax.py
- hax/hax/util.py
- provisioning/miniprov/hare_mp/main.py
- provisioning/miniprov/hare_mp/utils.py
Problem: MessageBUs class is singleton class and component need to
call MessageBus.init method before making use of Message Bus library
Solution: Calling MessageBus.init method in 'start' interface before
starting other Hare related services
Tested by Manual installation of RPMs.
**Deployment is in progress.**
> EOS-27018: Hare to adopt utils logging framework

- cfgen/cfgen
Presently Hare cfgen allocates entire motr fid for motr
objects. To accommodate updates to an existing fid dynamically, cfgen
must now allocate only the base fid and reserve the 32 bits based on
object mask for the updates.
- generate motr configuration with base fids with two-part key
- dynamic key set to 0 for motr processes.
- Dynamic part of object fid is decided based on MASK Map.
consul-kv.json file generated with fids
1. for processess
```
{
"key": "m0conf/nodes/localhost/processes/55834574848/services/ios",
"value": 15
},
{
"key": "m0conf/nodes/0x6e00000000000001:0x3/processes/0x7200000000000001:0xd00000000/services/0x7300000000000001:0xf",
"value": "{\"name\": \"ios\", \"state\": \"M0_NC_UNKNOWN\"}"
},
{
"key": "m0conf/nodes/0x6e00000000000001:0x3/processes/0x7200000000000001:0x39 …
```
> EOS-26960: Update cfgen to allocate base fid

- hax/hax/server.py
```
Previously hctl status command over http was like below:
curl http://<data-pod:port>/cluster/status
It is required to add version parameters like below:
curl http://<hare-pod/svc:port>/v1/cluster/status
Solution: 
Modified string value as "/v1/cluster/status" in place of
"/cluster/status" in server.py.
```
> EOS-27236: Improve http command for hctl status

- Makefile
- hax/hax/ha/__init__.py
- hax/hax/hax.py
hctl bootstrap hangs in main,
```
[root@ssc-vm-g2-rhev4-1947 ~]# hctl bootstrap --mkfs --xprt libfab ~/1n.yaml
2022-01-07 10:44:17: Generating cluster configuration... OK
2022-01-07 10:44:20: Starting Consul server on this node......... OK
2022-01-07 10:44:29: Importing configuration into the KV store... OK
2022-01-07 10:44:31: Starting Consul on other nodes...Consul ready on all nodes
2022-01-07 10:44:31: Updating Consul configuraton from the KV store... OK
2022-01-07 10:44:33: Waiting for the RC Leader to get elected.... OK
2022-01-07 10:44:36: Starting Motr (phase1, mkfs)...
```
Because config_path kv is missing is missing in Consul, config_path is added through hare mini provisioner, which is not invoked as part of hctl bootstrap.
```
Jan 07 10:49:18 …
```
> EOS-27315: hctl bootstrap is failing in latest hare main

- cfgen/cfgen
- cfgen/examples/singlenode.yaml
- provisioning/miniprov/hare_mp/cdf.py
Presently there's an option to disable aux pool creation in the Hare configuration generator and there is disk repetition found in base pools. Logically, disk repetition is not allowed for base pools but only aux pools can have disks repeated. So, we don't allow overlapping pools, i.e. pools sharing physical devices between them.
Solution:
Depending on the provided configuration we should be able to generate correct combinations of pools. For this, We need to check specifically for the pool instead of pool versions. and if disks are repeated in base pools then it should be thrown AssertionError for that.
> EOS-25537: Improvement in aux pool enable/disable implementation for kubernetes

- cfgen/cfgen
- hax/hax/motr/__init__.py
- hax/hax/types.py
- hax/hax/util.py
- hax/requirements.txt
- stubs/recordclass/__init__.pyi
For dtm to understand if a motr client logs must be discarded, everytime
a motr client restarts, a new fid must be allocated by Hare when Hare
receives an entrypoint request from that motr client.
Solution:
- Hare reserves 32 bits from motr object fid to be used at runtime.
- On motr client restart, when hax receives an entrypoint request,
hax increments the corresponding motr configuration object type
sequence and sets it in the reserved 32 bit of the motr process
configuration object fid.
- Updated fid is saved the Consul corresponding to its base fid.
- Updated motr client process fid is piggy backed over the outgoing
ha messages for a given process from hax to other motr processes.
> EOS-26323: interface to allocate and return a new fid in hax

- provisioning/miniprov/hare_mp/cdf.py
- provisioning/miniprov/hare_mp/consul_starter.py
- provisioning/miniprov/hare_mp/hax_starter.py
- provisioning/miniprov/hare_mp/main.py
- provisioning/miniprov/hare_mp/utils.py
Problem: Current logs are not enough to understand the root
cause in many cases.
Solution:
a) Update the logging.debug statements to logging.info to
increase visibility
b) Add extra log statements for important functions using
decorators
Signed-off-by: Yash Bhamare <yash.bhamare@seagate.com>
> EOS-26606: Improve logging for hare mini-provisioning

- cfgen/cfgen
Hare cfgen create motr configuration object instances corresponding to
motr data and metadata devices associated with motr ioservice and CAS
service types. If an explicitly metadata device is not specified in Hare
CDF, then cfgen does not create a default metadata device for CAS service
type.
Solution:
Create a default ConfDrive object corresponding to `/dev/null` device for
motr CAS service type.
> cfgen: default ConfDrive object is not created for CAS service type

- cfgen/cfgen
- hax/hax/server.py
- utils/hare-status
```
Hare fetches bytecount data from Motr. This needs to be persisted and
an interface must be provided to query the same.
Solution:
- Add Consul KVs for healthy,degraded,critical and damaged 
as a part of cfgen.
- Add a hctl status sub command `--byecount` to report bytecount
information.
- Provide a http command to query byte count information
http://hax-svc:8008/v1/cluster/status/bytecount
```
> EOS-26484: Support http request to query byte count for CSM

- hax/test/test_delivery_herald.py
This warning tells that in updated versions of python, await and async will be treated
as keywords. And hence we get this warning while reusing the user-defined functions
and variables.
Solution:
Rename the function name from await to waitfor.
> EOS-23820: a warning regarding await keyword

- hax/hax/filestats.py
- hax/hax/motr/__init__.py
- hax/hax/motr/ffi.py
- hax/hax/motr/hax.c
- hax/hax/motr/hax.h
- hax/hax/types.py
1. m0_spiel_proc_counters_fetch() in spiel/spiel.h
2. m0_conf_pver_status() in conf/pvers.h
Fetch bytecount stats from motr land to python land in hax.
Motr code
```
count_stats->pc_proc_fid = *proc_fid;
count_stats->pc_bckey[0]->sbk_fid = M0_FID_TINIT('v', 1, 8);
count_stats->pc_bckey[0]->sbk_user_id = 1;
count_stats->pc_bcrec[0]->sbr_byte_count = 4096;
count_stats->pc_bcrec[0]->sbr_object_count = 1;
```
Output received in hax
```
Jan 18 01:39:27 ssc-vm-g3-rhev4-2743.colo.seagate.com hare-hax[31390]: 2022-01-18 01:39:27,093 [DEBUG] {fs-stats-updater} Shreya got bytecount : ByteCountStats(proc_fid=0x7200000000000001:0xf, pvers=[PverBC(pver_fid=0x7600000000000001:0x8, user_id=1, byte_count=4096, object_count=1)])
```
> EOS-27467: Integrate motr apis in Hare for fetching degraded bytecount.

- provisioning/miniprov/hare_mp/cdf.py
- provisioning/miniprov/hare_mp/templates/hare.config.conf.tmpl.1-node
- provisioning/miniprov/hare_mp/templates/hare.config.conf.tmpl.3-node
- provisioning/miniprov/hare_mp/templates/hare.config.conf.tmpl.3-node.sample
- provisioning/miniprov/hare_mp/templates/hare.init.conf.tmpl.1-node
- provisioning/miniprov/hare_mp/templates/hare.init.conf.tmpl.3-node
- provisioning/miniprov/hare_mp/templates/hare.reset.conf.tmpl.1-node
- provisioning/miniprov/hare_mp/templates/hare.reset.conf.tmpl.3-node
- provisioning/miniprov/hare_mp/templates/hare.test.conf.tmpl.1-node
- provisioning/miniprov/hare_mp/templates/hare.test.conf.tmpl.3-node
- provisioning/miniprov/test/test_cdf.py
- provisioning/miniprov/test/test_templates.py
Due to recent changes to the mini provisioner code corresponding unit
tests are failing.
Solution:
Make test code compatible with the related changes in the mini provisioner.
> provisioning: mini provisioning unit tests are failing

- cfgen/cfgen
- hax/hax/util.py
- hax/helper/configure.py
- provisioning/miniprov/hare_mp/cdf.py
- provisioning/miniprov/hare_mp/templates/hare.config.conf.tmpl.3-node.sample
- provisioning/miniprov/hare_mp/utils.py
1. Hare mini provisioner saves local storage devices facts and information
during mini-provisioner config stage. This information is read during the
config stage to generate motr configuration. hare requires devices
information form all the nodes to be available in Consul to generate the
motr configuration on every node. All the nodes in a cluster are provisioned
in-parallel, thus, it is possible that a node might be executing prepare
stage while the othe might already have started with config. This can be
illustrated as follows,
Node 0
```
2022-01-25 22:05:24 cortx_setup [62]: INFO [_provision_components] /opt/seagate/cortx/hare/bin/hare_setup config --config yaml:///etc/cortx/cluster.conf --services all
2022-01-25 22:05:32 cortx_setup [62]: ERROR [main] error(1): config phase of hare, …
```
> EOS-27016: device info accessed before saving

- utils/m0crate-io-conf
m0crate is a Motr tool, which runs IO for workload configuration file
specified in its arguments. m0crate-io-conf is Hare tool which generates
the workload configuration file with current cluster configuration.
m0crate-io-conf script is not generating the workload configuration file
with the current cluster configuration.
So, a fix for m0crate-io-conf script is needed.
Solution :
Update the m0crate-io-conf file with the latest lnet changes to grep
endpoint and fids from consul kv and populated yaml file. Also as support
for both lnet and libfab is needed, transport type option is added.
> EOS-27636: m0crate-io-conf util is broken

- cfgen/cfgen
While generating motr configuration Hare creates ConfDrive
objects for metadata devices before data devices. This puts
metadata devices before data devices in the devices array
populated in motr poolversion machine. Motr maintains a
device to service context array which is indexed using the
data devices identifie,r which is >= 0 < pool width.
A given layout is used to map a given data unit to its
corresponding object index in the pool and this object index
is used as a subscript to fetch the corresponding ioservice
context. Thus adding CAS devices between the data devices
may lead to incorrect mapping of device to service context.
Solution:
Create all the data devices before metadata devices while
generating configuration.
> cfgen: motr data devices order is broken

- Makefile
- jenkins/prepare-yum-repos
- jenkins/test-boot1
- jenkins/vm-reset
**Problem:**
Pre-merge tests are failing due to the script used to prepare dependencies
still points to CentOS 7.8 refs and VM used for pre-merge job is running 
on OS CentOS 7.8.
[Jenkins Hare-PreMerge-Test](http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Component-Test/job/Hare-PreMerge-Test/)
**Solution:**
1. Replace current VM with centos 7.9 instead with Specs - 
**centos 7.9 , 16 CPU, 16GB RAM, 4 disks/50GB.**
2. Updated the dependencies info in prepare-yum-repos file by correcting 
the centos 7.9 and also verify/Updated all scripts in [Jenkins folder](https://github.com/Seagate/cortx-hare/blob/main/jenkins/) again
as pre-merge job use most of them.
> EOS-27356: hare pre-merge CICD job is failing

- cfgen/dhall/types.dhall
- cfgen/dhall/types/M0ClientDesc.dhall
- cfgen/examples/ci-boot1-2ios.yaml
- cfgen/examples/ci-boot2-1confd.yaml
- cfgen/examples/ci-boot2.yaml
- cfgen/examples/ci-boot3.yaml
- cfgen/examples/ldr1-cluster.yaml
- cfgen/examples/multipools.yaml
- cfgen/examples/singlenode.yaml
- cfgen/tests/singlenode.dhall
- provisioning/miniprov/hare_mp/cdf.py
- provisioning/miniprov/hare_mp/dhall/gencdf.dhall
- provisioning/miniprov/hare_mp/store.py
- provisioning/miniprov/hare_mp/types.py
- provisioning/miniprov/hare_mp/utils.py
- provisioning/miniprov/test/test_cdf.py
Reading from Confstore - motr clients
```
cortx:
motr:
...
num_clients: 2                 # Number of Clients
clients:                       # Motr Client Settings
- name: rgw_s3                 # rgw_s3|s3|cclient (Motr Clients)
num_instances: 1             # Client instances per node (pod)
endpoints:
- tcp://server1-node1:21001  # Format: <protocol>://<hostname_ip>:21001
- tcp://server1-node2:21001  # Num endpoints will be same as num of client instances
- name: motr_client
num_instances: 0             # Optional client. Only for Dev.
endpoints:
- tcp://server1-node1:21001
- tcp://server1-node2:21001
```
and generate CDF
```
nodes:
- transport_type: libfab
m0_servers:
...
m0_clients:
- name: rgw_s3
instance: 1
- name: motr_client
instance: 0
memorysize_mb: 15866.52734375
```
> EOS-27617: Populate CDF with rgw client details fetched from conf-store

- provisioning/miniprov/hare_mp/main.py
- provisioning/miniprov/hare_mp/utils.py
- utils/update-consul-conf
Problem: Currently 'rgw' sysconfig file are generated under path
<config-path>/s3/sysconfig/<machine-id>/
We need to change that path to following
<config-path>/rgw/sysconfig/<machine-id>/
Solution: Changed path of motr client's(such as rgw, s3server etc) sysconfig files
to following format
<config-path>/rgw/sysconfig/<machine-id>/
**Test:**
Tested by running config stage in LC environment
```
[root@cortx-server-headless-svc-ssc-vm-g2-rhev4-2785 cortx-hare]# cat /etc/cortx/rgw/sysconfig/b1616a564b424663ae7a0926621656a8/rgw-0x7200000000000001\:0x9f
MOTR_PROFILE_FID=0x7000000000000001:0xe1
MOTR_RGW_EP='inet:tcp:cortx-server-headless-svc-ssc-vm-g2-rhev4-2785@5004'
MOTR_HA_EP='inet:tcp:cortx-server-headless-svc-ssc-vm-g2-rhev4-2785@2001'
MOTR_PROCESS_FID='0x7200000000000001:0x9f' …
```
> EOS-28564: RGW sysconfig path needs changes

- cfgen/cfgen
- cfgen/dhall/types.dhall
- cfgen/dhall/types/Ports.dhall
- cfgen/examples/multipools.yaml
- cfgen/examples/singlenode.yaml
- cfgen/tests/singlenode.dhall
- provisioning/miniprov/hare_mp/cdf.py
- provisioning/miniprov/hare_mp/dhall/gencdf.dhall
- provisioning/miniprov/hare_mp/types.py
Hare generates motr processes endpoints and internally generates the
corresponding ports. It is important to make the portal range configurable
so that the corresponding endpoint can be generated such that to facilitate
firewall settings as part of the overall product. 
Solution:
- Read portal range from cortx provisioner via hare mini-provisioner
- Update CDF format to optionally include motr processes portal range.
- Generate motr processes endpoint within the given portal range.
> EOS-23618: Motr endpoint ports are not configurable

- provisioning/miniprov/hare_mp/main.py
- utils/update-consul-conf
**Problem**: Fix issues seen during RGW deployment
**Solution**:
motr configuration path was not getting created, modified code
to create motr conf directory.
While executing 'configure' command wrong locale was getting set
Now we are checking if locale is present then we will set UTF locale
**Test:**
Tested by running 'config' stage on CentOS 7.9 and Rocky Linux machines
> Problem: Fix issues seen during RGW deployment

- utils/update-consul-conf
**Solution**: Removed client name from keys in sysconfig file
```
MOTR_PROFILE_FID -> MOTR_PROFILE_FID
MOTR_HA_EP -> MOTR_HA_EP 
MOTR_RGW_EP -> MOTR_CLIENT_EP
MOTR_PROCESS_FID -> MOTR_PROCESS_FID
MOTR_RGW_PORT -> MOTR_CLIENT_PORT
```
**Test:**
On VM,
```
[root@ssc-vm-g2-rhev4-2221 cortx-hare]# cat /etc/sysconfig/rgw-0x7200000000000001\:0x2b
MOTR_PROFILE_FID=0x7000000000000001:0x5b
MOTR_CLIENT_EP='inet:tcp:192.168.59.148@5001'
MOTR_HA_EP='inet:tcp:192.168.59.148@2001'
MOTR_PROCESS_FID='0x7200000000000001:0x2b'
MOTR_CLIENT_PORT=28071
```
On server POD,
```
[root@cortx-server-headless-svc-ssc-vm-g2-rhev4-2785 /]# cat /etc/cortx/rgw_s3/sysconfig/b1616a564b424663ae7a0926621656a8/rgw_s3-0x7200000000000001\:0x96
MOTR_PROFILE_FID=0x7000000000000001:0xdb …
```
> EOS-28748: RGW: Update MOTR endpoint key names in Hare generated config

- hax/hax/handler.py
- hax/hax/motr/__init__.py
- hax/hax/types.py
- hax/hax/util.py
- hax/test/integration/test_motr.py
- utils/get-process-state
- utils/hare-status
hax saves all the motr processes states per node. This can be avoided
now to further optimize the process state transition algorithm.
Solution:
- Maintain single copy of motr processes state in Consul KV.
- No need to check for client process while handling entrypoint requests.
> EOS-27498: util: process statuses are duplicate

- README.md
Update readme with the `transport_type` configuration information for libfabric.
-----
[View rendered README.md](https://github.com/andriytk/cortx-hare/blob/update-readme/README.md)
> README: update with transport_type config info

- hax/hax/ha/handler/node.py
- hax/hax/handler.py
- hax/hax/motr/__init__.py
- hax/hax/queue/__init__.py
- hax/hax/server.py
- hax/hax/types.py
- hax/hax/util.py
- hax/test/integration/test_motr.py
- hax/test/integration/test_server.py
- hax/test/test_types.py
- utils/hare-drive-state
hctl drive-state-set command is used to explicitly transition
motr storage drive objects. Presently the command fails to
apply sns drive state changes due to wrongly parsing the consul
kv to fetch sdev fid corresponding to the drive.
Solution:
- Update consul kv parsing to fetch sdev fid corresponding to the
drive.
- Handle SNS state transitions as well.
> EOS-28773: hctl drive-state-set command does not work

- cfgen/cfgen
- provisioning/miniprov/hare_mp/utils.py
- utils/hare-fetch-fids
- utils/hare-status
- utils/update-consul-conf
**Solution**: Modified key structure to make it dictionary
Aso Modified 'hctl fetch-fids' to include endpoint info.
Also added hax in the list of services returned by 'hctl fetch-fids'.
**Test:**
I ran 'prepare' and 'config' in LR and LC(data and server POD pod). Stages were successfull and following is the 'hctl status' output after changes.
On LC:
[root@cortx-server-headless-svc-ssc-vm-g4-rhev4-0416 tmp1]# hctl status
Byte_count:
critical_byte_count : 0
damaged_byte_count : 0
degraded_byte_count : 0
healthy_byte_count : 0
Data pool:
0x6f00000000000001:0x33 'storage-set-1__sns'
Profile:
0x7000000000000001:0x50 'Profile_the_pool': 'storage-set-1__sns' 'storage-set-1__dix' None
Services:
cortx-server-headless-svc-ssc-vm-g4-rhev4-0416
[started]  hax        0x7200000000000001:0x2d …
> EOS-28577: hctl status not able to read 'm0_client_types' key

- utils/hare-fetch-fids
If fetch-fids command does not find any of the motr services configured
on a node, it returns an error string, If `hctl fetch-fids` is invoked
though a program, the error string in such a case is not parseble. And
user may not understand if its a valid result or not.
Solution:
Return whatever is configured for a given node, return empty if
nothing is configured.
> hctl: fetch-fids command returns un-parseble error string

- hax/hax/bytecount.py
- hax/hax/hax.py
- hax/hax/motr/__init__.py
- hax/hax/util.py
Currently, we have motr apis to fetch the bytecount from motr land.
We need to use these apis and update the byte count of pool versions
in Consul in regular intervals.
Solution:
- Created a separate bytecount updater thread similar to fsStatsUpdater
which updates bytecount information at regular intervals and stores
it consul KV.
> CORTX-27237: Collect bytecount data from Motr and store in consul

- hax/hax/filestats.py
- hax/hax/handler.py
- hax/hax/motr/__init__.py
- hax/hax/types.py
- hax/hax/util.py
Eventhough hare reports process failure (offline) the same is
not updated in consul kv. Thus, while preparing nvec reply,
correct status of the failed process is not reported.
Solution:
- notify offline(M0_NC_TRANSIENT) on process failure instead of
failed(M0_NC_FAILED).
- Update failure of a peer motr process in consul kv through Hare
recovery co-ordinator.
- Read the process status from consul kv.
> CORTX-25823: nvec reply does not contain process real status

- hax/hax/motr/__init__.py
Currently, only two motr ha states are broadcasted: M0_NC_ONLINE and M0_NC_FAILED.
Solution: use to_ha_note_status() to convert ObjHealth state to motr ha state.
> hax: fix ha state setting at broadcast_ha_states()

- hax/hax/bytecount.py
- hax/hax/motr/hax.c
- hax/hax/util.py
```
Based on pool version state for each pool version, it would require to
calculate degraded, critical and healthy bytecounts.
1. _get_pver_with_pver_status() in bytecount.py
Getting a dictionary value of pver and it's state like below
Ex: {'0x7600000000000001:0x8': PverState.M0_CPS_CRITICAL,
'0x7600000000000001:0x9': PverState.M0_CPS_HEALTHY
}
2. update_bc_for_dg_category in util.py
which will update aggreagate bytecount value for each pool on consul.
This function will update bytecount for subsequent dg state/category
which must reflect on cluster status.
```
> CORTX-27238: Categorise bytecount based on pool version state

- Makefile
- cfgen/cfgen
cfgen script imports some of the hax modules and thus require to have
hax modules path accessible if executed explicitly post installation.
e.g.
```
[root@ssc-vm-g4-rhev4-0554 ~]# /opt/seagate/cortx/hare/bin/cfgen
Traceback (most recent call last):
File "/opt/seagate/cortx/hare/bin/cfgen", line 17, in <module>
import psutil
ModuleNotFoundError: No module named 'psutil'
```
Solution:
Add hax module paths for imports to be available to cfgen script as
part of installation.
> cfgen: cfgen execution fails outside of hctl

- hax/hax/handler.py
- hax/hax/message.py
- hax/hax/motr/__init__.py
- hax/hax/motr/hax.c
- hax/hax/motr/planner.py
Currently, M0_HA_NVEC_SET states from Motr are handled similarly to M0_HA_NVEC_GET, which is wrong and contradicts the design. For example, when the disk is repaired, the REPAIRED ha notification from Motr would not be handled.
Solution: add handling of M0_HA_NVEC_SET from Motr. For now, only M0_NC_REPAIRED and M0_NC_ONLINE are handled, which is sufficient for SNS repair/rebalance. More states can be added later.
References:
- https://jts.seagate.com/browse/CORTX-29018
How to test:
1) write some data
2) fail some disk: `hctl drive-state --json $(jq --null-input --compact-output '{ node: "centos8", source_type: "drive", device: "/dev/loop1", state: "failed" }')`
3) set its status to repairing state: `hctl drive-state --json $(jq --null-input --compact-output '{ node: "centos8", …
> CORTX-29018: hax: handle ha states from motr

- utils/hare-bootstrap
After initial bootstrap with mkfs, any changes to the devices is not
maintained if the cluster is re-bootstrapped without mkfs option.
Solution:
Regenerate consul configuration and environment only if mkfs options is
specified.
> CORTX-29101 : hctl: devices states are not maintained on re-bootstrap

- hax/hax/handler.py
- hax/hax/util.py
While transitioning a drive state using `hctl drive-state` command, hax
maps the drive name to its corresponding motr fid. While doing this the
corresponding node name is not considered to fetch the drive fid
on a given node.
Solution:
Consider node name while parsing KV to extract the drive fid for a given
node.
> ha: node name not considered while fetching sdev fid

- README.md
Solution:
Add https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/192020649/Hare+Architecture
to Hare README.md document.
-----
[View rendered README.md](https://github.com/mssawant/cortx-hare-1/blob/readme-update/README.md)
> readme: hare architecture document link is missing from README.md

- cfgen/cfgen
- hax/hax/util.py
- utils/hare-status
```
Fixing some cosmetic changes for dg-bytecount hctl status like below:
Existing:                                     After Modification:
{                                             {
"byte_count": {                                "bytecount": {
"critical_byte_count": 0,                        "critical": 0,
"damaged_byte_count": 0,          ==>            "damaged": 0,
"degraded_byte_count": 0,                        "degraded": 0,
"healthy_byte_count": 10502144                   "healthy":10502144
}                                            }
```
> CORTX-29080: Consistent naming convention in hctl status and rest api

- hax/hax/types.py
- hax/hax/util.py
- hax/test/test_types.py
Hare reports a process as M0_NC_ONLINE by default even if the process
has not started.
Solution:
Report M0_NC_TRANSIENT if process has not started yet.
> nvec: report M0_NC_TRANSIENT for unknown status

- cfgen/cfgen
- cfgen/dhall/types.dhall
- cfgen/dhall/types/M0ClientDesc.dhall
- cfgen/examples/ci-boot1-2ios.yaml
- cfgen/examples/ci-boot2-1confd.yaml
- cfgen/examples/ci-boot2.yaml
- cfgen/examples/ci-boot3.yaml
- cfgen/examples/ldr1-cluster.yaml
- cfgen/examples/multipools.yaml
- cfgen/examples/singlenode.yaml
- cfgen/tests/singlenode.dhall
- provisioning/miniprov/hare_mp/cdf.py
- provisioning/miniprov/hare_mp/dhall/gencdf.dhall
- provisioning/miniprov/hare_mp/main.py
- provisioning/miniprov/hare_mp/store.py
- provisioning/miniprov/hare_mp/types.py
- provisioning/miniprov/hare_mp/utils.py
- provisioning/miniprov/test/test_cdf.py
- utils/bootstrap-node
- utils/hare-bootstrap
- utils/hare-fetch-fids
- utils/hare-status
- utils/update-consul-conf
**Test:**
Tested single node RGW deployment, it was successful
```
[root@cortx-data-headless-svc-ssc-vm-g4-rhev4-0635 /]# hctl status
Byte_count:
critical_byte_count : 0
damaged_byte_count : 0
degraded_byte_count : 0
healthy_byte_count : 0
Data pool:
0x6f00000000000001:0x33 'storage-set-1__sns'
Profile:
0x7000000000000001:0x50 'Profile_the_pool': 'storage-set-1__sns' 'storage-set-1__dix' None
Services:
cortx-server-headless-svc-ssc-vm-g4-rhev4-0635
[started]  hax        0x7200000000000001:0x29  inet:tcp:cortx-server-headless-svc-ssc-vm-g4-rhev4-0635@22001
[started]  rgw        0x7200000000000001:0x2c  inet:tcp:cortx-server-headless-svc-ssc-vm-g4-rhev4-0635@21501
cortx-data-headless-svc-ssc-vm-g4-rhev4-0635  (RC)
[started]  hax        0x7200000000000001:0x7 …
```
> Rebase main with rgw

- cfgen/examples/ci-boot1-2ios.yaml
- cfgen/examples/ci-boot2-1confd.yaml
- cfgen/examples/ci-boot2.yaml
- cfgen/examples/ci-boot3.yaml
- cfgen/examples/ldr1-cluster.yaml
- cfgen/examples/multipools.yaml
- cfgen/examples/singlenode.yaml
- cfgen/tests/singlenode.dhall
- utils/hare-bootstrap
- utils/hare-status
**Solution:**
'm0crate-io-conf' expects atleast one client to be configured in CDF.
Modified code to include more client named 'm0_client_other' in
example CDFs
Also modified bootstrap script to skip client service startup
**Test:**
Tested bootstrap on LR setup
```
[root@ssc-vm-g2-rhev4-2221 cortx-hare]# hctl bootstrap --mkfs ~/CDF.yaml_backup
2022-03-03 05:06:36: Generating cluster configuration... OK
2022-03-03 05:06:38: Starting Consul server on this node............ OK
2022-03-03 05:06:48: Importing configuration into the KV store... OK
2022-03-03 05:06:48: Starting Consul on other nodes...Consul ready on all nodes
2022-03-03 05:06:48: Updating Consul configuraton from the KV store... OK
2022-03-03 05:06:50: Waiting for the RC Leader to get elected........... OK
2022-03-03 05:06:59: …
```
> Problem: premerge-test failing due to 'm0crate' failure

- provisioning/miniprov/hare_mp/main.py
All the nodes in the cluster generate hare configuration through
mini-provisioner. As all the nodes are provisioned and started
independant of each other, it is possible that the consul kv is
imported multiple times, overwriting the state of the node that
has already started.
Solution:
Check if consul kv is already imported before importing during mini-
provisioner config stage.
consul-kv.json contains key values for the entire cluster. Thus,
it is sufficent to import consul-kv just once. We fetch one of
the consul kv to check if the key-values were already imported
during start up of one of the nodes in the cluster, this avoids
duplicate imports and thus a possible overwriting of the updated
cluster state.
> CORTX-29148: hclt drive status showing M0_NC_UNKOWN after bootstrap

- rules/sns-repair
Hare uses motr spiel api to trigger sns recovery operations. Presently,
Hare adds the sns operation to broadcast queue, this was changed as part
of commit 7543caf, but since spiel api connects to all the ioservices
in the cluster and sends the trigger to all the ioservices itself, hare,
further invoking the spiel command on all the nodes leads to duplication
of this trigger.
Solution:
Revert to commit `bc44695` and let only rc invoke the spiel command
for sns operations.
> sns: hare issues duplicate sns repair trigger

- hax/hax/bytecount.py
- hax/hax/motr/__init__.py
- hax/hax/motr/ffi.py
- hax/hax/motr/hax.c
- hax/hax/motr/hax.h
- hax/hax/types.py
- hax/hax/util.py
Currently, the bytecount aggregation for pool configurations except
parity units 0 included the parity buffer count.
We are now calculating the parity buffers and removing those from
the final bytecount of a specific pool version.
cdf file
```
pools:
- name: the pool
type: sns  # optional; supported values: "sns" (default), "dix", "md"
disk_refs:
- { path: /dev/loop0, node: localhost }
- { path: /dev/loop1, node: localhost }
- { path: /dev/loop2, node: localhost }
- { path: /dev/loop3, node: localhost }
- { path: /dev/loop4, node: localhost }
- { path: /dev/loop5, node: localhost }
- { path: /dev/loop6, node: localhost }
- { path: /dev/loop7, node: localhost }
- { path: /dev/loop8, node: localhost }
- { path: /dev/loop9, node: …
```
> CORTX-29081: skip parity buffers count while calculating byte count

- utils/update-consul-conf
**Solution:**
Modified 'MOTR_PROFILE_FID' and 'MOTR_CLIENT_PORT' value to be in string format
**Test:** 
Tested 1 node deployment using RGW PR https://github.com/Seagate/cortx-rgw-integration/pull/50
```
[root@ssc-vm-g4-rhev4-0635 ~]# kubectl get pods
NAME                                                 READY   STATUS    RESTARTS   AGE
consul-client-wwm8w                                  1/1     Running   0          42m
consul-server-0                                      1/1     Running   0          42m
cortx-control-678c577b88-gv8ts                       1/1     Running   0          41m
cortx-data-ssc-vm-g4-rhev4-0635-566dc59ff9-49xkh     4/4     Running   0          40m
cortx-ha-7c8dc56d9b-6gcql                            3/3     Running   0          37m …
```
> CORTX-29157: inconsistency in sysconfig file for MOTR_PROFILE_FID key

- hax/hax/types.py
- hax/hax/util.py
- hax/test/integration/test_motr.py
Hare reports online for sns device states in nvec reply.
Solution:
Map sns device states correctly to their respective ha states during
nvec reply.
> CORTX-29099: hare does not map the sns device states correctly

- hax/hax/hax.py
- hctl
- utils/proto-rc
```
2022-02-24 18:38:19 hare/proto-rc: 11016: Process epoch: eq/11: {"message_type": "device-state-set", "payload": {"node": "cortx-data-headless-svc-ssc-vm-g2-rhev4-1475", "source_type": "drive", "device": "/dev/sdg", "state": "failed"}}
2022-02-24 18:38:19 hare/proto-rc: HARE_RC_EVENT_TYPE: device-state-set, HARE_RC_EVENT_PAYLOAD: {
2022-02-24 18:38:19   "node": "cortx-data-headless-svc-ssc-vm-g2-rhev4-1475",
2022-02-24 18:38:19   "source_type": "drive",
2022-02-24 18:38:19   "device": "/dev/sdg",
2022-02-24 18:38:19   "state": "failed"
2022-02-24 18:38:19 }
2022-02-24 18:38:19 2022-02-24 18:38:19,560 [DEBUG] Bound <class 'hax.common.HaxGlobalState'> to an instance <hax.common.HaxGlobalState object at 0x7f07a6f95128>
2022-02-24 18:38:19 2022-02-24 18:38:19,560 [DEBUG] Created and …
```
> CORTX-29223: hax: unset locale causes hctl commands to fail

- .alexrc
- .github/workflows/alex_reviewdog.yml
Alex scan may report certain words to be prohibited from there use in various documentation or code. For example,
easy might be reported as insensitive. Thus we want to avoid such false positives.
**Solution:**
Add relevant words to the list to avoid such false positives as part of Alex scan configuration.
Signed-off-by: Venkatesh K <venkatesh.k@seagate.com>
> CORTX-28870: Alex scan generate false positive

- rules/sns-rebalance
- rules/sns-repair
Hare sns rules scripts use `logger` to log error messages to
standard error. This does not work in container environment as
it tries to access `/dev/log` that is typically linked to
`/run/systemd/journal/dev-log`, which is not present in container
environment if systemd is not enabled.
Solution:
Make logging more generic by echoing the error message instead of using
logger.
> CORTX-29150 : rules: `logger` doesn't work in container environment

- provisioning/miniprov/hare_mp/consul_starter.py
- provisioning/miniprov/hare_mp/hax_starter.py
- provisioning/miniprov/hare_mp/main.py
- provisioning/setup.yaml
- utils/hare-reportbug
**Problem**: 'setup_type' key is getting deleted so Hare needs to stop using it
**Solution**:
Above key was getting used during 'post_install' and suuport bundle generation
Modified code to remove references to above key and make solution generic
**Test:**
Tested 1 node deployment, it was successful.
```
[root@ssc-vm-g4-rhev4-0635 k8_cortx_cloud]# kubectl get pods
NAME                                                 READY   STATUS    RESTARTS   AGE
consul-client-h578z                                  1/1     Running   0          4m38s
consul-server-0                                      1/1     Running   0          4m37s
cortx-control-6c77c7b4d8-ndvtt                       1/1     Running   0          3m18s
cortx-data-ssc-vm-g4-rhev4-0635-8444f98b55-qj64l     4/4     Running   0 …
```
> CORTX-28881: Hare needs to stop using 'cortx>common>setup_type'

- hax/requirements.txt
Problem:
aiohttp version is old. It needs to be upgraded
Solution:
aiohttp version will be upgraded to 3.8.1
This version is latest version and it is
expected to resolve security 
vulnerabilities.
Corresponding JIRA 
https://jts.seagate.com/browse/CORTX-27923
Detailed test results are documented and
document is attached to JIRA
> CORTX-27923 - Upgrade aiohttp version to 3.8.1

- hare.spec
In latest container deployments, consul servers are deployed with
version 1.10.0 while clients are still on 1.9.1 and the latest released
version is 1.11.4.
```
[root@cortx-data-headless-svc-ssc-vm-g3-rhev4-2107 /]# consul members
Node                                            Address              Status  Type    Build   Protocol  DC   Segment
consul-server-0                                 172.18.167.20:8301   alive   server  1.10.0  2         dc1  <all>
consul-server-1                                 172.18.31.90:8301    alive   server  1.10.0  2         dc1  <all>
consul-server-2                                 172.18.164.149:8301  alive   server  1.10.0  2         dc1  <all>
cortx-data-headless-svc-ssc-vm-g3-rhev4-2107    172.18.120.211:8301  alive   client  1.9.1   2         dc1 …
```
> consul: hare consul version range is obsolete

- hctl
In container environment, `locale -a` command generates following
warnings,
```
[root@cortx-data-headless-svc-ssc-vm-g2-rhev4-1630 /]# locale -a
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_COLLATE to default locale: No such file or directory
```
Hare hctl interface uses `locale -a` to find and set appropriate locale, thus
the above warnings are generated during hctl command execution.
Solution:
Redirect stderr messages generated on `locale -a` execution to `/dev/null`.
> CORTX-29457: locale warnings generated as part of hctl command

- provisioning/miniprov/hare_mp/main.py
- provisioning/miniprov/hare_mp/utils.py
Some of the newly added Hare-Consul key values are not included in the list of keys
to be deleted as part of the Hare mini-provisioner cleanup stage, e.g. byte-count.
Solution:
Removed remaining key values from consul kv as part of Hare mini-provisioner 
cleanup stage.
> CORTX-29311: Hare-mini-prov: include missing hare kvs to be deleted during cleanup

- hax/hax/handler.py
- hax/hax/server.py
- hax/hax/util.py
- systemd/consul-client-conf.json.in
- systemd/consul-server-conf.json.in
It is possible that Consul may not send service state notifications
periodically as configured, see https://github.com/hashicorp/consul/issues/7069.
Sometimes the notification is sent only on Consul service state change.
During bootstrap if a peer process has not started, Hare reports it as offline
in nvec reply to another process. Relying on Consul notification, Hare expects
that the offline state will be updated to online on receiving a corresponding
periodical Consul notification. But as the notification might get delayed or
not arrive at all, the offline state of the process may not be updated to
online, which may further lead to inconsistencies.
Solution:
Watch `processes/` key value for the updates reported by the individual
process and accordingly broadcast the process state change …
> ha: process state update is not a broadcast

- hax/hax/bytecount.py
- hax/hax/util.py
After cluster or process restart, the 'ios' process health state
was received as 'OK' despite being offline. This led to invoking
motr spiel api for offline ios process and killing bytecount
updater thread.
Solution:
Returning correct health states of processes in get_m0d_statuses() api.
> CORTX-29142: Bytecount thread exiting due to incorrect process health state.

- hax/hax/server.py
- provisioning/miniprov/hare_mp/main.py
- provisioning/miniprov/hare_mp/utils.py
- rfc/11/README.md
- utils/hare-fetch-fids
**Solution**:
Added support for API for fetching fids and other client info.
Also modified 'hctl fetch-fids' to provide an option to read
info from consul rather than kv file
**Test:**
Tested 1 node deployment, deployment was successful.
Tested api 'curl http://172.16.150.118:8008/v1/cluster/fetch-fids'
```
[root@ssc-vm-g4-rhev4-0635 ~]# curl http://172.16.150.118:8008/v1/cluster/fetch-fids
[
{
"name": "cortx-server-headless-svc-ssc-vm-g4-rhev4-0635",
"svcs": [
{
"name": "hax",
"fid": "0x7200000000000001:0x29",
"ep": "inet:tcp:cortx-server-headless-svc-ssc-vm-g4-rhev4-0635@22001"
},
{
"name": "rgw",
"fid": "0x7200000000000001:0x2c",
"ep": "inet:tcp:cortx-server-headless-svc-ssc-vm-g4-rhev4-0635@21501",
"ha_ep": "inet:tcp:cortx-server-headless-svc-ssc-vm-g4-rhev4-0635@22001", …
```
> CORTX-27809: Provide an interface/API to query motr client endpoint and fid

- cfgen/cfgen
- hax/hax/bytecount.py
- hax/hax/filestats.py
- hax/hax/hax.py
- hax/hax/motr/__init__.py
- hax/hax/motr/ffi.py
- hax/hax/motr/hax.c
- hax/hax/motr/hax.h
- hax/hax/types.py
- hax/hax/util.py
- provisioning/miniprov/hare_mp/main.py
- provisioning/miniprov/hare_mp/utils.py
- utils/hare-status
Currently, deployment is failing due to missing changes (dg_bytecount) in Motr's main branch. 
Once Motr's `dg_bytecount` branch is merged to main, we can merge this PR.
Tests:
Deployment is successful with Motr's `dg_bytecount` branch.
link - https://eos-jenkins.colo.seagate.com/job/Cortx-Automation/job/RGW/job/setup-cortx-rgw-cluster/1133/
IOs are successful
```
[root@ssc-vm-g2-rhev4-2610 ~]# aws s3 mb s3://test-bucket --endpoint-url http://192.168.54.124:30080                                                     make_bucket: test-bucket
[root@ssc-vm-g2-rhev4-2610 ~]# aws s3 ls --endpoint-url http://192.168.54.124:30080
2022-03-21 02:28:31 test-bucket
[root@ssc-vm-g2-rhev4-2610 ~]#
[root@ssc-vm-g2-rhev4-2610 ~]# dd if=/dev/urandom of=/tmp/9M bs=1M count=9
9+0 records in
9+0 records out …
```
> Merge dg_bytecount branch to main

- hax/hax/handler.py
- hax/hax/util.py
We don't want to allow any hax process to update the remote
process's persistent state, i.e. `processes/<proc-fid>` in-
order to maintain consistency. Thus we allow only RC (recovery
coordinator) to update the remote process's persistent state.
But, this was not working and any hax process was allowed to
update the remote procces's persistent state, which led to
inconsistencies.
Solution:
Allow only RC (recovery coordinator) or process's local hax
to update the remote process's persistent state.
> CORTX-29488: non rc hax process might update the remote process state

- provisioning/miniprov/hare_mp/consul_starter.py
- provisioning/miniprov/hare_mp/main.py
Hare configures consul client agent with 0.0.0.0 bind address. Some
of the Hare rules fetch the bind address from Consul in-order to
communicate over http, but communication fails as 0.0.0.0 resolution
fails.
Solution:
Bind Consul client agent to a specific ip address instead of 0.0.0.0.
> CORTX-29486: Hare fails to communicate on 0.0.0.0 consul bind address

- hax/hax/handler.py
- hax/hax/hax.py
- hax/hax/server.py
- hax/hax/types.py
- hax/hax/util.py
Presently the handler function to update and broadcast motr
process state changes is a bit convulated and is difficult to
read. Also, hax updates the remote process's state only in
case of node failure but not if process is reported as offline.
Solution:
- Simplify process state update logic.
- Update remote process state if the current state of the
process is either failed or offline.
> CORTX-29700: ha: function to update motr process state is complicated

- provisioning/miniprov/test/test_cdf.py
**Solution:**
Modified keys used in tests according to new drive related key structure.
Change in the key is as follows
self.kv.kv_put(f'{hostname}/{disk_key}', drive_info)
to
self.kv.kv_put(f'{hostname}/drives/{disk_key}', drive_info)
**Tests:**
```
(.py3venv) [root@ssc-vm-g2-rhev4-2221 miniprov]# git push -f myrepo fix_tests
Everything up-to-date
(.py3venv) [root@ssc-vm-g2-rhev4-2221 miniprov]# python ./setup.py test
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
running egg_info
writing hare_mp.egg-info/PKG-INFO
writing dependency_links to hare_mp.egg-info/dependency_links.txt
writing entry points to hare_mp.egg-info/entry_points.txt …
```
> Problem: Mini-provisioning testes are broken after 'drives' related changes

- hax/hax/bytecount.py
- hax/hax/exception.py
- hax/hax/motr/__init__.py
During node failures,  failed services are falsely reported as active due to delay issue by Consul. 
When we try to connect those service we get an error from motr apis.
Instead of aborting the thread, we should keep the thread running but break the iteration and start a new iteration.
Log the error reported.
1. 1+0 config, 3N
```
[root@cortx-data-headless-svc-ssc-vm-g4-rhev4-0848 ~]# hctl status --bytecount
{
"bytecount": {
"critical": 0,
"damaged": 1048576000,
"degraded": 0,
"healthy": 0
}
}
```
After pod is up again ---
```
2022-03-31 06:59:14,491 [ERROR] {byte-count-updater} Failed to update Consul KV due to an intermittent error. The error is swallowed since new attempts will be made timely
2022-03-31 07:49:11,523 [ERROR] …
```
> CORTX-29944: Bytecount thread gets aborted when receiving error from motr API

- cfgen/cfgen
- cfgen/dhall/types/Ports.dhall
- cfgen/examples/multipools.yaml
- cfgen/examples/singlenode.yaml
- cfgen/tests/singlenode.dhall
- hax/hax/hax.py
- hax/hax/util.py
- provisioning/miniprov/hare_mp/cdf.py
- provisioning/miniprov/hare_mp/types.py
- systemd/consul-client-conf.json.in
- systemd/consul-server-conf.json.in
- utils/update-consul-conf
The htctl http port number for incoming consul connections is hardcoded
as 8008.
Solution:
Handle the http port value in cfgen:
* Read the port number from CDF.yaml as `/network_ports/hax_http`.
* Write the port number in consul-kv.json as `ports/hax`.
Update consul conf:
* Read the port from kv and configure a consul service `hax_http`.
Read and use the value in hax:
* Read the ServicePort with consul util and use it on hax start.
Signed-off-by: Dmitry Kuzmenko <dmitry.kuzmenko@seagate.com>
> CORTX-27062: Dynamic port range to be parsed from config.yaml for hctl over http

- rfc/11/README.md
- utils/hare-bootstrap
Solution: update the log message text.
Signed-off-by: Dmitry Kuzmenko <dmitry.kuzmenko@seagate.com>
-----
[View rendered rfc/11/README.md](https://github.com/DmitryKuzmenko/cortx-hare/blob/minor_hare-bootstrap_syntax_fixup/rfc/11/README.md)
> Problem: mistype in hare-bootstrap log message.

- provisioning/miniprov/hare_mp/main.py
Need log related improvements in checkrpm related logs.
The empty "stderr:" and "output:" strings are getting logged un-necessarily.
Solution:
Conditionally do not log anything for empty `err` and `out` values.
Signed-off-by: Dmitry Kuzmenko <dmitry.kuzmenko@seagate.com>
> CORTX-28841: MiniProv logging update

- provisioning/miniprov/hare_mp/cdf.py
- provisioning/miniprov/hare_mp/main.py
- provisioning/miniprov/hare_mp/store.py
- provisioning/miniprov/hare_mp/utils.py
CORTX-29546: CORTX clients pods are not working after RGW pods are introduced in 
k8s version 0.1.0
Motr client pods are started by deployment scripts, but hctl status is not showing them.
It seems hare is expecting the component is of motr client similar to RGW which is not
there, since it's part of motr (devel) only.
CORTX-29536: Hare stuck in data pod on removing rgw from motr client list - Granular Data
Only deployment
If we remove rgw from motr client section deployment got failed as hare stuck in data
pod deployment, For scenarios: rgw_s3/motr_client instance count to 0/1 (num_client_inst=1)
in solution.yaml file.
Solution:
Instead of the component name as motr look for the service name as a motr_client.
Added null checking scenarios for get_motr_clients function as it's not …
> CORTX-29546: CORTX clients pods are not working with after RGW pods are introduced in k8s version 0.1.0

- containers/examples/3node/hare.config.conf.3-node
- containers/examples/3node/hare.config.conf.n.cvgs.3-node
- provisioning/miniprov/hare_mp/cdf.py
- provisioning/miniprov/hare_mp/templates/hare.config.conf.tmpl.1-node
- provisioning/miniprov/hare_mp/templates/hare.config.conf.tmpl.3-node
- provisioning/miniprov/hare_mp/templates/hare.config.conf.tmpl.3-node.sample
- provisioning/miniprov/hare_mp/templates/hare.init.conf.tmpl.1-node
- provisioning/miniprov/hare_mp/templates/hare.init.conf.tmpl.3-node
- provisioning/miniprov/hare_mp/templates/hare.init.conf.tmpl.3-node.sample
- provisioning/miniprov/hare_mp/templates/hare.reset.conf.tmpl.1-node
- provisioning/miniprov/hare_mp/templates/hare.reset.conf.tmpl.3-node
- provisioning/miniprov/hare_mp/templates/hare.test.conf.tmpl.1-node
- provisioning/miniprov/hare_mp/templates/hare.test.conf.tmpl.3-node
- provisioning/miniprov/hare_mp/templates/hare.test.conf.tmpl.3-node.sample
- provisioning/miniprov/samples/sample_provisioner_cluster.json
- provisioning/miniprov/test/test_cdf.py
- provisioning/miniprov/test/test_templates.py
keys replaced old to new:
cvg_count to num_cvg
storage_set_count to num_storage_set
Also changed: 
TMPL_CVG_COUNT TO TMPL_NUM_CVG
TMPL_STORAGESET_COUNT TO TMPL_NUM_STORAGESET
Signed-off-by: Lakshita Jain <lakshita.jain@seagate.com>
Signed-off-by: Lakshita Jain <lakshita.jain@seagate.com>
> CORTX-29741: replace obsolete conf-store keys

- cfgen/cfgen
- cfgen/dhall/types.dhall
- cfgen/dhall/types/ClientPort.dhall
- cfgen/dhall/types/ServerPort.dhall
- cfgen/examples/singlenode.yaml
- cfgen/tests/singlenode.dhall
- provisioning/miniprov/hare_mp/cdf.py
- provisioning/miniprov/hare_mp/dhall/gencdf.dhall
- provisioning/miniprov/hare_mp/types.py
**Solution:**
Modified 'NetworkPorts' to include list of endpoints for clients as well as ios and confd.
cfgen will use endpoint according to type of process
```
network_ports:
m0_server:
- 29000
- 22000
m0_client_other:
- name: rgw
port: 21000
m0_client_s3: null
hax: 22000
```
**Testing in progress**
> Problem: CORTX-29866 Make motr server and client processes port range configurable per process type

- hax/hax/handler.py
- hax/hax/server.py
- hax/hax/util.py
- systemd/consul-client-conf.json.in
- systemd/consul-server-conf.json.in
Problem:
When data pod deleted and its process show offline in
hctl status, but consul kv shows Hax process states
as started.
Solution:
Add Hax service to watcher list.
> CORTX-29700: Add Hax service to watches list

- hax/hax/util.py
It is possible that the imported Consul KV might node be available
on all the nodes at real time. This may lead to temporary failures
in subset of configured nodes while reading Consul KVs. In case of
such failures, interested functions must retry based on the KV
availability expectations (i.e. if the KV must be present or can be
NULL).
Solution:
- repeat init_motr_processes_status() if get_node_fid() fails or
returns None.
> CORTX-31086: init_motr_processes_status does not retry on failure

- hax/test/test_failure.py
This is a unit test to check behavior on single node failure. We invoke the handler for a state update indicating a process is gone, then check that the appropriate components (drive, controller, node, etc.) are marked failed in Consul. We also check that the failures are broadcast through hax.
This test only covers a particular code path (total node failure). There are other code paths for different scenarios (e.g. drive failure or service crash) that will require additional unit tests.
> CORTX-29827: Add unit test simulating single node failure

- utils/hare-reportbug
Motr traces in the support bundles are currently in binary form, which can only be parsed by the exact Motr version that created them. A YAML format is also available that's easier to work with. Motr currently generates YAML traces in its support bundles (see https://github.com/Seagate/cortx-motr/blob/ae3c398111ffae336515613aacd22e89c914683c/utils/m0reportbug#L754 for details). This adds a similar step to Hare's support bundle generation process.
> CORTX-30783: Run m0tracedump when creating support bundles

- rules/sns-rebalance
- rules/sns-repair
Introducing bash variables for HAX node name and HAX port in the sns-repair and sns-rebalance scripts.
> Cortx-29485 SNS Repair: hctl repair start command is not triggering start request 

- Makefile
- provisioning/logrotate/hare_logrotate.sh
Although Hare configures logrotate, the default cron job to run logrotate is configured
to be executed daily on RHEL based operating systems. This delays rotation of Hare logs
and Hare logs might grow to more than the configured limit.
Solution:
Explicitly configure a Hare specific cron job to run logrotate hourly.
> CORTX-26200 : Hare logs are not rotated as per logrotate configuration

- utils/hare-rebalance
- utils/hare-repair
This issue is common to hare utils: hare-repair, hare-rebalance
Both had the hax port hard-coded to 8008 in the curl query URL for status
Solution:
Derive the hax port using consul kv and pass it as a variable to the URL
Signed-off-by: Deepak Nayak <deepak.nayak@seagate.com>
> CORTX-31185: SNS Repair: hctl repair status command is failing

- utils/bootstrap-node
Problem: mkfs phase awaits on STARTED. Sometimes
it leads to a timeout error during bootstrap.
It happens when RECOVERED is sent right after
STARTED.
Solution: check both states (STARTED|RECOVERED).
> XXX: Consider RECOVERED state in mkfs phase.

- hax/hax/handler.py
- hax/hax/server.py
It is possible that several broadcast requests are received by hax
through various events and sources, e.g. Consul, HA, etc. Hax watches
several Consul keys for updates, although Consul sends these updates
in a batch, hax processes them individually. This adds to processing
delay. Additionally, while processing every broadcast request, hax
performs some redundant operations with respect fetching some
peripheral information from Consul.
Solution:
- Process broadcast requests in batches.
- Avoid redundant operations, e.g. checking is a node is an rc node,
fetching local process status, etc.
> broadcast: broadcast message processing is in-efficient

- containers/examples/3node/hare.config.conf.3-node
- containers/examples/3node/hare.config.conf.n.cvgs.3-node
- provisioning/miniprov/hare_mp/cdf.py
- provisioning/miniprov/hare_mp/templates/hare.config.conf.tmpl.1-node
- provisioning/miniprov/hare_mp/templates/hare.config.conf.tmpl.3-node
- provisioning/miniprov/hare_mp/templates/hare.init.conf.tmpl.1-node
- provisioning/miniprov/hare_mp/templates/hare.init.conf.tmpl.3-node
- provisioning/miniprov/hare_mp/templates/hare.reset.conf.tmpl.1-node
- provisioning/miniprov/hare_mp/templates/hare.reset.conf.tmpl.3-node
- provisioning/miniprov/hare_mp/templates/hare.test.conf.tmpl.1-node
- provisioning/miniprov/hare_mp/templates/hare.test.conf.tmpl.3-node
- provisioning/miniprov/hare_mp/templates/hare.test.conf.tmpl.3-node.sample
- provisioning/miniprov/hare_mp/utils.py
- provisioning/miniprov/samples/sample_provisioner_cluster.json
- provisioning/miniprov/test/test_cdf.py
CORTX-30793: `node>{node_id}>storage>cvg`
is obsolete
`node>{node_id}>storage>cvg` is replaced with node>{node_id}>cvg, thus
corresponding users must be updated.
Solution:
Replace occurrences or `node>{node_id}>storage>cvg` with node>{node_id}>cvg.
Signed-off-by: Zahid Shaikh <zahid.shaikh@seagate.com>
> CORTX-30793- Change hierarchy {nodeid}>storage>cvg to {nodeid}>cvg

- cfgen/cfgen
- cfgen/dhall/types/ClusterDesc.dhall
- cfgen/dhall/types/NodeDesc.dhall
- cfgen/examples/multipools.yaml
- cfgen/examples/singlenode.yaml
- cfgen/tests/singlenode.dhall
- provisioning/miniprov/hare_mp/cdf.py
- provisioning/miniprov/hare_mp/dhall/gencdf.dhall
- provisioning/miniprov/hare_mp/templates/hare.config.conf.tmpl.3-node.sample
- provisioning/miniprov/hare_mp/types.py
- provisioning/miniprov/test/test_cdf.py
- utils/hare-rebalance
- utils/hare-repair
- utils/update-consul-conf
**Solution**:
Modified CDF format to move the 'network_ports' info under individual node.
**Test:**
```
[root@cortx-data-headless-svc-ssc-vm-g2-rhev4-2784 /]# hctl status
Bytecount:
critical : 0
damaged : 0
degraded : 0
healthy : 0
Data pool:
0x6f00000000000001:0x9f 'storage-set-1__sns'
Profile:
0x7000000000000001:0xde 'Profile_the_pool': 'storage-set-1__sns' 'storage-set-1__dix' None
Services:
cortx-data-headless-svc-ssc-vm-g2-rhev4-2785  (RC)
[started]  hax                 0x7200000000000001:0x2f         inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-2785@31101
[started]  ioservice           0x7200000000000001:0x32         inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-2785@34101
[started]  ioservice           0x7200000000000001:0x41 …
```
> CORTX-30898: Endpoint port settings needs to be done at node level instead of cluster level

- hax/hax/handler.py
- hax/hax/server.py
- systemd/consul-client-conf.json.in
- systemd/consul-server-conf.json.in
- utils/update-consul-conf
Hare watches entire `processes/` kv tree for corresponding process
state changes. But, consul generates notification for entire tree
for even a single process state change. This adds to delay in
processing of the relevant events.
Solution:
Watch specific processes kv per processes so that only relevant
Csonul events are generated.
> CORTX-31298: watching processes/ prefix is in-efficient

- cfgen/cfgen
- hax/hax/ha/ha.py
- hax/hax/handler.py
- hax/hax/util.py
When consul notifies hax with process failure events, we need to report
aggregated node status to HA.
- When one or more processes fails but less than total no. of processes
running on a particular node, we report node status "degraded", by the
local node.
- When all the processes fail, then RC node reports node status
"offline" for that node.
The states of the processes are maintained in consul kv key `process/<process fid>`
- killing the pod (node failure)
- process failure notification was received by both the RC node and local node.
local node
- until hax was up, received local process failure events.
- Sent node status=degraded
- once hax was down, nothing happened.
RC node
- Received all the process failure events.
- sent degraded node status
- sent offline node status - when all …
> CORTX-29826: Hare-HA: report node status as degraded or offline based on process failures

- jenkins/bootstrap-singlenode
- jenkins/prepare-yum-repos
PreMerge Jenkins Job failing due to couple of issues,
1. On RoclyLinux VM, still we are using Repository which is pointing to CentOS7.9.
2. losetup: set up and control loop devices is not working because, it not getting detached as expected.
Solution:
1. Repository changes in jenkins/prepare-yum-repos file to rockylinux.
2. Detach loop device before setting up.
> CORTX-31431: PreMerge Issue: loops devices are not getting detached 

- utils/update-consul-conf
Hare watches individual process state changes through consul KV updates.
But every node does not watch all the nodes Hare and motr processes
presently. This prevents from state updates to be propagated to all
the nodes and can lead to inconsistencies.
Solution:
Every hare node must watch all the Hare and motr processes state
changes in cluster. Add watchers for every Hare and Motr process in
the cluster.
> CORTX-31620: process state change is not a broadcast to all the nodes

- hax/hax/ha/ha.py
- hax/hax/util.py
Updated get_process_based_node_state() to consider all processes which
did not start or not found in consul kv as offline and report node state
as degraded.
> CORTX-31618: hax waits forever for m0_client_other process to start

- rules/sns-rebalance
After triggering "hctl rebalance start" command, the disk is not going into the
"online" state, instead of it remains in the "rebalancing" state.
In the sns-rebalance script, get_hax_port() function not able to fetch
ports/hax key from consul kv.
> CORTX-32070: Disk stuck in rebalancing state after hctl rebalance start cmd

- hax/hax/ha/ha.py
- hax/hax/util.py
machine id to node name mapping is maintained through
mini-provisioner and not during hctl bootstrap.
Thus get_machineid_by_nodename(), may fail infitely
when bootstrapped through `hctl bootstrap`.
Also don't use cache to get node and service statuses,
that may return false statuses.
Solution:
- Do not repeat get_machineid_by_nodename() on failure.
- Avoid caching node and service statuses.
> CORTX-31920: get_machineid_by_nodename() may return None

- hax/hax/ha/message_interface/message_interface.py
- hax/hax/util.py
**Solution**:
Fixed format by removing json.dump()
Also fixed 'degraded' event related issue
**Test:**
Tested 3 node deployment.
Following are few of the events generated
```
Received event={'header': {'version': '1.0', 'timestamp': '1654601238.428012', 'event_id': '1654601238d2b4b6f7a0af4feab5c3266c7c28ba20'}, 'payload': {'source': 'hare', 'cluster_id': 'NOT_DEFINED', 'site_id': 'NOT_DEFINED', 'rack_id': 'NOT_DEFINED', 'storageset_id': 'NOT_DEFINED', 'node_id': 'a4760ca16c728947f2bf2db1b16c85f1', 'resource_type': 'node', 'resource_id': 'a4760ca16c728947f2bf2db1b16c85f1', 'resource_status': 'degraded', 'specific_info': {'generation_id': 'cortx-data-headless-svc-ssc-vm-g2-rhev4-2784'}}}
Received event={'header': {'version': '1.0', 'timestamp': '1654601241.102206', 'event_id': …
```
> CORTX-29710: Hare-HA - Correct the message format sent from Hare to ha

- hax/hax/util.py
Hare reports a ioservice as STARTED when it transitions to
M0_CONF_HA_PROCESS_DTM_RECOVERED but confds are reported as online
when they transition to M0_CONF_HA_PROCESS_STARTED. Hare rconfc
starter thread checks if all the ioservices and confds are `online`
before initializing motr spiel api through `get_m0d_statuses()`,
which fetches health (using `get_service_health()`) of both confds
and ioservices. Presently `get_service_health()`, reports RECOVERING
for confd as it does not transition to `M0_CONF_HA_PROCESS_DTM_RECOVERED`
state. This blocks rconfc and spiel api initialization.
Solution:
Invoke `get_service_health()` only for ioservices in `get_m0d_statuses()`
> CORTX-32139: bytecount and filesystem stats are not updating

- cfgen/tests/sample-confd.dhall
With addition on new service object attribute `params` cfgen tests
are failing with invalid dhall function argument, as they were not
updated accordingly.
Solution:
Update cfgen test sample confd dhall file to include `params` as service
attribute.
```
[520478@ssc-vm-g4-rhev4-0554:cortx-hare-1] make test
--> Testing cfgen
[520478@ssc-vm-g4-rhev4-0554:cortx-hare-1]
```
> CORTX-29824 : cfgen: cfgen test fail

- utils/hare-fetch-fids
As the cortx deployments starts using fdqn instead of just
short hostnames, it is important that the corresponding users
switch to more consistent node names and avoid assumptions that
exepct the system and configured names to be same.
Solution:
Use full node name, socket.getfqdn() instead of just hostname.
> CORTX-32140: hctl fetch-fids command fails

- jenkins/bootstrap-singlenode
Fix for premerge test failures
Ensures that Motr processes aren't lingering and holding onto loop devices. Loop device detatch is lazy as of kernel 3.7, so if there's a mounted filesystem or open file descriptor for the device, losetup -d will run successfully but not actually detatch the loop device (it will be automatically detatched when the last reference is released). Stuck Motr processes have been interfering with loop devices here, so ensure they're cleaned up. Note that this assumes that there are no other tests or Motr instances running on the same host, as it just kills all m0d and m0mkfs.
> CORTX-31431: Kill any lingering Motr processes holding onto loop devices 

- hax/hax/motr/hax.c
Removing this dependency between motr and hax will
help reduce build time.
Signed-off-by: Rinku Kothiya <rinku.kothiya@seagate.com>
> CORTX-31642: Remove dependency between motr and hax

- hax/hax/handler.py
- hax/hax/hax.py
- hax/hax/util.py
- hax/test/integration/test_motr.py
In order to broadcast every motr process state update in cluster to
every other motr process, Hare watches the every motr process's state
machine transitions. A possible race between motr process state updates
can occur where the motr process reports M0_CONF_HA_PROCESS_STARTED and
hare updates the same in Consul, this triggeres a notification locally
as well as to remote processes. When local process in handling this
M0_CONF_HA_PROCESS_STARTED state transition notification, it is possible
the motr process reported M0_CONF_HA_PROCESS_DTM_RECOVERED and its
corresponding state machine in Consul KV was accordingly transitioned.
But the in-progress processing of M0_CONF_HA_PROCESS_STARTED state
transition, happening in a separate thread, might already be
updating the process state in Consul …
> CORTX-32139: bytecount statistics do not update

- hax/hax/handler.py
- hax/hax/motr/__init__.py
- hax/hax/util.py
Hax may receive a Motr/S3server failure notification from Consul or
cortx-ha. But the notification can be delayed and the process might
have already restarted. When a Motr/S3server process, it requests
entrypoint information from Hare, which implies that the service is
starting. This can be used as a sure point to notify a failure before
replying to the process's entrypoint request.
Also, to note that it is important to identify the bootstrap situation
vs the failure case. We need not report failure for a bootstrapping
process.
Solution:
- Maintain a motr/s3server restart count, fetch the count when hax gets
a First entrypoint request. Check if the process is starting for the
first time or subsequent.
- If a motr/s3server process is not starting for the first time, send
a failure …
> CORTX-32095: Problem: hax may not report a motr failure in real time

- hax/requirements.txt
Solution: The issue was with the version of charset-normalizer, a package that
aiohttp (a package required by HARE) was pulling in as a depend. We have now set
the version of charset-normalizer to 2.0.12 - which works with aiohttp 3.8.1
as required by HARE.
Signed-off-by: Deepak Nayak <deepak.nayak@seagate.com>
> CORTX-32329: Hare builds are failing for main and custom-ci branches

- provisioning/miniprov/hare_mp/main.py
Tested below command after doing 3 node deployment
> /opt/seagate/cortx/hare/bin/hare_setup upgrade --changeset yaml:///etc/cortx/changeset.conf --config yaml:///etc/cortx/cluster.conf
> CORTX-26260: HARE: Support Config SW Upgrade

- Makefile
- cfgen/cfgen
- cfgen/dhall/types/NodeDesc.dhall
- cfgen/examples/ci-boot1-2ios.yaml
- cfgen/examples/ci-boot2-1confd.yaml
- cfgen/examples/ci-boot2.yaml
- cfgen/examples/ci-boot3.yaml
- cfgen/examples/ldr1-cluster.yaml
- cfgen/examples/multipools.yaml
- cfgen/examples/singlenode.yaml
- cfgen/tests/singlenode.dhall
- provisioning/miniprov/hare_mp/cdf.py
- provisioning/miniprov/hare_mp/dhall/gencdf.dhall
- provisioning/miniprov/hare_mp/templates/hare.config.conf.tmpl.3-node.sample
- provisioning/miniprov/hare_mp/types.py
- provisioning/miniprov/hare_mp/utils.py
- provisioning/miniprov/test/test_cdf.py
**Solution**:
Added support for 'node_group' in CDF format
**Test:**
Tested 3 node deployment and single node bootstrap
> CORTX-29979: Multiple Data pod deployment: Support Node group in CDF

- hax/hax/handler.py
- hax/hax/motr/__init__.py
- hax/hax/server.py
- hax/hax/util.py
- hax/test/integration/test_server.py
On process restart, before replying to the first entrypoint request,
Hare notifies the process as M0_NC_FAILED to rest of the motr cluster.
But this restricts dtm recovery completion on process restart as the
process is marked as FAILED and not OFFLINE.
Solution:
Notify OFFLINE instead of FAILED on process restart.
> CORTX-32483: all2all dtm test fails

- hax/hax/util.py
**Solution**:
Revert only caching related part of "CORTX-31920: get_machineid_by_nodename() may return None"
This reverts commit fc55437fa66ad992e633b626dd50d51ec0e00c80.
**Testing:**
```
[root@ssc-vm-g2-rhev4-1630 ~]#  kubectl get pods
NAME                                                 READY   STATUS    RESTARTS       AGE
cortx-consul-client-249m4                            1/1     Running   0              121m
cortx-consul-client-4xv9g                            1/1     Running   0              121m
cortx-consul-client-4zpgw                            1/1     Running   0              121m
cortx-consul-client-5wjph                            1/1     Running   0              121m
cortx-consul-client-6dcrx                            1/1     Running   0              121m …
```
> CORTX-32421: [2.0.0-837-07603][v0.7.0][27N] Server pods going into CrashLoopBackOff state during deployment

- cfgen/dhall/types/M0ServerDesc.dhall
- cfgen/examples/ci-boot1-2ios.yaml
- cfgen/examples/ci-boot2-1confd.yaml
- cfgen/examples/ci-boot2.yaml
- cfgen/examples/ci-boot3.yaml
- cfgen/examples/ldr1-cluster.yaml
- cfgen/examples/multipools.yaml
- cfgen/examples/singlenode.yaml
- cfgen/tests/singlenode.dhall
- provisioning/miniprov/hare_mp/cdf.py
- provisioning/miniprov/hare_mp/dhall/gencdf.dhall
- provisioning/miniprov/hare_mp/types.py
- provisioning/miniprov/hare_mp/utils.py
- provisioning/miniprov/test/test_cdf.py
**Solution:**
Added support for log device in CDF fotmat.
Also modified mini-provisioning code to read log device info from confstore and use
it to generated CDF.
**Test:**
Tested 3 node deployment,
Since confstore do not contain 'log' devices as of now, tested it by manually adding log device entry in confstore and running hare 'prepare' and 'config' stage.
```
cvg:
- devices:
log:
- /dev/sdd
data:
- /dev/sdd
- /dev/sde
metadata:
- /dev/sdc
num_data: 2
```
CDF generated with following entry for log devices
```
nodes:
- transport_type: libfab
m0_servers:
- io_disks:
log:
- path: /dev/sdd
size: 0
blksize: 4096
data:
- path: /dev/sdd
size: 0
blksize: 4096
- path: /dev/sde
```
> CORTX-32347: Add support for log device in CDF

- hax/hax/handler.py
- hax/hax/hax.py
- hax/hax/message.py
- hax/hax/motr/__init__.py
- hax/hax/motr/hax.c
- hax/hax/motr/planner.py
- hax/hax/queue/__init__.py
- hax/hax/server.py
- hax/hax/types.py
- hax/hax/util.py
- hax/helper/ping.py
- hax/test/integration/test_server.py
- hax/test/test_failure.py
- hax/test/test_types.py
- utils/update-consul-conf
CORTX-33628: Hare ha events are not ordered
Hare monitors motr and rgw processes for failures and
broadcasts the same to the entire cluster. But presently
they are not ordered and there's not way to determine the
order in which they were processed across the cluster.
Out of order events affects IO post or during failures
as events are not delivered properly.
Worst, it is extremely difficult to debug the same through
several logs.
Thus, it is important to maintain the event order and logging.
Solution:
- Use broadcast queue to broadcast events and maintain order.
- Let RC only handle the node failure events.
- Let local node handle the process failure event.
- Increase consul service watcher interval and set timeout
for probe to avoid frequent Consul watcher events.
- Guard from delayed …
> CORTX-33628 : Hax motr node restart fix

- hax/hax/motr/hax.h
Problem: motr halon interface code assumes a size of 0x40 for the EP_ADDR_BUF_SIZE
Solution:
The size of the EP_ADDR_BUF_SIZE so used should ideally come from libfabric #define (M0_NET_IP_STRLEN_MAX)
> CORTX-33637: Multi-data pod deployment failed for 24N with 2CVG

- hax/hax/ha/handler/node.py
- hax/hax/ha/message_interface/message_interface.py
When HA send node online event to Hare event_type is not poppulate anymore.
Instead status(online, failed, offline) is available in resource_status.
**Solution**:
Modified code to use 'resource_status' instead of 'event_type'
> CORTX-33728: Actual status of resource is not available in 'event_type' field

- hax/hax/ha/message_interface/message_interface.py
- provisioning/miniprov/hare_mp/cdf.py
- provisioning/miniprov/hare_mp/main.py
- provisioning/miniprov/hare_mp/store.py
- provisioning/miniprov/hare_mp/utils.py
- provisioning/miniprov/test/test_cdf.py
Problem:
Provisioner team is planning to migrate file based Gconf to consule based Gconf.
In order to do this, hare component needs some changes to support this migration.
Solution:
There are changes required in way we fetch the keys and its values from Gconf
e.g. endpoints, Hostname, machineIDs.
Approach we took is,
a) for any key we want to fetch, first we need to fetch num_XXX key from Gconf.
b) based on this number, we need to iterate over each key and get desired value of key.
> CORTX-32741: HARE - Consul Support for GCONF

- hax/hax/util.py
**Problem**: is_proc_client checks if service entry in consul ends with 'm0_client...'
But with current implementation client service entry in consul ends with actual service name
**Solution**:
Modified code to read client types are use them to compare client entries from consul.
> CORTX-33637: 'is_proc_client' function is not returning 'True' even for client services.

- cfgen/cfgen
- utils/update-consul-conf
Hare configures motr and most of the configuration is provided as an input via
motr `confd.xc`. Some parameters are passed via a `/etc/sysconfig` file, e.g.
[@ssc-vm-g4-rhev4-0554:cortx-cc] cat /etc/sysconfig/m0d-0x7200000000000001\:0x1
MOTR_M0D_EP='inet:tcp:10.230.240.235@21002'
MOTR_HA_EP='inet:tcp:10.230.240.235@22001'
MOTR_PROCESS_FID='0x7200000000000001:0x1'
MOTR_CONF_XC='/etc/motr/confd.xc'
MOTR_NODE_UUID='b86b7254-11c4-11ed-987d-566fcce40625'
Hare takes the log device from CDF.yaml and the same needs to be added to the 
corresponding motr ioservice's `/etc/sysconfig` file.
Solution:
- Update cfgen to parse log device from CDF and add to m0conf and
update-consul-conf (creates the motr sysconfig file)
- Validate to ensure uniqueness of disks between log/metadata and data sections.
> CORTX-32348: Add log device entries in motr sysconfig file from CDF.yaml

- provisioning/miniprov/hare_mp/store.py
CORTX-33789: Hare Config stage fail with Motr Clients
Problem:
If num_client_inst is specified a non-zero value, deployment is failing.
Issue is with search key. For data nodes we used `'io':'motr'`, it returns the
list of machine IDs which includes both data node and motr client nodes,
because of which deployment was failing.
Solution:
Separated search key for data node and motr client node.
> CORTX-33789: Hare Config stage fail with Motr Clients

- hax/hax/handler.py
- hax/hax/motr/__init__.py
Process events are a broadcast to all the nodes in the cluster.
Not all the nodes are required to update the entire process configuration
tree in KV. Only the process's local hax or RC must do that.
Solution:
- Avoid updating process configuration tree in KV, but notify local motr
processes about any remote process state updates.
- Set HA and Confd process states to M0_CONF_HA_PROCESS_RECOVERED
on receiving M0_CONF_HA_PROCESS_STARTED.
> CORTX-29871: process state machine update multiple times

- cfgen/cfgen
- hax/hax/log.py
- hax/hax/queue/cli.py
- hax/hax/util.py
- hax/helper/configure.py
- hax/helper/update_conf.py
- provisioning/miniprov/hare_mp/consul_starter.py
- provisioning/miniprov/hare_mp/hax_starter.py
- utils/hare_cov/hare_coverage.py
Problem: Redirect Error and Warning messages of Hare processes to stdout/stderr
Solution: Add stream handler to processes missing it. Stream handlers would
have INFO level logging with process id or thread added in log message
depending on context. Log level of some messages are changed to info
from debug.
Signed-off-by: Sarang Sawant <sarang.sawant@seagate.com>
> CORTX-30044 Redirect hare log messages to stdout/stderr

- cfgen/cfgen
The validation for log device size was missing which resulted
in failure of cluster bootstrap. Default size
was taken from lsblk if not provided via confstore.
Solution:
Following motr constraints are considered:
- the log device size upper and lower bounds is set to 4GB and
128MB respectively.
- The size of the log device is rounded off to the nearest
power of 2.
> CORTX-33876: Log device size should be power of 2 with limits

- provisioning/miniprov/hare_mp/main.py
Problem:
rgw admin utility in server init containers is stuck or taking
long time around 10mins for a 5 node setup.
Solution:
This could be due to this rgw utility can connect to
the stale hax process of data pods init container.
To make sure that this utility is connected to data pods
run time hax process, added a delay of 30 secs after
"mkfs done" is completed. This improved the timings of
deployments to within 3 mins.
Signed-off-by: Vinoth.V <vinoth.v@seagate.com>
Testing:
Ran 10 iteration of deployment on 5 node and 9 node using custom build 2.0.0-7596-custom-ci
> CORTX-33786:CORTX Deployment timeout in statefulset of cortx-server

- cfgen/cfgen
- cfgen/examples/multipools.yaml
- provisioning/miniprov/hare_mp/cdf.py
Problem:
The confd and ios Port information in hctl status is not matching with 
cluster.conf in both Both basic Linux and K8s
in basic Linux:
ios Port in hctl status is 21003 instead of 21001 (as per cluster.conf):
```Services:
ssc-vm-rhev4-2906.colo.seagate.com  (RC)
[started]  hax                 0x7200000000000001:0x0          inet:tcp:10.230.240.238@22001
[started]  confd               0x7200000000000001:0x1          inet:tcp:10.230.240.238@21002
[started]  ioservice           0x7200000000000001:0x2          inet:tcp:10.230.240.238@21003
[unknown]  m0_client_other     0x7200000000000001:0x3          inet:tcp:10.230.240.238@22501
[unknown]  m0_client_other     0x7200000000000001:0x4          inet:tcp:10.230.240.238@22502
```
In K8s:
both confd and ios Port are not matching with …
> CORTX-33705: confd and ios ports are not aligned with cluster

- hax/hax/bytecount.py
- hax/hax/filestats.py
- hax/hax/ha/message_type/message_type.py
- hax/hax/handler.py
- hax/hax/hax.py
- hax/hax/motr/__init__.py
- hax/hax/motr/delivery.py
- hax/hax/queue/__init__.py
- hax/hax/server.py
- hax/hax/util.py
- utils/hare_cov/hare_coverage.py
Problem:
As of now, much of the default logging in HARE is at DEBUG level. Its
recommended to use INFO as default log level, to generate just good enough logs
in production releases, and enable DEBUG log level only in development
systems. This enable system to more relevant logs in less number of lines and
hence size.
Solution:
Convert the DEBUG level of such logging to INFO level.
> CORTX-33030: In Hare, Set default log level to INFO

- cfgen/cfgen
fis: Add fault injection service for motr clients and servers
Enabling of FIS will help in inducing the faults using m0console
utility.
For further details refer,
https://github.com/Seagate/cortx-motr/pull/2103
> Enable Fault Injection service for motr

- cfgen/cfgen
- cfgen/dhall/types/ClusterDesc.dhall
- cfgen/examples/singlenode.yaml
- cfgen/tests/singlenode.dhall
- provisioning/miniprov/hare_mp/cdf.py
- provisioning/miniprov/hare_mp/dhall/gencdf.dhall
- provisioning/miniprov/hare_mp/types.py
Hare automatically generates formulaic pool versions (i.e. different
combinations of layouts) based on the tolerances for failure domains
and corresponding layout parameters. In some configuration cases,
these multiple poolversions may not be required and in-order to use
other fault tolerant and recovery methods (e.g. automatic data recovery
on process restart). Thus, there needs to be a way to disable
generating formulaic pool versions.
Solution:
- Add a flag in cdf to disable formulaic pool versions.
- Update cfgen to read corresponding flag and skip generating
formulaic pool versions.
- Add corresponding flag to hare mini-provisioner, set it to False
by default.
> CORTX-30537: add a way to disable formulaic pool versions

- hax/hax/handler.py
- hax/hax/motr/__init__.py
- hax/hax/types.py
- hax/hax/util.py
- hax/test/integration/test_motr.py
- hax/test/test_failure.py
A motr client restart is considered as a permanent failure
and thus, if an existing motr client restarts its existing
fid is updated by Hare. A motr process comprises of motr
services associated to it. Interested motr modules subscribe
to change in the service states, also, motr confc (configuration
cache) maintains a hierarchy of processes and services, thus
if a process fid changes without updating the service fids,
it will not be possible to map a given process to its corresponding
services. Thus, It is important to update the services fids
along with its respective process fid.
Solution:
- Allocate service fids along with its corresponding process fid.
- Make fid allocation routine generic to work for any motr
configuration object.
Signed-off-by: Mandar Sawant …
> CORTX-28971: update service fids along with process fids

- utils/m0crate-io-conf
Probleam:
Hare PreMerge Jenkins Job failing due to m0crate IO failuers.
` [io_req.c:1551:device_check] <! rc=-5 [0x23724c0] too many failures `
Solution:
Added workaround to unblock pre-merged job:
Workaround: Keep IO size and block size same in m0crate-io-conf as below
```
IOSIZE: 2m      # Total Size of IO to perform per object
BLOCK_SIZE: 2m          # In N+K conf set to (N * UNIT_SIZE) for max perf
```
> CORTX-34086: m0crate IO failure

- hax/hax/motr/hax.c
Problem: 
Codacy flags issues in hax.c C code
Solution:
1. Some motr struct asserts were called after the local variable assignments were done.
2. 1 variable (obj_name) had wider scope than necessary.
Signed-off-by: Deepak Nayak <deepak.nayak@seagate.com>
> CORTX-34159: Address and fix Codacy issues in C file (hax.c)

- hax/hax/handler.py
- hax/hax/queue/publish.py
- utils/hare-reportbug
Problem:
HARE bq messages in Support Bundle do not contain timestamps.
This is needed for effective offline debug using logs from Support bundle.
Solution:
Add timestamps to bq publisher; also add the consul kv dump so generated to
Support Bundle.
> CORTX-34147: Add time stamp for consul process state updated in bq

- utils/hare-bootstrap
Hare bootstrap script, hare-bootstrap, presently does not invoke update-consul-conf for client nodes. Presently the script invokes update-consul-conf with `--server` parameter always, which prevents it from updating consul-client-conf.json file by replacing the HAX_HTTP_PROTOCOL variable with corresponding value. This leads to invalid http URL and consul is not able to update the relevant node status.
Solution:
Invoke update-consul-conf for servers and clients separately.
> bootstrap: client consul configuration is not updated
