Seagate/cortx-hare

utils/hare-reportbug

Contains commits from following pull requests:
https://github.com/Seagate/cortx-hare/pull/1349
https://github.com/Seagate/cortx-hare/pull/1352

Improve hctl reportbug tool

---

.gitignore
.gitmodules
Jenkinsfile
Makefile
README.md
cfgen/Makefile
hare.spec
jenkins/prepare-yum-repos
systemd/hare-consul-agent.service

Please, see cherry picked commits info below in the commits log.

Consul RPM patches from `main` branch

---

utils/hare-reportbug

Cherry pick of #1384 pull request to cortx-1.0 branch.

Improve hctl reportbug

---

hax/hax/filestats.py
hax/hax/util.py

That's an overkill, leads to extra load of Consul KV (given we store the
statistics there) and also causes extra fops to happen (Spiel API is
used to fetch that information).
Solution: fetch FS statistics from RC node only.
Closes #1406

Problem: every hax instance updates FS statistics

---

Jenkinsfile

Problem: Jenkinsfile contains user specific credentials. Security team has raised concern for this.
Solution: Use service user account credentials.

Remove user specific credentials from Jenkinsfile

---

hax/hax/hax.py
hax/hax/motr/__init__.py
hax/hax/motr/hax.c
hax/hax/motr/hax.h
hax/hax/types.py
hax/hax/util.py

Solution: take the first profile found in Consul KV, use its FID to initialize Spiel API.
Closes #1435

Problem: wrong FID is used to initialize Spiel API

---

hax/hax/motr/delivery.py

EOS-16167 Refactor wait_for_all and wait_for_any.
Problem:
wait_for_all() and wait_for_any() in DeliveryHerald
class, both functions have replicated code.
Solution:
Created a new function _verify_delivered() in
DeliveryHerald class. This function has common logic 
for checking if delievery has happened. wait_for_any()
and wait_for_all() functions will replace common code
with _verify_delivered() function.
Test steps:
make ran the test_delivery_herald.py
and all tests passed.
Bootstrap passed.
Signed-off-by: Shipra Gupta <shipra.gupta@seagate.com>

EOS-16167 Refactor wait_for_all.

---

rfc/20/README.md
rfc/README.md

Problem: Mini-Provisioner integration is not documented

---

Makefile
cfgen/dhall/types.dhall
cfgen/dhall/types/M0ServerDesc.dhall
cfgen/dhall/types/NodeDesc.dhall
cfgen/dhall/types/PoolDesc.dhall
hare.spec
provisioning/miniprov/Makefile
provisioning/miniprov/exampleV1.json
provisioning/miniprov/hare_mp/__init__.py
provisioning/miniprov/hare_mp/cdf.py
provisioning/miniprov/hare_mp/dhall/gencdf.dhall
provisioning/miniprov/hare_mp/dhall/test.dhall
provisioning/miniprov/hare_mp/main.py
provisioning/miniprov/hare_mp/store.py
provisioning/miniprov/hare_mp/types.py
provisioning/miniprov/requirements.txt
provisioning/miniprov/setup.py
provisioning/miniprov/test/__init__.py
provisioning/miniprov/test/test_cdf.py
provisioning/setup.yaml

Jira link: https://jts.seagate.com/browse/EOS-16511
Solution: leverage Dhall language and type system from CFGEN

EOS-16511: Mini-Provisioner requires CDF generation

---

README.md
hare.spec

Solution:
Update hare requirement for Consul version to 1.9.1.

Problem: Hare uses older Consul version 1.7.8

---

provisioning/setup.yaml

Solution: fix setup.yaml once again. It seems like it was auto-merge
issue.

Problem: latest merge reverted back 'cmd' to 'script'

---

provisioning/miniprov/hare_mp/cdf.py
provisioning/miniprov/test/test_cdf.py

Solution: Use `cluster>{node}>network>data>private_interfaces` (notice
'private').

Problem: data_iface is taken from a wrong ConfStore key

---

provisioning/miniprov/hare_mp/main.py

In case of cluster bootstrap failure in init and test hare mini provisioning
commands, hare_setup exits without attempting to shutdown a partially
running cluster. For example, if s3server fails to start, bootstrap will
fail and hare_setup will exit without stopping the partially running hare
and motr services.
Solution:
Check if cluster is running even in case of bootstrap failure and invoke `hctl
shutdown` while preserving the bootstrap error in order to report command failure.

Problem: Init and test commands may leave partial cluster running

---

provisioning/miniprov/hare_mp/cdf.py
provisioning/miniprov/test/test_cdf.py

JIRA: https://jts.seagate.com/browse/EOS-17250
Solution: take the type value from ConfStore under key
`cluster>{nodename}>network>data>interface_type`

Problem: data_iface_type value is not taken from ConfStore

---

provisioning/miniprov/hare_mp/main.py

Solution: Fixed wrong closing bracket

Problem: hare_setup fails for --test option

---

README.md
cfgen/requirements.txt
hax/setup.py

Description: Transitive dependencies issue resolved regarding idna and also updated directory name from motr to cortx-motr in README file
Problem: make devinstall didn't work due to dependency issues
Solution: Resolved by specifying the required version in cfgen/requirements.txt and setup.py to avoid dependency conflict.
Signed-off-by: SUPRIT SHINDE <suprit.shinde@seagate.com>
-----
[View rendered README.md](https://github.com/supritshinde/cortx-hare/blob/PATCH-1/README.md)

EOS-17487 resolved. (transitive dependency issue)

---

rfc/20/README.md

Solution: Modified rfc according to changes done in hare_setup command
-----
[View rendered rfc/20/README.md](https://github.com/SwapnilGaonkar7/cortx-hare/blob/doc_EOS-17172/rfc/20/README.md)

Problem: some sections in RFC 20 are outdated

---

provisioning/miniprov/hare_mp/main.py
provisioning/setup.yaml

Solution: Add --config option for all commands in hare setup.yaml file

Problem: In setup.yaml file, --config option is mandatory for all commands and that is causing deployment failure

---

rfc/20/README.md

Updated RFC accordingly
-----
[View rendered rfc/20/README.md](https://github.com/SwapnilGaonkar7/cortx-hare/blob/rfc20_update1/rfc/20/README.md)

Problem: some sections in RFC 20 are outdated 

---

hax/hax/motr/delivery.py

It is possible that the messages from a halink promise were already delivered
and the sender invokes wait_for_all, which does not check if the promise was
already delivered or not and may block.
Solution:
Check the promise in recently_delivered list before blocking to confirm if
the messages are not already delivered.

EOS-18828: wait_for_all may wait for already delivered messages

---

provisioning/miniprov/create-template.sh
provisioning/miniprov/hare_mp/cdf.py
provisioning/miniprov/hare_mp/templates/hare.config.conf.tmpl.json
provisioning/miniprov/samples/sample_provisioner_cluster.json
provisioning/miniprov/test/test_cdf.py

Solution: Modified path to access correct path for data, parity and spare

EOS-19035: Problem: [Mini Provisioner] Handle path change for keys present under 'durability'

---

provisioning/miniprov/samples/exampleV1.json
provisioning/miniprov/samples/sample_provisioner_cluster.json

JIRA ticket: [EOS-18815](https://jts.seagate.com/browse/EOS-18815)
Solution: replace "secret" values with STUB strings.

Problem: Sample ConfStore files contain secrets

---

provisioning/miniprov/create-template.sh
provisioning/miniprov/hare_mp/cdf.py
provisioning/miniprov/hare_mp/templates/hare.config.conf.tmpl.1-node
provisioning/miniprov/hare_mp/templates/hare.config.conf.tmpl.3-node
provisioning/miniprov/hare_mp/templates/hare.config.conf.tmpl.3-node.sample
provisioning/miniprov/hare_mp/templates/hare.init.conf.tmpl.1-node
provisioning/miniprov/hare_mp/templates/hare.init.conf.tmpl.3-node
provisioning/miniprov/hare_mp/templates/hare.init.conf.tmpl.3-node.sample
provisioning/miniprov/hare_mp/templates/hare.test.conf.tmpl.1-node
provisioning/miniprov/hare_mp/templates/hare.test.conf.tmpl.3-node
provisioning/miniprov/hare_mp/templates/hare.test.conf.tmpl.3-node.sample
provisioning/miniprov/test/test_cdf.py

Solution: Modified code to access these keys using correct path.

EOS-19149 Problem: Handle missing 'durability' key in paths of data, parity and spare units

---

Makefile

Reverts Seagate/cortx-hare#1570

Revert "EOS-19092 Problem : Makefile doesn't run linters against some of utils/hare-* scripts"

---

Makefile
utils/hare-fetch-fids

1. Since #1570 build was failing since flake8 started to analyze utils/* folder properly and found issues in utils/hare-fetch-fids
2. #1577 reverted #1570 but didn't fix the cause of the issue
This PR fixes flake8 issues and gets back @supriyachavan4398's changes (re-applies #1570)

Problem: flake8 findings break CI build

---

provisioning/miniprov/create-template.sh
provisioning/miniprov/hare_mp/cdf.py
provisioning/miniprov/hare_mp/templates/hare.config.conf.tmpl.1-node
provisioning/miniprov/hare_mp/templates/hare.config.conf.tmpl.3-node
provisioning/miniprov/hare_mp/templates/hare.config.conf.tmpl.3-node.sample
provisioning/miniprov/hare_mp/templates/hare.init.conf.tmpl.1-node
provisioning/miniprov/hare_mp/templates/hare.init.conf.tmpl.3-node
provisioning/miniprov/hare_mp/templates/hare.init.conf.tmpl.3-node.sample
provisioning/miniprov/hare_mp/templates/hare.test.conf.tmpl.1-node
provisioning/miniprov/hare_mp/templates/hare.test.conf.tmpl.3-node
provisioning/miniprov/hare_mp/templates/hare.test.conf.tmpl.3-node.sample
provisioning/miniprov/test/test_cdf.py

Solution: Modified keys to include pool type(sns)

Problem: Durability keys are changed to include pool type(currently hardcoded to 'sns')

---

cfgen/cfgen
provisioning/miniprov/hare_mp/cdf.py
provisioning/miniprov/hare_mp/dhall/gencdf.dhall
provisioning/miniprov/hare_mp/store.py
provisioning/miniprov/hare_mp/types.py
provisioning/miniprov/test/test_cdf.py

Solution:
1. Assume key structure as follows: `cluster>CLUSTER_ID>storage_set[M]>{type}>data`
2. Update tests and templates

EOS-19018: Pool type is not taken from ConfStore

---

provisioning/miniprov/hare_mp/main.py
utils/hare-bootstrap
utils/hare-shutdown

Solution: Modified code to skip consul stop during shutdown, also note that consul will be restarted during bootstrap

EOS-19534 Consul Hare Agent to be started by Hare in Mini-Provisioner Init Phase

---

provisioning/miniprov/hare_mp/main.py

Solution: Modified code to read server node type and use it during post_install
UT:
Tested on local setup deployed using Jenkin.
Will test it on local VM if required.

EOS-19796 Hare post_install need to use confstore keys instead of Provisoiner get_setup_info api

---

README.md
provisioning/miniprov/hare_mp/main.py
provisioning/setup.yaml
rfc/20/README.md
utils/hare-start

-----
[View rendered CONTRIBUTING.md](https://github.com/mssawant/cortx-hare-1/blob/main_stable_5_6_21/CONTRIBUTING.md)
[View rendered README.md](https://github.com/mssawant/cortx-hare-1/blob/main_stable_5_6_21/README.md)
[View rendered SECURITY.md](https://github.com/mssawant/cortx-hare-1/blob/main_stable_5_6_21/SECURITY.md)
[View rendered SUPPORT.md](https://github.com/mssawant/cortx-hare-1/blob/main_stable_5_6_21/SUPPORT.md)
[View rendered doc/hare-dtm-hld.md](https://github.com/mssawant/cortx-hare-1/blob/main_stable_5_6_21/doc/hare-dtm-hld.md)

Merge Hare main to Stable

---

hax/hax/util.py
stubs/consul/__init__.pyi

Solution: analyze Consul Members before invoking Consul Node Health.
Closes #1453 
JIRA ticket: https://jts.seagate.com/browse/EOS-19370

Problem: When node gets offline, hax raises IndexError

---

hax/hax/motr/delivery.py

It is possible that the hax message can be delivered even before
intiating wait on the delivery for a given ha message. In this
particular case, it is observed that the message is already delivered
before hax starting to wait on the delivery. Thus, as delivery callback
is already received, `notify waiting clients dict_items([])` and
hax starts waiting after the notification,
`waiting for broadcast of [MessageId(0x7f21a8008f00, 1)]`, the notification
is missed and hax continues to wait, thus timing out the entrypoint reply.
Solution:
Add the delivered `MessageID` to `herald.recently_delivered` list unconditionally
so that the delivered message is already present in the `recently delivered` messages
list when hax start to wait for then same.
Signed-off-by: Mandar Sawant …

EOS-20534: hax message can be delivered before waiting for delivery

---

cfgen/cfgen
hax/hax/util.py
hctl
provisioning/miniprov/hare_mp/cdf.py
provisioning/miniprov/hare_mp/dhall/gencdf.dhall
provisioning/miniprov/hare_mp/templates/hare.config.conf.tmpl.3-node
provisioning/miniprov/hare_mp/templates/hare.config.conf.tmpl.3-node.sample
provisioning/miniprov/hare_mp/templates/hare.init.conf.tmpl.3-node
provisioning/miniprov/hare_mp/templates/hare.init.conf.tmpl.3-node.sample
provisioning/miniprov/hare_mp/templates/hare.test.conf.tmpl.3-node
provisioning/miniprov/hare_mp/templates/hare.test.conf.tmpl.3-node.sample
provisioning/miniprov/hare_mp/types.py
provisioning/miniprov/test/test_cdf.py
stubs/consul/__init__.pyi
utils/hare-bootstrap

-----
[View rendered CONTRIBUTING.md](https://github.com/mssawant/cortx-hare-1/blob/main_to_stable_5_12_21/CONTRIBUTING.md)
[View rendered README.md](https://github.com/mssawant/cortx-hare-1/blob/main_to_stable_5_12_21/README.md)
[View rendered SECURITY.md](https://github.com/mssawant/cortx-hare-1/blob/main_to_stable_5_12_21/SECURITY.md)
[View rendered SUPPORT.md](https://github.com/mssawant/cortx-hare-1/blob/main_to_stable_5_12_21/SUPPORT.md)
[View rendered doc/hare-dtm-hld.md](https://github.com/mssawant/cortx-hare-1/blob/main_to_stable_5_12_21/doc/hare-dtm-hld.md)

Main to stable 5 12 21

---

cfgen/cfgen
hax/hax/motr/delivery.py
hax/hax/types.py
hax/hax/util.py
hax/requirements.txt
provisioning/miniprov/Makefile
provisioning/miniprov/hare_mp/main.py
provisioning/miniprov/mypy.ini
provisioning/mypy.ini

Merge to stable branch as of 06/09/21
Commits to be merged:
```
5c5ad4e Problem: newer mypy fails on Hare sources
ae8504a EOS-20779: 1N VM-Deployment Failed in hare for the build Main#1178 Issue : The bug was reported by Jenkins deployment failure and also was seen locally a couple of times. The r
14a83b6 EOS-21028: hare_setup init and test stop cluster too soon
010d87f EOS-20534: hax message can be delivered before waiting for delivery
a85fc11 EOS-18907: Implement "reset" and "cleanup" phase for Hare mini-provisioner
```

Stable merge 060921

---

utils/update-consul-conf

EOS-21072: Update s3server port to 28071

---

provisioning/miniprov/hare_mp/main.py

Solution : To generate log file which will contain all the logs generated during deployment(generated by hare_setup) by hare component.

EOS-19923 : Generate setup.log file for hare deployment

---

README.md

Signed-off-by: Patrick Hession <patrick.hession@seagate.com>
Added link for steps required to install cortx-utils.

Added cortx-utils installation steps

---

provisioning/miniprov/hare_mp/main.py
provisioning/setup.yaml

EOS-19917 CORTX-HARE: Implement test interface for Hare

---

hax/hax/motr/__init__.py
hax/hax/util.py

On node failure, hax notifies M0_NC_FAILED for all the motr processes on that node to all
the peer motr processes. Along with this the corresponding drives to the ioservices are also
notified as M0_NC_FAILED. But motr does not allow transition to M0_NC_ONLINE from M0_NC_FAILED.
A FAILED motr device, that is notified M0_NC_FAILED in case of permanent failure must go
through M0_NC_FAILED -> M0_NC_REPAIRING -> M0_NC_REPAIRED -> M0_NC_REBALANCING ->
M0_NC_ONLINE to become online. Thus a direct transition from M0_NC_FAILED -> M0_NC_ONLINE is
not allowed. Thus, hax needs to notify M0_NC_OFFLINE instead of M0_NC_FAILED for the ioservice
devices in case of node/process failure, this is also interpreted as transient failure for
devices.
Solution:
Notify M0_NC_OFFLINE and not M0_NC_FAILED for …

EOS-23123: hax transitions motr drives to M0_NC_FAILED instead of M0_NC_OFFLINE

---

.github/workflows/alex_reviewdog.yml
hax/hax/motr/__init__.py
hax/hax/util.py
provisioning/miniprov/hare_mp/main.py

Merge last 5 commits from main branch to stable:
```
commit 6f920405449d57bf8de6c297a55f540f50cdd8e6 (HEAD -> main-stable-7-26, mein/main-stable-7-26)
Author: Mandar Sawant <mandar.sawant@seagate.com>
EOS-23123: hax transitions motr drives to M0_NC_FAILED instead of M0_NC_OFFLINE
commit 93bc676ea0b33b4a4ff0bcc1749dc3ae29da54eb
Author: Vaibhav Paratwar <vaibhav.paratwar@seagate.com>
EOS-23093 help strings for pre/post upgrade change
commit e2928007772bb706b4c69460780fae4af3599534
Author: Venkatesh K <venkatesh.k@seagate.com>
Changed the copyright year
commit 0d60c763f9f2db224496110fb879b886a4aafc68
Author: Venkatesh K <venkatesh.k@seagate.com>
Added copyright header
commit 3fc1c8db2bd2ca66e5797454fd7cffa8db5db8fc
Author: Venkatesh K <venkatesh.k@seagate.com>
Added Alex workflow
``` …

Merge main to stable (7/26)

---

cfgen/cfgen
hax/hax/hax.py
hax/hax/util.py
stubs/consul/__init__.pyi

Merge the following commits from main to stable branch:
```
commit a37841449ed6d68eb211768ebfeeee6839779e1b (HEAD -> stable-0802, mein/stable-0802)
Author: Konstantin Nekrasov <konstantin.nekrasov@seagate.com>
EOS-22484: RC can't be re-elected after hctl shutdown
commit 434ba4caa2c99a2e69efc32abda2c4975ace1336
Author: Konstantin Nekrasov <konstantin.nekrasov@seagate.com>
EOS-15352: cfgen doesn't check facter version
```

Merge main to stable 0802

---

provisioning/miniprov/hare_mp/main.py

EOS-23256: Factory reset failing and cluster going in bad state
Factory reset command deletes Hare data from Consul KV and Hare logs. This is not as expected,
because post reset hare_setup init will not be invoked to recreate the deleted Consul KV. Thus,
deletion of Hare Consul KV must be done as part of Cleanup and not reset hare_setup command.
Solution:
As hare_setup init command is expected to be executed post hare_setup cleanup, delete Consul KV in hare_setup cleanup command.

EOS-23256: Factory reset failing and cluster going in bad state

---

.github/auto_assign.yml

Updated Gatekeepers list for Hare

Updated Gatekeepers list

---

utils/manage_events.py

HA is adding event manager class which can be used to subscribe/register and listen for events.
Hare needs to add class to access this event manager for listen events
In this PR, we are adding skeleton class to communicate with Event Manager
Note: Event Manager class is not fully implemented yet, just skeleton class is present right now

EOS-23105 Add skeleton class for integration of Hare with HA Event Manager

---

README.md
hare.spec

Solution:
We replace facter with puppet agent
Signed-off-by: vaibhavparatwar <vaibhav.paratwar@seagate.com>

EOS-21367 : Facter rpm doesn't exist

---

hax/requirements.txt
utils/generate-coverage
utils/hare_cov/README.md
utils/hare_cov/__init__.py
utils/hare_cov/hare_coverage.py

Added script for python and C, which installs the dependency packages, runs UTs and then run the code coverage tool.
Reported-by: Vaibhav Prakash Paratwar <vaibhav.paratwar@seagate.com>
Signed-off-by: ajaykumarptl <ajaykumar.patel@seagate.com>

EOS-22575: Added Code Coverage script.

---

Makefile
hax/requirements.txt
provisioning/miniprov/hare_mp/main.py
provisioning/miniprov/hare_mp/templates/hare.reset.conf.tmpl.1-node
provisioning/miniprov/hare_mp/templates/hare.reset.conf.tmpl.3-node
provisioning/miniprov/test/test_templates.py
provisioning/support.yaml
utils/generate-coverage
utils/hare_cov/README.md
utils/hare_cov/__init__.py
utils/hare_cov/hare_coverage.py

Merging fresh main branch to fault_tolerance
-----
[View rendered utils/hare_cov/README.md](https://github.com/knekrasov/cortx-hare/blob/main-to-fault-tolerance-0825/utils/hare_cov/README.md)

Main to fault tolerance 0825

---

cfgen/cfgen
ha-simulator/README.md
ha-simulator/docker-compose.yml
ha-simulator/docker/Dockerfile
ha-simulator/docker/etc/ha.conf
ha-simulator/docker/etc/message_bus.conf
ha-simulator/docker/patches/0001-Consul-hostname-altered-via-env-variable.patch
ha-simulator/docker/requirements.txt
ha-simulator/docker/run.sh
ha-simulator/emitter.py
ha-simulator/prepare-host.sh
ha-simulator/run-containers.sh
hax/hax/ha/__init__.py
hax/hax/ha/events.py
hax/hax/ha/handler/__init__.py
hax/hax/ha/handler/node.py
hax/hax/ha/thread.py
hax/hax/hax.py
hax/hax/motr/__init__.py
hax/hax/types.py
hax/hax/util.py
hax/mypy.ini
hax/test/integration/test_motr.py
hax/test/integration/testutils.py
hax/test/test_types.py
utils/manage_events.py

JIRA epic: [EOS-17653](https://jts.seagate.com/browse/EOS-17653)
Merging current state of fault_tolerance branch back to main branch.
These changes have been tested during integration testing rooms with CORTX-HA and Motr teams.

EOS-17653 Merge fault_tolerance to main (without aux pools)

---

hax/hax/motr/__init__.py

JIRA issue: [EOS-24124](https://jts.seagate.com/browse/EOS-24124)
Problem: when an MKFS process stops, its storage devices are marked as
offline by hax which may lead to Motr panics (pool version is dirty)
while MKFS stop is a special case which should be handled separately.
Solution: add a condition - if the status is STOPPED and it is an mkfs,
then don't inherit device statuses from this process.

EOS-24124: drives set offline when MKFS process stops

---

provisioning/miniprov/hare_mp/main.py

Adding 'services' option to all the mini-provisioing interfaces
Supporting value for option is 'all'
**UT:**
```
[root@ssc-vm-2494 hare]# /opt/seagate/cortx/hare/bin/hare_setup prepare --config yaml:///tmp/hare_mp_k8/single_node_confstore.yaml --services all
[root@ssc-vm-2494 hare]# /opt/seagate/cortx/hare/bin/hare_setup prepare --config yaml:///tmp/hare_mp_k8/single_node_confstore.yaml
[root@ssc-vm-2494 hare]# /opt/seagate/cortx/hare/bin/hare_setup config --config yaml:///tmp/hare_mp_k8/single_node_confstore.yaml
[root@ssc-vm-2494 hare]# /opt/seagate/cortx/hare/bin/hare_setup config --config yaml:///tmp/hare_mp_k8/single_node_confstore.yaml --services all
```

EOS-25124: Add --services hax option

---

provisioning/miniprov/hare_mp/store.py
provisioning/miniprov/hare_mp/templates/hare.config.conf.tmpl.1-node
provisioning/miniprov/hare_mp/templates/hare.config.conf.tmpl.3-node
provisioning/miniprov/hare_mp/templates/hare.config.conf.tmpl.3-node.sample
provisioning/miniprov/hare_mp/templates/hare.init.conf.tmpl.1-node
provisioning/miniprov/hare_mp/templates/hare.init.conf.tmpl.3-node
provisioning/miniprov/hare_mp/templates/hare.reset.conf.tmpl.1-node
provisioning/miniprov/hare_mp/templates/hare.reset.conf.tmpl.3-node
provisioning/miniprov/hare_mp/templates/hare.test.conf.tmpl.1-node
provisioning/miniprov/hare_mp/templates/hare.test.conf.tmpl.3-node
provisioning/miniprov/test/test_validator.py

Accommodating recent key related changes for storage_set_id.
Key name storage_set_id chenged to storage_set.

EOS-24381 : Integration task with Motr, S3 for F-99A

---

hax/helper/generate_sysconf.py
hax/helper/update_conf.py
provisioning/miniprov/hare_mp/main.py
provisioning/miniprov/hare_mp/store.py
utils/hare-fetch-fids
utils/update-consul-conf
utils/utils.py

EOS-24821: Run motr-mkfs out side hctl bootstrap

---

Makefile
hax/hax/motr/ffi.py

(cherry picked from commit a41717eb2fdbfa4a591da52b55b5835b982bdd72)

Add ARM64/AArch64 support

---

provisioning/miniprov/hare_mp/main.py

Using 'cortx>common>setup_type' to get setup type
**Also log rotation configuration will be common for all setup types
So removed check for setup type to decide log rotation configuration**

EOS-25665: Wrong key is being used for checking server type

---

README.md

Clarify what should be done in case of CentOS 7 and 8 OS versions.
-----
[View rendered README.md](https://github.com/Seagate/cortx-hare/blob/andriytk-patch-1/README.md)

README: update facter installation steps

---

README.md
cfgen/cfgen
hare.spec
hax/hax/filestats.py
hax/hax/handler.py
hax/hax/message.py
hax/hax/motr/__init__.py
hax/hax/motr/ffi.py
hax/hax/motr/hax.c
hax/hax/motr/hax.h
hax/hax/motr/rconfc.py
hax/test/integration/test_motr.py
hax/test/integration/test_server.py
hax/test/integration/testutils.py
utils/hare-bootstrap

null
-----
[View rendered README.md](https://github.com/mssawant/cortx-hare-1/blob/main_kubernetes/README.md)

Pull some main commits into kubernetes

---

utils/check-service
utils/hare-bootstrap
utils/update-consul-conf

Starting consul as server.
Modified check-service to take host(hostname or IP address) as input
TODO: Test

EOS-25791 'hctl bootstrap' is not working on Hare kubernetes branch

---

README.md
cfgen/cfgen
hax/hax/consul/cache.py
hax/hax/handler.py
hax/hax/hax.py
hax/hax/message.py
hax/hax/motr/__init__.py
hax/hax/motr/ffi.py
hax/hax/motr/hax.c
hax/hax/motr/hax.h
hax/hax/motr/planner.py
hax/hax/util.py
hax/test/integration/test_motr.py
hax/test/integration/testutils.py
hax/test/test_work_planner.py

Due to lack of plan to promote kubernetes branch to main, until that happens, merging certain required commits from kubernetes to main branch to fix relevant issues.
-----
[View rendered README.md](https://github.com/mssawant/cortx-hare-1/blob/pv-dirty-main/README.md)

Merge certain commits from kubernetes branch to main

---

provisioning/miniprov/hare_mp/main.py

Solution: Added check for tcp protocol

EOS-26729: Modify consul endpoint handling to connect to endpoint with tcp protocol

---

.github/pull_request_template.md

Signed-off-by: Gaurav Chaudhari <gaurav.chaudhari@seagate.com>
-----
[View rendered .github/pull_request_template.md](https://github.com/gauravchaudhari02/cortx-hare/blob/add-template/.github/pull_request_template.md)

Adhoc :  Add PR template

---

hax/hax/util.py
provisioning/miniprov/hare_mp/main.py

It is possible that not all the remote and local process statuses
are updated on every node. For more reliability it is better to
check all the processes status per node explicity.
Solution:
Iterate over each node's processes and check the corresponding status
in Consul KV.

EOS-26836: wait function in init is not reliable

---

provisioning/miniprov/hare_mp/main.py

Problem:
By default the stream in setup_logging is sys.stderr
which is populating the logs in the stderr. stderr
indicates the log type as error. So all logs should
be populated on stdout. Error can be indicated by
return value, instead of log type as stderr.
Solution:
Changed stream from sys.stderr to sys.stdout in setup_logging
Signed-off-by: Bhargav Dekivadiya <bhargav.dekivadiya@seagate.com>
- Problem statement
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

EOS-26779: Logging configuration in miniprovisioner needs

---

cfgen/cfgen
hax/hax/hax.py
hax/hax/util.py
hax/helper/configure.py
provisioning/miniprov/hare_mp/cdf.py
provisioning/miniprov/hare_mp/main.py
provisioning/miniprov/hare_mp/store.py
provisioning/miniprov/hare_mp/utils.py
provisioning/miniprov/test/test_cdf.py
systemd/consul-client-conf.json.in
systemd/consul-server-conf.json.in
utils/update-consul-conf

This PR is created for merging feature branch K8s_pod_separation to kubernetes branch.
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

Merging K8s_pod_separation feature branch to kubernetes

---

cfgen/examples/singlenode.yaml
cfgen/tests/sample-confd.dhall
cfgen/tests/singlenode.dhall

**Problem:**
Hare's `make cfgen` tests are failing.
**Solution:**
Need modifications in cfgen, sample files and corresponding dhall
files to fix the tests.

EOS-26855: Fix Hare cfgen tests

---

hax/hax/motr/__init__.py

Hare, on receiving entrypoint request from a motr process fetches the
required information from Consul in-order to prepare the entrypoint
reply. If the required information is not available, Hare drops the
entrypoint requestsilently, expecting motr would timeout and resend
the entrypoint request. This mechanism was introduced to reduce the
number of entrypoint requests received from a motr process when Hare
replies with EAGAIN.
Solution:
Add a delay of 1 second before replying to entrypoint request in case
of a failure for now.

EOS-27971:Problem: subsequent entrypoint requests are not received from motr

---

hctl
rules/sns-rebalance
rules/sns-repair
utils/hare-rebalance
utils/hare-repair

Revive sns-related `hctl repair/rebalance` commands.
Related to https://jts.seagate.com/browse/EOS-27765.

utils: revive sns hctl repair/rebalance cmds

---

provisioning/miniprov/hare_mp/cdf.py

Problem: Protocol information needs to be retrieved from endpoint flag
Solution:
Modified code to read 'cortx>hare>hax>endpoints' which is in the format
'<protocol>://<hostname>:<port>' and getting interface type(protocol) from it
Tested 'config' stage by adding following keys in confstore
```
cortx:
hare:
hax:
endpoints:
- tcp://cortx-data-headless-svc-ssc-vm-g3-rhev4-2623:22001
- tcp://cortx-data-headless-svc-ssc-vm-g2-rhev4-2784:22001
- tcp://cortx-data-headless-svc-ssc-vm-g2-rhev4-2785:22001
- tcp://cortx-server-headless-svc-ssc-vm-g2-rhev4-2784:22001
- tcp://cortx-server-headless-svc-ssc-vm-g3-rhev4-2623:22001
- tcp://cortx-server-headless-svc-ssc-vm-g2-rhev4-2785:22001
- …
```

EOS-28475 Hare need to stop using 'cortx>motr>interface_type' key

---

hax/hax/queue/__init__.py
rules/sns-repair

Solution:
Add sns command to broadcast queue.

CORTX-290100:sns: sns operation is not a broadcast

---

hax/hax/motr/__init__.py
hax/hax/queue/offset.py
hax/hax/util.py
hax/test/integration/test_server.py
hax/test/test_offset_storage.py
provisioning/miniprov/hare_mp/main.py

**Solution:** Added retry mechanism while reading consul kv
**Test**: Tested 15 node deployment and IOs

CORTX-29444: Consul KV is being accessed before import is completed

---

hax/hax/bytecount.py

Due to the unavailability of motr's byte count data, consul kv maybe not be
updated with appropriate keys. And fetching those keys lead to
HAConsistencyException and aborting the thread.
Such delays from motr land are expected, so this kind of error can be
swallowed and next timely attempts will be made.
```
2022-03-22 10:34:37,697 [ERROR] {byte-count-updater} Aborting due to an error
Traceback (most recent call last):
File "/opt/seagate/cortx/hare/lib64/python3.6/site-packages/hax/bytecount.py", line 149, in _execute
pver_items = self._get_pver_with_pver_status(motr)
File "/opt/seagate/cortx/hare/lib64/python3.6/site-packages/hax/bytecount.py", line 63, in _get_pver_with_pver_status
iosservice_items = self.consul.kv.kv_get('ioservices/', recurse=True)
File …
```

CORTX-29142: Bytecount thread exiting due to HAConsistencyException

---

README.md

Testing if PRs work for me. Just a minor fix in a command in the README
-----
[View rendered README.md](https://github.com/trshaffer/cortx-hare/blob/test-pr/README.md)

Test PR: minor README fix

---

hax/hax/util.py

With dynamic Consul node name related changes, Hare maintains a mapping
of node's hostname to Consul node name. This mapping is created during
corresponding node's provisioning. Thus, if a particular node is not
provisioned, its corresponding mapping will be missing from Consul.
Motr processes reqeust for the entire cluster state from Hare, during
which Hare requires the hostname to Consul nodename mapping in-order
to fetch the corresponding node's status via `get_consul_node()`,
and `get_consul_node()` will keep repeating and continously try to
fetch corresponding Consul nodename until it is successful in doing
so. This may block the overall bootstrap process.
Solution:
Do not repeat `get_consul_node()` on failure but report the corresponding
node as offline on failure.
Signed-off-by: …

util: get_consul_node() keeps repeating and blocks startup

---

hax/hax/server.py

This reverts commit cbafa24871ee08e0e3f5d7a828914519e9c4b77a.

Revert "server: consul sends duplicate events for already processed events

---

hax/hax/motr/hax.c

CORTX-31300: Memory leak in hax m0_ha_proc_counters_fetch API
Solution: As part of CORTX-27707 analysis, following pointers
count_stats->pc_bcrec and count_stats->pc_bckey were
not freed for bytecount fetch. so freeing them in
m0_ha_proc_counters_fetch
Signed-off-by: Vinoth.V <vinoth.v@seagate.com>
Tested on dev setup
---------------------------
`[root@ssc-vm-g2-rhev4-1980 cortx-motr]# hctl status
Bytecount:
critical : 0
damaged : 0
degraded : 0
healthy : 0
Data pool:
0x6f00000000000001:0x2b 'the pool'
Profile:
0x7000000000000001:0x47 'default': 'the pool' None None
Services:
ssc-vm-g2-rhev4-1980.colo.seagate.com  (RC)
[started]  hax                 0x7200000000000001:0x6          inet:tcp:192.168.58.249@22001
[started]  confd               0x7200000000000001:0x9 …

CORTX-31300: Memory leak in hax m0_ha_proc_counters_fetch API

---

hax/test/test_failure.py

This is a unit test to check the behavior of drive state failure.
We invoke the handler for a device_state_set. We also check that the
failure is broadcast to motr.

CORTX-29828: Unit Tests: Drive state change broadcast and KV update

---

hax/hax/ha/event/event.py
hax/hax/ha/ha.py
hax/hax/ha/resource/__init__.py
hax/hax/ha/resource/node.py
hax/hax/ha/resource/resource.py
hax/hax/ha/types.py
hax/hax/ha/utils.py
hax/hax/hax.py
hax/hax/server.py

**Solution:**
Added new base classes for resources and events. These calsses will be
used as parent classes for all the resources and events

CORTX-31068: Refactoring needed for Hare-ha communication module

---

.github/auto_assign.yml

Signed-off-by: Mukul Malhotra <mukul.malhotra@seagate.com>
Gatekeeper added to the Hare repo

CORTX-32101: Gatekeeper Added

---

CODE_OF_CONDUCT.md
README.md

Solution: Add second space for each line.
Signed-off-by: hessio <patrick.hession@seagate.com>
-----
[View rendered CODE_OF_CONDUCT.md](https://github.com/hessio/cortx-hare/blob/codacy-fix1/CODE_OF_CONDUCT.md)
[View rendered README.md](https://github.com/hessio/cortx-hare/blob/codacy-fix1/README.md)

CORTX-29982: Incorrect list-item spacing

---

rfc/16/README.md
rfc/21/README.md

Solution: Edit list numbering to increase by 1 instead of all elements labelled as 1
Signed-off-by: hessio <patrick.hession@seagate.com>
-----
[View rendered rfc/16/README.md](https://github.com/hessio/cortx-hare/blob/list-marker-value/rfc/16/README.md)

CORTX-29982: [ordered-list-marker-value] Codacy issue

---

provisioning/miniprov/hare_mp/main.py

Problem: rgw admin util fails with timeout when started before motr ios mkfs is done
When both data and server pods are started at once, mkfs of ioservice processes
done in init contianer of data pods is not yet complete, but in init container of
RGW server pods rgw admin util try to create index and user account in it.
This causes failures of the utility as mkfs and m0d shares the same endpoint.
Solution:
Make sure that mkfs done for all isoervice is checked in init phase of hare
in RGW server init containers as well. This is a one time activity per deployment.

CORTX-32355 Server Pod takes more than 10 minutes to start when started concurrently with data pod

---

Makefile
cfgen/cfgen
hax/hax/hax.py
hax/hax/server.py
hax/helper/configure.py
hax/helper/generate_sysconf.py
hax/setup.py
hctl
provisioning/miniprov/hare_mp/cdf.py
provisioning/miniprov/hare_mp/hax_starter.py
provisioning/miniprov/hare_mp/main.py
provisioning/miniprov/hare_mp/utils.py
rfc/11/README.md
systemd/hare-consul
systemd/hare-consul-agent.service
systemd/hare-hax.service
utils/check-service
utils/elect-rc-leader
utils/generate-coverage
utils/get-process-state
utils/get-service-health
utils/h0q
utils/hare-bootstrap
utils/hare-reportbug
utils/hare-status
utils/m0crate-io-conf
utils/mk-consul-env
utils/preboot-motr-setup
utils/s3auth-disable
utils/update-consul-conf

Signed-off-by: Vimlesh Kumar <vimlesh.kumar@seagate.com>
-----
[View rendered rfc/11/README.md](https://github.com/vimleshsgt/cortx-hare/blob/esiwace2-dkrz/rfc/11/README.md)

Moving cortx-hare completely in user space hence in user home directory

---

hax/hax/motr/ffi.py
hax/setup.py

Signed-off-by: Vimlesh Kumar <vimlesh.kumar@seagate.com>

Making isa-l related code changes to take it from user home directory

---

ha-simulator/prod_consumer.py
hax/hax/bytecount.py
hax/hax/ha/message_interface/__init__.py
hax/hax/motr/delivery.py
hax/hax/motr/planner.py
hax/hax/motr/util.py
hax/hax/queue/cli.py
hax/hax/queue/confobjutil.py
hax/hax/queue/offset.py
hax/hax/types.py
hax/test/integration/testutils.py
hax/test/test_delivery_herald.py
hax/test/test_work_planner.py
utils/utils.py

Problem: Reduce the number of Critical and minor Codacy issues. Identify Test coverage of modules where security and other fixes are done.  
Solution:  a) Code/doc comment changes in the files which had maximum issues and which does not require logical change or refactoring. 
b) Tested utils security fix.
c) False positive and conflicting Codacy rules will be disabled.

CORTX-33669 critical/minor Codacy fixes related to style and security

---

cfgen/cfgen
ha-simulator/docker/Dockerfile
hax/hax/common/__init__.py
hax/hax/ha/message_type/__init__.py
hax/hax/ha/message_type/message_type.py
hax/hax/ha/resource/__init__.py
hax/hax/handler.py
hax/hax/message.py
hax/hax/motr/rconfc.py
hax/hax/queue/__init__.py
hax/hax/server.py
hax/helper/configure.py
hax/helper/exec.py
hax/helper/generate_sysconf.py
hax/test/integration/test_server.py
hax/test/integration/testutils.py
hax/test/test_delivery_herald.py
hax/test/test_failure.py
hax/test/test_work_planner.py
provisioning/miniprov/hare_mp/consul_starter.py
provisioning/miniprov/hare_mp/hax_starter.py
provisioning/miniprov/hare_mp/main.py
provisioning/miniprov/hare_mp/types.py
provisioning/miniprov/hare_mp/utils.py
provisioning/miniprov/hare_mp/validator.py
provisioning/miniprov/test/__init__.py
provisioning/miniprov/test/test_cdf.py
utils/utils.py

Problem: disable false positive, conflicting rules and reduce the Codacy issues.
Solution:
a) Fix all pep257 issues.
b) False positive and conflicting Codacy rules are disabled in codacy flake8.
c) Fix medium priority and security issues.

CORTX-33151 Codacy fixes related to style and security
